// GENERATED FILE - do not edit.
//
// Regenerate with:  python3 tools/marlin/gen_mcommands.py
// Source of truth:  doc/marlin-gcode/commands.json
// Extracted from:   MarlinFirmware/MarlinDocumentation @ 0856d12b0253378bc8d17a246fb09fc8c5437997
// How and why:      tools/marlin/README.md, github.com/qw3rtrun/p3d-web-ui/issues/13
//
// The registry over every Marlin command and the named facade this project calls. The 295
// command classes themselves are one file each under `command/`, named after the class
// they hold, and are star-imported here rather than named 295 times.

package org.qw3rtrun.p3d.g.marlin

import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.marlin.command.*
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * Every Marlin command this module knows how to write, and the lookup that reads one back.
 *
 * Three views of the same 295 commands - [all], [info] and [decoders] - all built in `G`
 * then `M` then `T` order and all **index-aligned**, so `all[i]`, `info[i]` and
 * `decoders[i]` are the same command. Callers that need to pair a class with its metadata
 * or its decoder may rely on that.
 */
object MarlinCommands {

    /**
     * One bare instance per command - every parameter absent.
     *
     * This is the enumeration of what the module can *write*: a bare instance encodes to
     * exactly its code, which is the claim the generated cover checks class by class.
     * Reading is [decoders]' job; nothing here needs an instance to decode against any
     * more, because `head()` and `decodeParams()` moved to each class's companion.
     */
    val all: List<GRq<*>> = listOf(
        LinearMoveG0(),
        LinearMoveG1(),
        ArcOrCircleMoveG2(),
        ArcOrCircleMoveG3(),
        Dwell(),
        BezierCubicSplineMove(),
        DirectStepperMove(),
        Retract(),
        Recover(),
        CleanTheNozzle(),
        CNCWorkspacePlanesG17(),
        CNCWorkspacePlanesG18(),
        CNCWorkspacePlanesG19(),
        InchUnits(),
        MillimeterUnits(),
        MeshValidationPattern(),
        ParkToolhead(),
        AutoHome(),
        BedLeveling3Point(),
        BedLevelingBilinear(),
        BedLevelingLinear(),
        BedLevelingManual(),
        BedLevelingUnified(),
        BedLeveling(),
        SingleZProbe(),
        DockSled(),
        UndockSled(),
        DeltaAutoCalibration(),
        MechanicalGantryCalibration(),
        ZSteppersAutoAlignment(),
        TrammingAssistant(),
        ProbeTargetG38_2(),
        ProbeTargetG38_3(),
        ProbeTargetG38_4(),
        ProbeTargetG38_5(),
        MoveToMeshCoordinate(),
        MoveInMachineCoordinates(),
        SelectWorkspaceG54(),
        SelectWorkspaceG55(),
        SelectWorkspaceG56(),
        SelectWorkspaceG57(),
        SelectWorkspaceG58(),
        SelectWorkspaceG59(),
        SelectWorkspaceG59_1(),
        SelectWorkspaceG59_2(),
        SelectWorkspaceG59_3(),
        StoredPositions(),
        ReturnToSavedPosition(),
        ProbeTemperatureCalibration(),
        CancelCurrentMotionMode(),
        AbsolutePositioning(),
        RelativePositioning(),
        SetPosition(),
        BacklashAndToolheadOffsetCalibration(),
        UnconditionalStopM0(),
        UnconditionalStopM1(),
        SpindleCWLaserOn(),
        SpindleCCWLaserOn(),
        SpindleLaserOff(),
        CoolantControlsM7(),
        CoolantControlsM8(),
        CoolantControlsM9(),
        VacuumBlowerControlM10(),
        VacuumBlowerControlM11(),
        ExpectedPrinterCheck(),
        EnableSteppers(),
        DisableSteppersM18(),
        ListSDCard(),
        InitSDCard(),
        ReleaseSDCard(),
        SelectSDFile(),
        StartOrResumeSDPrint(),
        PauseSDPrint(),
        SetSDPosition(),
        ReportSDPrintStatus(),
        StartSDWrite(),
        StopSDWrite(),
        DeleteSDFile(),
        ReportPrintTime(),
        SelectAndStart(),
        GetLongPath(),
        SDCardSorting(),
        SetPinState(),
        PinsDebugging(),
        ProbeRepeatabilityTest(),
        SetPrintProgress(),
        StartPrintJobTimer(),
        PausePrintJobTimer(),
        StopPrintJobTimer(),
        PrintJobStats(),
        PowerOn(),
        PowerOff(),
        EAbsolute(),
        ERelative(),
        DisableSteppersM84(),
        InactivityShutdown(),
        HotendIdleTimeout(),
        DisableHotendIdleTimeout(),
        SetAxisStepsPerUnit(),
        FreeMemory(),
        ConfigureBedDistanceSensor(),
        SetHotendTemperature(),
        ReportHotendTemperature(),
        SetFanSpeed(),
        FanOff(),
        BreakAndContinue(),
        WaitForHotendTemperature(),
        SetGetLineNumber(),
        DebugLevel(),
        FullShutdown(),
        HostKeepalive(),
        GetCurrentPosition(),
        FirmwareInfo(),
        SetLCDMessage(),
        SerialPrint(),
        EndstopStates(),
        EnableEndstops(),
        DisableEndstops(),
        TMCDebugging(),
        FanTachometers(),
        ParkHead(),
        Baricuda1Open(),
        Baricuda1Close(),
        Baricuda2Open(),
        Baricuda2Close(),
        SetBedTemperature(),
        SetChamberTemperature(),
        SetLaserCoolerTemperature(),
        SetMaterialPreset(),
        SetTemperatureUnits(),
        SetRGBWColor(),
        PositionAutoReport(),
        TemperatureAutoReport(),
        SetMixFactor(),
        SaveMix(),
        SetMix(),
        GradientMix(),
        WaitForBedTemperature(),
        WaitForChamberTemperature(),
        WaitForProbeTemperature(),
        WaitForLaserCoolerTemperature(),
        VolumetricExtrusionDiameter(),
        PrintTravelMoveLimits(),
        SetMaxFeedrate(),
        SetStartingAcceleration(),
        SetAdvancedSettings(),
        SetHomeOffsets(),
        FirmwareRetractionSettings(),
        FirmwareRecoverSettings(),
        SetAutoRetract(),
        HomingFeedrate(),
        SoftwareEndstops(),
        FilamentSwapParameters(),
        SetHotendOffset(),
        SetFeedratePercentage(),
        SetFlowPercentage(),
        WaitForPinState(),
        TriggerCamera(),
        LCDContrast(),
        LCDSleepBacklightTimeout(),
        LCDBrightness(),
        I2CSend(),
        I2CRequest(),
        ScanI2CBus(),
        ServoPosition(),
        EditServoAngles(),
        DetachServo(),
        Babystep(),
        PlayTone(),
        SetHotendPID(),
        ColdExtrude(),
        PIDAutotune(),
        SetBedPID(),
        UserThermistorParameters(),
        ModelPredictiveTempControl(),
        SetChamberPID(),
        SetMicroStepping(),
        SetMicrostepPins(),
        CaseLightControl(),
        SCARAThetaA(),
        SCARAThetaB(),
        SCARAPsiA(),
        SCARAPsiB(),
        SCARAPsiC(),
        ActivateSolenoid(),
        DeactivateSolenoids(),
        FinishMoves(),
        DeployProbe(),
        StowProbe(),
        MMU2FilamentType(),
        FilamentWidthSensorNominalDiameter(),
        FilamentWidthSensorOn(),
        FilamentWidthSensorOff(),
        ReadFilamentWidth(),
        Quickstop(),
        FilamentRunout(),
        PowerLossRecovery(),
        LCDLanguage(),
        BedLevelingState(),
        SetMeshValue(),
        SetZMotorXY(),
        XTwistCompensation(),
        BacklashCompensation(),
        HomeOffsetsHere(),
        PowerMonitor(),
        CancelObjects(),
        FixedTimeMotion(),
        FTMotionTrajectorySmoothing(),
        SaveSettings(),
        RestoreSettings(),
        FactoryReset(),
        ReportSettings(),
        ValidateEEPROMContents(),
        LockMachine(),
        UnlockMachine(),
        SetPasscode(),
        AbortSDPrint(),
        EndstopsAbortSD(),
        MachineName(),
        EthernetIPAddressNetworkIF(),
        EthernetSubnetMask(),
        EthernetGatewayIPAddress(),
        SetTMCSteppingMode(),
        SerialBaudRate(),
        NonlinearExtrusionControl(),
        ZVInputShaping(),
        FilamentChange(),
        ConfigureFilamentChange(),
        MultiNozzleMode(),
        SCARAConfiguration(),
        DeltaConfiguration(),
        DualEndstopOffsets(),
        SetDeltaEndstopAdjustments(),
        DuetSmartEffectorSensitivity(),
        LoadFilament(),
        UnloadFilament(),
        ControllerFanSettings(),
        RepeatMarker(),
        GCodeMacrosM810(),
        GCodeMacrosM811(),
        GCodeMacrosM812(),
        GCodeMacrosM813(),
        GCodeMacrosM814(),
        GCodeMacrosM815(),
        GCodeMacrosM816(),
        GCodeMacrosM817(),
        GCodeMacrosM818(),
        GCodeMacrosM819(),
        ReportGCodeMacros(),
        XYZProbeOffset(),
        BedSkewCompensation(),
        I2CPositionEncodersM860(),
        I2CPositionEncodersM861(),
        I2CPositionEncodersM862(),
        I2CPositionEncodersM863(),
        I2CPositionEncodersM864(),
        I2CPositionEncodersM865(),
        I2CPositionEncodersM866(),
        I2CPositionEncodersM867(),
        I2CPositionEncodersM868(),
        I2CPositionEncodersM869(),
        ProbeTemperatureConfig(),
        HandlePromptResponse(),
        LinearAdvanceFactor(),
        StepperMotorCurrent(),
        TrimpotStepperMotorCurrent(),
        SetTrimpotPins(),
        ReportDACStepperCurrent(),
        CommitDACToEEPROM(),
        TMCOTPreWarnCondition(),
        ClearTMCOTPreWarn(),
        SetHybridThresholdSpeed(),
        TMCBumpSensitivity(),
        TMCZAxisCalibration(),
        L6474ThermalWarningTest(),
        L6474OvercurrentWarningTest(),
        L6474SpeedWarningTest(),
        TMCChopperTiming(),
        TMCHomingCurrent(),
        StartSDLogging(),
        MagneticParkingExtruder(),
        BackUpFlashSettingsToSD(),
        RestoreFlashFromSD(),
        TouchScreenCalibration(),
        FirmwareUpdate(),
        STOPRestart(),
        MAX7219Control(),
        SelectOrReportToolT0(),
        SelectOrReportToolT1(),
        SelectOrReportToolT2(),
        SelectOrReportToolT3(),
        SelectOrReportToolT4(),
        SelectOrReportToolT5(),
        SelectOrReportToolT6(),
        SelectOrReportToolT7(),
    )

    /**
     * The reading half: every command's companion object, which is its [GRqDecoder].
     *
     * A bare class name here *is* the companion - `LinearMoveG0`, not `LinearMoveG0()`.
     */
    val decoders: List<GRqDecoder<*>> = listOf(
        LinearMoveG0,
        LinearMoveG1,
        ArcOrCircleMoveG2,
        ArcOrCircleMoveG3,
        Dwell,
        BezierCubicSplineMove,
        DirectStepperMove,
        Retract,
        Recover,
        CleanTheNozzle,
        CNCWorkspacePlanesG17,
        CNCWorkspacePlanesG18,
        CNCWorkspacePlanesG19,
        InchUnits,
        MillimeterUnits,
        MeshValidationPattern,
        ParkToolhead,
        AutoHome,
        BedLeveling3Point,
        BedLevelingBilinear,
        BedLevelingLinear,
        BedLevelingManual,
        BedLevelingUnified,
        BedLeveling,
        SingleZProbe,
        DockSled,
        UndockSled,
        DeltaAutoCalibration,
        MechanicalGantryCalibration,
        ZSteppersAutoAlignment,
        TrammingAssistant,
        ProbeTargetG38_2,
        ProbeTargetG38_3,
        ProbeTargetG38_4,
        ProbeTargetG38_5,
        MoveToMeshCoordinate,
        MoveInMachineCoordinates,
        SelectWorkspaceG54,
        SelectWorkspaceG55,
        SelectWorkspaceG56,
        SelectWorkspaceG57,
        SelectWorkspaceG58,
        SelectWorkspaceG59,
        SelectWorkspaceG59_1,
        SelectWorkspaceG59_2,
        SelectWorkspaceG59_3,
        StoredPositions,
        ReturnToSavedPosition,
        ProbeTemperatureCalibration,
        CancelCurrentMotionMode,
        AbsolutePositioning,
        RelativePositioning,
        SetPosition,
        BacklashAndToolheadOffsetCalibration,
        UnconditionalStopM0,
        UnconditionalStopM1,
        SpindleCWLaserOn,
        SpindleCCWLaserOn,
        SpindleLaserOff,
        CoolantControlsM7,
        CoolantControlsM8,
        CoolantControlsM9,
        VacuumBlowerControlM10,
        VacuumBlowerControlM11,
        ExpectedPrinterCheck,
        EnableSteppers,
        DisableSteppersM18,
        ListSDCard,
        InitSDCard,
        ReleaseSDCard,
        SelectSDFile,
        StartOrResumeSDPrint,
        PauseSDPrint,
        SetSDPosition,
        ReportSDPrintStatus,
        StartSDWrite,
        StopSDWrite,
        DeleteSDFile,
        ReportPrintTime,
        SelectAndStart,
        GetLongPath,
        SDCardSorting,
        SetPinState,
        PinsDebugging,
        ProbeRepeatabilityTest,
        SetPrintProgress,
        StartPrintJobTimer,
        PausePrintJobTimer,
        StopPrintJobTimer,
        PrintJobStats,
        PowerOn,
        PowerOff,
        EAbsolute,
        ERelative,
        DisableSteppersM84,
        InactivityShutdown,
        HotendIdleTimeout,
        DisableHotendIdleTimeout,
        SetAxisStepsPerUnit,
        FreeMemory,
        ConfigureBedDistanceSensor,
        SetHotendTemperature,
        ReportHotendTemperature,
        SetFanSpeed,
        FanOff,
        BreakAndContinue,
        WaitForHotendTemperature,
        SetGetLineNumber,
        DebugLevel,
        FullShutdown,
        HostKeepalive,
        GetCurrentPosition,
        FirmwareInfo,
        SetLCDMessage,
        SerialPrint,
        EndstopStates,
        EnableEndstops,
        DisableEndstops,
        TMCDebugging,
        FanTachometers,
        ParkHead,
        Baricuda1Open,
        Baricuda1Close,
        Baricuda2Open,
        Baricuda2Close,
        SetBedTemperature,
        SetChamberTemperature,
        SetLaserCoolerTemperature,
        SetMaterialPreset,
        SetTemperatureUnits,
        SetRGBWColor,
        PositionAutoReport,
        TemperatureAutoReport,
        SetMixFactor,
        SaveMix,
        SetMix,
        GradientMix,
        WaitForBedTemperature,
        WaitForChamberTemperature,
        WaitForProbeTemperature,
        WaitForLaserCoolerTemperature,
        VolumetricExtrusionDiameter,
        PrintTravelMoveLimits,
        SetMaxFeedrate,
        SetStartingAcceleration,
        SetAdvancedSettings,
        SetHomeOffsets,
        FirmwareRetractionSettings,
        FirmwareRecoverSettings,
        SetAutoRetract,
        HomingFeedrate,
        SoftwareEndstops,
        FilamentSwapParameters,
        SetHotendOffset,
        SetFeedratePercentage,
        SetFlowPercentage,
        WaitForPinState,
        TriggerCamera,
        LCDContrast,
        LCDSleepBacklightTimeout,
        LCDBrightness,
        I2CSend,
        I2CRequest,
        ScanI2CBus,
        ServoPosition,
        EditServoAngles,
        DetachServo,
        Babystep,
        PlayTone,
        SetHotendPID,
        ColdExtrude,
        PIDAutotune,
        SetBedPID,
        UserThermistorParameters,
        ModelPredictiveTempControl,
        SetChamberPID,
        SetMicroStepping,
        SetMicrostepPins,
        CaseLightControl,
        SCARAThetaA,
        SCARAThetaB,
        SCARAPsiA,
        SCARAPsiB,
        SCARAPsiC,
        ActivateSolenoid,
        DeactivateSolenoids,
        FinishMoves,
        DeployProbe,
        StowProbe,
        MMU2FilamentType,
        FilamentWidthSensorNominalDiameter,
        FilamentWidthSensorOn,
        FilamentWidthSensorOff,
        ReadFilamentWidth,
        Quickstop,
        FilamentRunout,
        PowerLossRecovery,
        LCDLanguage,
        BedLevelingState,
        SetMeshValue,
        SetZMotorXY,
        XTwistCompensation,
        BacklashCompensation,
        HomeOffsetsHere,
        PowerMonitor,
        CancelObjects,
        FixedTimeMotion,
        FTMotionTrajectorySmoothing,
        SaveSettings,
        RestoreSettings,
        FactoryReset,
        ReportSettings,
        ValidateEEPROMContents,
        LockMachine,
        UnlockMachine,
        SetPasscode,
        AbortSDPrint,
        EndstopsAbortSD,
        MachineName,
        EthernetIPAddressNetworkIF,
        EthernetSubnetMask,
        EthernetGatewayIPAddress,
        SetTMCSteppingMode,
        SerialBaudRate,
        NonlinearExtrusionControl,
        ZVInputShaping,
        FilamentChange,
        ConfigureFilamentChange,
        MultiNozzleMode,
        SCARAConfiguration,
        DeltaConfiguration,
        DualEndstopOffsets,
        SetDeltaEndstopAdjustments,
        DuetSmartEffectorSensitivity,
        LoadFilament,
        UnloadFilament,
        ControllerFanSettings,
        RepeatMarker,
        GCodeMacrosM810,
        GCodeMacrosM811,
        GCodeMacrosM812,
        GCodeMacrosM813,
        GCodeMacrosM814,
        GCodeMacrosM815,
        GCodeMacrosM816,
        GCodeMacrosM817,
        GCodeMacrosM818,
        GCodeMacrosM819,
        ReportGCodeMacros,
        XYZProbeOffset,
        BedSkewCompensation,
        I2CPositionEncodersM860,
        I2CPositionEncodersM861,
        I2CPositionEncodersM862,
        I2CPositionEncodersM863,
        I2CPositionEncodersM864,
        I2CPositionEncodersM865,
        I2CPositionEncodersM866,
        I2CPositionEncodersM867,
        I2CPositionEncodersM868,
        I2CPositionEncodersM869,
        ProbeTemperatureConfig,
        HandlePromptResponse,
        LinearAdvanceFactor,
        StepperMotorCurrent,
        TrimpotStepperMotorCurrent,
        SetTrimpotPins,
        ReportDACStepperCurrent,
        CommitDACToEEPROM,
        TMCOTPreWarnCondition,
        ClearTMCOTPreWarn,
        SetHybridThresholdSpeed,
        TMCBumpSensitivity,
        TMCZAxisCalibration,
        L6474ThermalWarningTest,
        L6474OvercurrentWarningTest,
        L6474SpeedWarningTest,
        TMCChopperTiming,
        TMCHomingCurrent,
        StartSDLogging,
        MagneticParkingExtruder,
        BackUpFlashSettingsToSD,
        RestoreFlashFromSD,
        TouchScreenCalibration,
        FirmwareUpdate,
        STOPRestart,
        MAX7219Control,
        SelectOrReportToolT0,
        SelectOrReportToolT1,
        SelectOrReportToolT2,
        SelectOrReportToolT3,
        SelectOrReportToolT4,
        SelectOrReportToolT5,
        SelectOrReportToolT6,
        SelectOrReportToolT7,
    )

    /** What one command class models: its code, its name, and the letters it accepts. */
    data class Info(
        val code: String,
        val className: String,
        val letters: Set<Char>,
        val bareString: Boolean,
    )

    /**
     * The same commands as metadata, for callers and tests that need to ask what a command
     * accepts without building one. `letters` is every parameter letter the class has a
     * property for, which is the honest measure of coverage against Marlin's own docs.
     */
    val info: List<Info> = listOf(
        Info("G0", "LinearMoveG0", setOf('A', 'B', 'C', 'E', 'F', 'S', 'U', 'V', 'W', 'X', 'Y', 'Z'), false),
        Info("G1", "LinearMoveG1", setOf('A', 'B', 'C', 'E', 'F', 'S', 'U', 'V', 'W', 'X', 'Y', 'Z'), false),
        Info("G2", "ArcOrCircleMoveG2", setOf('A', 'B', 'C', 'E', 'F', 'I', 'J', 'P', 'R', 'S', 'U', 'V', 'W', 'X', 'Y', 'Z'), false),
        Info("G3", "ArcOrCircleMoveG3", setOf('A', 'B', 'C', 'E', 'F', 'I', 'J', 'P', 'R', 'S', 'U', 'V', 'W', 'X', 'Y', 'Z'), false),
        Info("G4", "Dwell", setOf('P', 'S'), false),
        Info("G5", "BezierCubicSplineMove", setOf('E', 'F', 'I', 'J', 'P', 'Q', 'S', 'X', 'Y'), false),
        Info("G6", "DirectStepperMove", setOf('E', 'I', 'R', 'S', 'X', 'Y', 'Z'), false),
        Info("G10", "Retract", setOf('S'), false),
        Info("G11", "Recover", emptySet(), false),
        Info("G12", "CleanTheNozzle", setOf('P', 'R', 'S', 'T', 'X', 'Y', 'Z'), false),
        Info("G17", "CNCWorkspacePlanesG17", emptySet(), false),
        Info("G18", "CNCWorkspacePlanesG18", emptySet(), false),
        Info("G19", "CNCWorkspacePlanesG19", emptySet(), false),
        Info("G20", "InchUnits", emptySet(), false),
        Info("G21", "MillimeterUnits", emptySet(), false),
        Info("G26", "MeshValidationPattern", setOf('B', 'C', 'D', 'F', 'H', 'I', 'K', 'L', 'O', 'P', 'Q', 'R', 'S', 'U', 'X', 'Y'), false),
        Info("G27", "ParkToolhead", setOf('P'), false),
        Info("G28", "AutoHome", setOf('A', 'B', 'C', 'H', 'L', 'O', 'R', 'U', 'V', 'W', 'X', 'Y', 'Z'), false),
        Info("G29", "BedLeveling3Point", setOf('A', 'C', 'D', 'E', 'J', 'O', 'Q', 'V'), false),
        Info("G29", "BedLevelingBilinear", setOf('A', 'B', 'C', 'D', 'E', 'F', 'H', 'J', 'L', 'O', 'Q', 'R', 'S', 'V', 'W', 'X', 'Y', 'Z'), false),
        Info("G29", "BedLevelingLinear", setOf('A', 'B', 'C', 'D', 'E', 'F', 'H', 'J', 'L', 'O', 'P', 'Q', 'R', 'S', 'T', 'V', 'X', 'Y'), false),
        Info("G29", "BedLevelingManual", setOf('I', 'J', 'S', 'X', 'Y', 'Z'), false),
        Info("G29", "BedLevelingUnified", setOf('A', 'B', 'C', 'D', 'E', 'F', 'H', 'I', 'J', 'K', 'L', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y'), false),
        Info("G29", "BedLeveling", emptySet(), false),
        Info("G30", "SingleZProbe", setOf('C', 'E', 'X', 'Y'), false),
        Info("G31", "DockSled", emptySet(), false),
        Info("G32", "UndockSled", emptySet(), false),
        Info("G33", "DeltaAutoCalibration", setOf('C', 'E', 'F', 'O', 'P', 'R', 'S', 'T', 'V', 'X', 'Y', 'Z'), false),
        Info("G34", "MechanicalGantryCalibration", setOf('S', 'Z'), false),
        Info("G34", "ZSteppersAutoAlignment", setOf('A', 'E', 'I', 'L', 'R', 'S', 'T', 'Z'), false),
        Info("G35", "TrammingAssistant", setOf('S'), false),
        Info("G38.2", "ProbeTargetG38_2", setOf('F', 'X', 'Y', 'Z'), false),
        Info("G38.3", "ProbeTargetG38_3", setOf('F', 'X', 'Y', 'Z'), false),
        Info("G38.4", "ProbeTargetG38_4", setOf('F', 'X', 'Y', 'Z'), false),
        Info("G38.5", "ProbeTargetG38_5", setOf('F', 'X', 'Y', 'Z'), false),
        Info("G42", "MoveToMeshCoordinate", setOf('F', 'I', 'J', 'P'), false),
        Info("G53", "MoveInMachineCoordinates", emptySet(), false),
        Info("G54", "SelectWorkspaceG54", emptySet(), false),
        Info("G55", "SelectWorkspaceG55", emptySet(), false),
        Info("G56", "SelectWorkspaceG56", emptySet(), false),
        Info("G57", "SelectWorkspaceG57", emptySet(), false),
        Info("G58", "SelectWorkspaceG58", emptySet(), false),
        Info("G59", "SelectWorkspaceG59", emptySet(), false),
        Info("G59.1", "SelectWorkspaceG59_1", emptySet(), false),
        Info("G59.2", "SelectWorkspaceG59_2", emptySet(), false),
        Info("G59.3", "SelectWorkspaceG59_3", emptySet(), false),
        Info("G60", "StoredPositions", setOf('D', 'E', 'F', 'Q', 'S', 'X', 'Y', 'Z'), false),
        Info("G61", "ReturnToSavedPosition", setOf('E', 'F', 'S', 'X', 'Y', 'Z'), false),
        Info("G76", "ProbeTemperatureCalibration", setOf('B', 'P'), false),
        Info("G80", "CancelCurrentMotionMode", emptySet(), false),
        Info("G90", "AbsolutePositioning", emptySet(), false),
        Info("G91", "RelativePositioning", emptySet(), false),
        Info("G92", "SetPosition", setOf('A', 'B', 'C', 'E', 'U', 'V', 'W', 'X', 'Y', 'Z'), false),
        Info("G425", "BacklashAndToolheadOffsetCalibration", setOf('B', 'T', 'U', 'V'), false),
        Info("M0", "UnconditionalStopM0", setOf('P', 'S'), true),
        Info("M1", "UnconditionalStopM1", setOf('P', 'S'), true),
        Info("M3", "SpindleCWLaserOn", setOf('I', 'O', 'S'), false),
        Info("M4", "SpindleCCWLaserOn", setOf('I', 'O', 'S'), false),
        Info("M5", "SpindleLaserOff", emptySet(), false),
        Info("M7", "CoolantControlsM7", emptySet(), false),
        Info("M8", "CoolantControlsM8", emptySet(), false),
        Info("M9", "CoolantControlsM9", emptySet(), false),
        Info("M10", "VacuumBlowerControlM10", emptySet(), false),
        Info("M11", "VacuumBlowerControlM11", emptySet(), false),
        Info("M16", "ExpectedPrinterCheck", emptySet(), true),
        Info("M17", "EnableSteppers", setOf('A', 'B', 'C', 'E', 'U', 'V', 'W', 'X', 'Y', 'Z'), false),
        Info("M18", "DisableSteppersM18", setOf('A', 'B', 'C', 'E', 'S', 'U', 'V', 'W', 'X', 'Y', 'Z'), false),
        Info("M20", "ListSDCard", setOf('F', 'L', 'T'), false),
        Info("M21", "InitSDCard", emptySet(), false),
        Info("M22", "ReleaseSDCard", emptySet(), false),
        Info("M23", "SelectSDFile", emptySet(), true),
        Info("M24", "StartOrResumeSDPrint", setOf('S', 'T'), false),
        Info("M25", "PauseSDPrint", emptySet(), false),
        Info("M26", "SetSDPosition", setOf('S'), false),
        Info("M27", "ReportSDPrintStatus", setOf('C', 'S'), false),
        Info("M28", "StartSDWrite", emptySet(), true),
        Info("M29", "StopSDWrite", emptySet(), false),
        Info("M30", "DeleteSDFile", emptySet(), true),
        Info("M31", "ReportPrintTime", emptySet(), false),
        Info("M32", "SelectAndStart", setOf('P', 'S'), false),
        Info("M33", "GetLongPath", emptySet(), true),
        Info("M34", "SDCardSorting", setOf('F', 'S'), false),
        Info("M42", "SetPinState", setOf('I', 'P', 'S', 'T'), false),
        Info("M43", "PinsDebugging", setOf('E', 'I', 'P', 'S', 'T', 'W'), false),
        Info("M48", "ProbeRepeatabilityTest", setOf('C', 'E', 'L', 'P', 'S', 'V', 'X', 'Y'), false),
        Info("M73", "SetPrintProgress", setOf('C', 'P', 'R'), false),
        Info("M75", "StartPrintJobTimer", emptySet(), true),
        Info("M76", "PausePrintJobTimer", emptySet(), false),
        Info("M77", "StopPrintJobTimer", emptySet(), false),
        Info("M78", "PrintJobStats", emptySet(), false),
        Info("M80", "PowerOn", setOf('S'), false),
        Info("M81", "PowerOff", emptySet(), false),
        Info("M82", "EAbsolute", emptySet(), false),
        Info("M83", "ERelative", emptySet(), false),
        Info("M84", "DisableSteppersM84", setOf('A', 'B', 'C', 'E', 'S', 'U', 'V', 'W', 'X', 'Y', 'Z'), false),
        Info("M85", "InactivityShutdown", setOf('S'), false),
        Info("M86", "HotendIdleTimeout", setOf('B', 'E', 'S', 'T'), false),
        Info("M87", "DisableHotendIdleTimeout", emptySet(), false),
        Info("M92", "SetAxisStepsPerUnit", setOf('A', 'B', 'C', 'E', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'), false),
        Info("M100", "FreeMemory", setOf('C', 'D', 'F', 'I'), false),
        Info("M102", "ConfigureBedDistanceSensor", setOf('S'), false),
        Info("M104", "SetHotendTemperature", setOf('B', 'F', 'I', 'S', 'T'), false),
        Info("M105", "ReportHotendTemperature", setOf('R', 'T'), false),
        Info("M106", "SetFanSpeed", setOf('I', 'P', 'S', 'T'), false),
        Info("M107", "FanOff", setOf('P'), false),
        Info("M108", "BreakAndContinue", emptySet(), false),
        Info("M109", "WaitForHotendTemperature", setOf('B', 'F', 'I', 'R', 'S', 'T'), false),
        Info("M110", "SetGetLineNumber", setOf('N'), false),
        Info("M111", "DebugLevel", setOf('S'), false),
        Info("M112", "FullShutdown", emptySet(), false),
        Info("M113", "HostKeepalive", setOf('S'), false),
        Info("M114", "GetCurrentPosition", setOf('D', 'E', 'R'), false),
        Info("M115", "FirmwareInfo", emptySet(), false),
        Info("M117", "SetLCDMessage", emptySet(), true),
        Info("M118", "SerialPrint", setOf('P'), true),
        Info("M119", "EndstopStates", emptySet(), false),
        Info("M120", "EnableEndstops", emptySet(), false),
        Info("M121", "DisableEndstops", emptySet(), false),
        Info("M122", "TMCDebugging", setOf('E', 'I', 'P', 'S', 'V', 'X', 'Y', 'Z'), false),
        Info("M123", "FanTachometers", emptySet(), false),
        Info("M125", "ParkHead", setOf('L', 'P', 'X', 'Y', 'Z'), false),
        Info("M126", "Baricuda1Open", setOf('S'), false),
        Info("M127", "Baricuda1Close", emptySet(), false),
        Info("M128", "Baricuda2Open", setOf('S'), false),
        Info("M129", "Baricuda2Close", emptySet(), false),
        Info("M140", "SetBedTemperature", setOf('I', 'S'), false),
        Info("M141", "SetChamberTemperature", setOf('S'), false),
        Info("M143", "SetLaserCoolerTemperature", setOf('S'), false),
        Info("M145", "SetMaterialPreset", setOf('B', 'F', 'H', 'S'), false),
        Info("M149", "SetTemperatureUnits", setOf('C', 'F', 'K'), false),
        Info("M150", "SetRGBWColor", setOf('B', 'I', 'K', 'P', 'R', 'S', 'U', 'W'), false),
        Info("M154", "PositionAutoReport", setOf('S'), false),
        Info("M155", "TemperatureAutoReport", setOf('S'), false),
        Info("M163", "SetMixFactor", setOf('P', 'S'), false),
        Info("M164", "SaveMix", setOf('S'), false),
        Info("M165", "SetMix", setOf('A', 'B', 'C', 'D', 'H', 'I'), false),
        Info("M166", "GradientMix", setOf('A', 'I', 'J', 'S', 'T', 'Z'), false),
        Info("M190", "WaitForBedTemperature", setOf('I', 'R', 'S', 'T'), false),
        Info("M191", "WaitForChamberTemperature", setOf('R', 'S'), false),
        Info("M192", "WaitForProbeTemperature", setOf('R', 'S'), false),
        Info("M193", "WaitForLaserCoolerTemperature", setOf('S'), false),
        Info("M200", "VolumetricExtrusionDiameter", setOf('D', 'L', 'S', 'T'), false),
        Info("M201", "PrintTravelMoveLimits", setOf('E', 'F', 'S', 'T', 'X', 'Y', 'Z'), false),
        Info("M203", "SetMaxFeedrate", setOf('E', 'T', 'X', 'Y', 'Z'), false),
        Info("M204", "SetStartingAcceleration", setOf('P', 'R', 'S', 'T'), false),
        Info("M205", "SetAdvancedSettings", setOf('B', 'E', 'J', 'S', 'T', 'X', 'Y', 'Z'), false),
        Info("M206", "SetHomeOffsets", setOf('A', 'B', 'C', 'P', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'), false),
        Info("M207", "FirmwareRetractionSettings", setOf('F', 'S', 'W', 'Z'), false),
        Info("M208", "FirmwareRecoverSettings", setOf('F', 'R', 'S', 'W'), false),
        Info("M209", "SetAutoRetract", setOf('S'), false),
        Info("M210", "HomingFeedrate", setOf('A', 'B', 'C', 'U', 'V', 'W', 'X', 'Y', 'Z'), false),
        Info("M211", "SoftwareEndstops", setOf('S'), false),
        Info("M217", "FilamentSwapParameters", setOf('A', 'B', 'C', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'O', 'P', 'Q', 'R', 'S', 'U', 'V', 'W', 'X', 'Y', 'Z'), false),
        Info("M218", "SetHotendOffset", setOf('T', 'X', 'Y', 'Z'), false),
        Info("M220", "SetFeedratePercentage", setOf('B', 'R', 'S'), false),
        Info("M221", "SetFlowPercentage", setOf('S', 'T'), false),
        Info("M226", "WaitForPinState", setOf('P', 'S'), false),
        Info("M240", "TriggerCamera", setOf('A', 'B', 'D', 'F', 'I', 'J', 'P', 'R', 'S', 'X', 'Y', 'Z'), false),
        Info("M250", "LCDContrast", setOf('C'), false),
        Info("M255", "LCDSleepBacklightTimeout", setOf('S'), false),
        Info("M256", "LCDBrightness", setOf('B'), false),
        Info("M260", "I2CSend", setOf('A', 'B', 'R', 'S'), false),
        Info("M261", "I2CRequest", setOf('A', 'B', 'S'), false),
        Info("M265", "ScanI2CBus", emptySet(), false),
        Info("M280", "ServoPosition", setOf('P', 'S'), false),
        Info("M281", "EditServoAngles", setOf('L', 'P', 'U'), false),
        Info("M282", "DetachServo", setOf('P'), false),
        Info("M290", "Babystep", setOf('P', 'S', 'X', 'Y', 'Z'), false),
        Info("M300", "PlayTone", setOf('P', 'S'), false),
        Info("M301", "SetHotendPID", setOf('C', 'D', 'E', 'F', 'I', 'L', 'P'), false),
        Info("M302", "ColdExtrude", setOf('P', 'S'), false),
        Info("M303", "PIDAutotune", setOf('C', 'D', 'E', 'S', 'U'), false),
        Info("M304", "SetBedPID", setOf('D', 'I', 'P'), false),
        Info("M305", "UserThermistorParameters", setOf('B', 'C', 'P', 'R', 'T'), false),
        Info("M306", "ModelPredictiveTempControl", setOf('A', 'C', 'E', 'F', 'H', 'P', 'R', 'S', 'T'), false),
        Info("M309", "SetChamberPID", setOf('D', 'I', 'P'), false),
        Info("M350", "SetMicroStepping", setOf('A', 'B', 'C', 'E', 'S', 'U', 'V', 'W', 'X', 'Y', 'Z'), false),
        Info("M351", "SetMicrostepPins", setOf('B', 'E', 'S', 'X', 'Y', 'Z'), false),
        Info("M355", "CaseLightControl", setOf('P', 'S'), false),
        Info("M360", "SCARAThetaA", emptySet(), false),
        Info("M361", "SCARAThetaB", emptySet(), false),
        Info("M362", "SCARAPsiA", emptySet(), false),
        Info("M363", "SCARAPsiB", emptySet(), false),
        Info("M364", "SCARAPsiC", emptySet(), false),
        Info("M380", "ActivateSolenoid", setOf('S'), false),
        Info("M381", "DeactivateSolenoids", setOf('S'), false),
        Info("M400", "FinishMoves", emptySet(), false),
        Info("M401", "DeployProbe", setOf('H', 'R', 'S'), false),
        Info("M402", "StowProbe", setOf('R'), false),
        Info("M403", "MMU2FilamentType", setOf('E', 'F'), false),
        Info("M404", "FilamentWidthSensorNominalDiameter", setOf('W'), false),
        Info("M405", "FilamentWidthSensorOn", setOf('D'), false),
        Info("M406", "FilamentWidthSensorOff", emptySet(), false),
        Info("M407", "ReadFilamentWidth", emptySet(), false),
        Info("M410", "Quickstop", emptySet(), false),
        Info("M412", "FilamentRunout", setOf('D', 'H', 'L', 'R', 'S'), false),
        Info("M413", "PowerLossRecovery", setOf('S'), false),
        Info("M414", "LCDLanguage", setOf('S'), false),
        Info("M420", "BedLevelingState", setOf('C', 'L', 'S', 'T', 'V', 'Z'), false),
        Info("M421", "SetMeshValue", setOf('C', 'I', 'J', 'N', 'Q', 'X', 'Y', 'Z'), false),
        Info("M422", "SetZMotorXY", setOf('R', 'S', 'W', 'X', 'Y'), false),
        Info("M423", "XTwistCompensation", setOf('A', 'E', 'I', 'R', 'X', 'Z'), false),
        Info("M425", "BacklashCompensation", setOf('F', 'S', 'X', 'Y', 'Z'), false),
        Info("M428", "HomeOffsetsHere", emptySet(), false),
        Info("M430", "PowerMonitor", setOf('I', 'V', 'W'), false),
        Info("M486", "CancelObjects", setOf('C', 'P', 'S', 'T', 'U'), false),
        Info("M493", "FixedTimeMotion", setOf('A', 'C', 'D', 'E', 'F', 'H', 'I', 'Q', 'S', 'X', 'Y', 'Z'), false),
        Info("M494", "FTMotionTrajectorySmoothing", setOf('E', 'O', 'T', 'X', 'Y', 'Z'), false),
        Info("M500", "SaveSettings", emptySet(), false),
        Info("M501", "RestoreSettings", emptySet(), false),
        Info("M502", "FactoryReset", emptySet(), false),
        Info("M503", "ReportSettings", setOf('C', 'S'), false),
        Info("M504", "ValidateEEPROMContents", emptySet(), false),
        Info("M510", "LockMachine", emptySet(), false),
        Info("M511", "UnlockMachine", setOf('P'), false),
        Info("M512", "SetPasscode", setOf('P', 'S'), false),
        Info("M524", "AbortSDPrint", emptySet(), false),
        Info("M540", "EndstopsAbortSD", setOf('S'), false),
        Info("M550", "MachineName", setOf('P'), true),
        Info("M552", "EthernetIPAddressNetworkIF", setOf('P', 'S'), false),
        Info("M553", "EthernetSubnetMask", setOf('P'), false),
        Info("M554", "EthernetGatewayIPAddress", setOf('P'), false),
        Info("M569", "SetTMCSteppingMode", setOf('E', 'I', 'T', 'X', 'Y', 'Z'), false),
        Info("M575", "SerialBaudRate", setOf('B', 'P'), false),
        Info("M592", "NonlinearExtrusionControl", setOf('A', 'B', 'C', 'S'), false),
        Info("M593", "ZVInputShaping", setOf('D', 'F', 'X', 'Y', 'Z'), false),
        Info("M600", "FilamentChange", setOf('B', 'E', 'L', 'R', 'T', 'U', 'X', 'Y', 'Z'), false),
        Info("M603", "ConfigureFilamentChange", setOf('L', 'T', 'U'), false),
        Info("M605", "MultiNozzleMode", setOf('E', 'P', 'R', 'S', 'X'), false),
        Info("M665", "SCARAConfiguration", setOf('A', 'B', 'P', 'S', 'T', 'X', 'Y'), false),
        Info("M665", "DeltaConfiguration", setOf('A', 'B', 'C', 'H', 'L', 'R', 'S', 'X', 'Y', 'Z'), false),
        Info("M666", "DualEndstopOffsets", setOf('X', 'Y', 'Z'), false),
        Info("M666", "SetDeltaEndstopAdjustments", setOf('X', 'Y', 'Z'), false),
        Info("M672", "DuetSmartEffectorSensitivity", emptySet(), false),
        Info("M701", "LoadFilament", setOf('L', 'T', 'Z'), false),
        Info("M702", "UnloadFilament", setOf('T', 'U', 'Z'), false),
        Info("M710", "ControllerFanSettings", setOf('A', 'D', 'I', 'R', 'S'), false),
        Info("M808", "RepeatMarker", setOf('L'), false),
        Info("M810", "GCodeMacrosM810", emptySet(), true),
        Info("M811", "GCodeMacrosM811", emptySet(), true),
        Info("M812", "GCodeMacrosM812", emptySet(), true),
        Info("M813", "GCodeMacrosM813", emptySet(), true),
        Info("M814", "GCodeMacrosM814", emptySet(), true),
        Info("M815", "GCodeMacrosM815", emptySet(), true),
        Info("M816", "GCodeMacrosM816", emptySet(), true),
        Info("M817", "GCodeMacrosM817", emptySet(), true),
        Info("M818", "GCodeMacrosM818", emptySet(), true),
        Info("M819", "GCodeMacrosM819", emptySet(), true),
        Info("M820", "ReportGCodeMacros", emptySet(), false),
        Info("M851", "XYZProbeOffset", setOf('X', 'Y', 'Z'), false),
        Info("M852", "BedSkewCompensation", setOf('I', 'J', 'K', 'S'), false),
        Info("M860", "I2CPositionEncodersM860", setOf('E', 'I', 'O', 'P', 'R', 'S', 'T', 'U', 'X', 'Y', 'Z'), false),
        Info("M861", "I2CPositionEncodersM861", setOf('E', 'I', 'O', 'P', 'R', 'S', 'T', 'U', 'X', 'Y', 'Z'), false),
        Info("M862", "I2CPositionEncodersM862", setOf('E', 'I', 'O', 'P', 'R', 'S', 'T', 'U', 'X', 'Y', 'Z'), false),
        Info("M863", "I2CPositionEncodersM863", setOf('E', 'I', 'O', 'P', 'R', 'S', 'T', 'U', 'X', 'Y', 'Z'), false),
        Info("M864", "I2CPositionEncodersM864", setOf('E', 'I', 'O', 'P', 'R', 'S', 'T', 'U', 'X', 'Y', 'Z'), false),
        Info("M865", "I2CPositionEncodersM865", setOf('E', 'I', 'O', 'P', 'R', 'S', 'T', 'U', 'X', 'Y', 'Z'), false),
        Info("M866", "I2CPositionEncodersM866", setOf('E', 'I', 'O', 'P', 'R', 'S', 'T', 'U', 'X', 'Y', 'Z'), false),
        Info("M867", "I2CPositionEncodersM867", setOf('E', 'I', 'O', 'P', 'R', 'S', 'T', 'U', 'X', 'Y', 'Z'), false),
        Info("M868", "I2CPositionEncodersM868", setOf('E', 'I', 'O', 'P', 'R', 'S', 'T', 'U', 'X', 'Y', 'Z'), false),
        Info("M869", "I2CPositionEncodersM869", setOf('E', 'I', 'O', 'P', 'R', 'S', 'T', 'U', 'X', 'Y', 'Z'), false),
        Info("M871", "ProbeTemperatureConfig", setOf('B', 'E', 'I', 'P', 'R', 'V'), false),
        Info("M876", "HandlePromptResponse", setOf('S'), false),
        Info("M900", "LinearAdvanceFactor", setOf('K', 'L', 'S', 'T'), false),
        Info("M906", "StepperMotorCurrent", setOf('E', 'I', 'T', 'X', 'Y', 'Z'), false),
        Info("M907", "TrimpotStepperMotorCurrent", setOf('B', 'C', 'D', 'E', 'I', 'J', 'K', 'S', 'U', 'V', 'W', 'X', 'Y', 'Z'), false),
        Info("M908", "SetTrimpotPins", setOf('P', 'S'), false),
        Info("M909", "ReportDACStepperCurrent", emptySet(), false),
        Info("M910", "CommitDACToEEPROM", emptySet(), false),
        Info("M911", "TMCOTPreWarnCondition", emptySet(), false),
        Info("M912", "ClearTMCOTPreWarn", setOf('E', 'I', 'X', 'Y', 'Z'), false),
        Info("M913", "SetHybridThresholdSpeed", setOf('A', 'B', 'C', 'E', 'I', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'), false),
        Info("M914", "TMCBumpSensitivity", setOf('A', 'B', 'C', 'I', 'U', 'V', 'W', 'X', 'Y', 'Z'), false),
        Info("M915", "TMCZAxisCalibration", setOf('S', 'Z'), false),
        Info("M916", "L6474ThermalWarningTest", setOf('D', 'E', 'F', 'J', 'K', 'T', 'X', 'Y', 'Z'), false),
        Info("M917", "L6474OvercurrentWarningTest", setOf('A', 'B', 'C', 'E', 'F', 'I', 'J', 'K', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'), false),
        Info("M918", "L6474SpeedWarningTest", setOf('E', 'I', 'J', 'K', 'M', 'T', 'X', 'Y', 'Z'), false),
        Info("M919", "TMCChopperTiming", setOf('A', 'B', 'C', 'I', 'O', 'P', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'), false),
        Info("M920", "TMCHomingCurrent", setOf('A', 'B', 'C', 'I', 'U', 'V', 'W', 'X', 'Y', 'Z'), false),
        Info("M928", "StartSDLogging", emptySet(), true),
        Info("M951", "MagneticParkingExtruder", setOf('C', 'D', 'H', 'I', 'J', 'L', 'R'), false),
        Info("M993", "BackUpFlashSettingsToSD", emptySet(), false),
        Info("M994", "RestoreFlashFromSD", emptySet(), false),
        Info("M995", "TouchScreenCalibration", emptySet(), false),
        Info("M997", "FirmwareUpdate", emptySet(), false),
        Info("M999", "STOPRestart", setOf('S'), false),
        Info("M7219", "MAX7219Control", setOf('C', 'D', 'F', 'I', 'P', 'R', 'U', 'V', 'X', 'Y'), false),
        Info("T0", "SelectOrReportToolT0", setOf('F', 'S'), false),
        Info("T1", "SelectOrReportToolT1", setOf('F', 'S'), false),
        Info("T2", "SelectOrReportToolT2", setOf('F', 'S'), false),
        Info("T3", "SelectOrReportToolT3", setOf('F', 'S'), false),
        Info("T4", "SelectOrReportToolT4", setOf('F', 'S'), false),
        Info("T5", "SelectOrReportToolT5", setOf('F', 'S'), false),
        Info("T6", "SelectOrReportToolT6", setOf('F', 'S'), false),
        Info("T7", "SelectOrReportToolT7", setOf('F', 'S'), false),
    )

    /**
     * Decoders by command head, so [decode] is a map lookup and not 295 comparisons.
     *
     * **A head can be claimed by more than one class** and this keeps the first. Marlin
     * documents `G29`, `G34`, `M665`, `M666` once per variant - six G29 pages, one per bed-leveling
     * system, and two each for the others - and which one a printer means depends on how
     * its firmware was compiled, which no amount of reading the line can tell you. Build
     * with the variant class you mean; [decode] is a best effort for the rest.
     */
    private val byHead: Map<GParameterWord<*>, GRqDecoder<*>> =
        decoders.groupBy { it.head() }.mapValues { (_, claimants) -> claimants.first() }

    /** The codes above, whose [decode] is therefore approximate. */
    val ambiguousCodes: List<String> = listOf("G29", "G34", "M665", "M666")

    /**
     * The command [cmd] says it is, or null if no Marlin command has that head.
     *
     * Matching is on the head as written, so a non-canonical `M0105` does not resolve -
     * the lexeme is part of a number's identity in this model.
     */
    fun decode(cmd: GCommand): GRq<*>? {
        val decoder = byHead[cmd.head] ?: return null
        return decoder.decodeParams(cmd.params)
    }
}

/**
 * Named shortcuts for the commands this project sends most.
 *
 * Each is one line over the classes above and has no privileges they do not - the point is
 * a call site that reads as an intention rather than a code number.
 */
object MarlinG {

    fun m105(index: Int? = null): ReportHotendTemperature {
        return ReportHotendTemperature(index = index)
    }

    fun tempReport(tool: Int? = null): ReportHotendTemperature {
        return m105(tool)
    }

    fun m115(): FirmwareInfo {
        return FirmwareInfo()
    }

    fun firmwareInfo(): FirmwareInfo {
        return m115()
    }

    fun m155(period: Int? = null): TemperatureAutoReport {
        return TemperatureAutoReport(seconds = period)
    }

    fun autoReportTemp(period: Int? = null): TemperatureAutoReport {
        return m155(period)
    }

    /**
     * `M104 T<tool> S<temp>`.
     *
     * The tool goes in `T` and not in `I`: M104 documents both, `I` being a material
     * preset index, and `T` is the one the old Java facade and `GSender.m104` send.
     */
    fun m104(temp: BigDecimal, tool: Int? = null): SetHotendTemperature {
        return SetHotendTemperature(temp = temp, t = tool)
    }

    fun setHotendTemperature(temp: BigDecimal, tool: Int? = null): SetHotendTemperature {
        return m104(temp, tool)
    }

    fun m140(temp: BigDecimal): SetBedTemperature {
        return SetBedTemperature(temp = temp)
    }

    fun setBedTemperature(temp: BigDecimal): SetBedTemperature {
        return m140(temp)
    }
}
