package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M524
 *
 * Abort SD print (sdcard).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(AbortSDPrint().encode())   // M524
 * AbortSDPrint.decode(GTokenizer.parse("M524").toList())   // AbortSDPrint(M524)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @see <a href="https://marlinfw.org/docs/gcode/M524.html">MarlinFirmare M524 doc</a>
 */
class AbortSDPrint : GRq<AbortSDPrint> {

    override fun encode(): GCommand {
        return M(524)
    }

    override fun equals(other: Any?): Boolean {
        return other is AbortSDPrint
    }

    override fun hashCode(): Int {
        return 873954
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<AbortSDPrint> {

        override fun head(): GParameterWord<*> {
            return M(524).head
        }

        override fun decodeParams(tokens: List<GToken>): AbortSDPrint {
            return AbortSDPrint()
        }
    }
}
