package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.G
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * G3 [X<pos>] [Y<pos>] [Z<pos>] [A<pos>] [B<pos>] [C<pos>] [U<pos>] [V<pos>] [W<pos>] I<offset> J<offset> R<radius> [E<pos>] [F<rate>] [P<count>] [S<power>]
 *
 * Arc or Circle Move (motion).
 *
 * Marlin documents `I`, `J`, `R` as required; every property here still defaults to
 * absent, so that every command class is constructible bare.
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(ArcOrCircleMoveG3(pos = BigDecimal("1.5")).encode())   // G3 X1.5
 * ArcOrCircleMoveG3.decode(GTokenizer.parse("G3 X1.5").toList())   // ArcOrCircleMoveG3(G3 X1.5)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property pos `X` - pos
 * @property y `Y` - pos
 * @property z `Z` - pos
 * @property a `A` - pos
 * @property b `B` - pos
 * @property c `C` - pos
 * @property u `U` - pos
 * @property v `V` - pos
 * @property w `W` - pos
 * @property offset `I` - offset (required)
 * @property j `J` - offset (required)
 * @property radius `R` - radius (required)
 * @property e `E` - pos
 * @property rate `F` - rate
 * @property count `P` - count
 * @property power `S` - power
 * @see <a href="https://marlinfw.org/docs/gcode/G3.html">MarlinFirmare G3 doc</a>
 */
data class ArcOrCircleMoveG3(
    val pos: BigDecimal? = null,
    val y: BigDecimal? = null,
    val z: BigDecimal? = null,
    val a: BigDecimal? = null,
    val b: BigDecimal? = null,
    val c: BigDecimal? = null,
    val u: BigDecimal? = null,
    val v: BigDecimal? = null,
    val w: BigDecimal? = null,
    val offset: BigDecimal? = null,
    val j: BigDecimal? = null,
    val radius: BigDecimal? = null,
    val e: BigDecimal? = null,
    val rate: BigDecimal? = null,
    val count: Int? = null,
    val power: BigDecimal? = null,
) : GRq<ArcOrCircleMoveG3> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(16)
        if (pos != null) words.add(word('X', pos.toPlainString()))
        if (y != null) words.add(word('Y', y.toPlainString()))
        if (z != null) words.add(word('Z', z.toPlainString()))
        if (a != null) words.add(word('A', a.toPlainString()))
        if (b != null) words.add(word('B', b.toPlainString()))
        if (c != null) words.add(word('C', c.toPlainString()))
        if (u != null) words.add(word('U', u.toPlainString()))
        if (v != null) words.add(word('V', v.toPlainString()))
        if (w != null) words.add(word('W', w.toPlainString()))
        if (offset != null) words.add(word('I', offset.toPlainString()))
        if (j != null) words.add(word('J', j.toPlainString()))
        if (radius != null) words.add(word('R', radius.toPlainString()))
        if (e != null) words.add(word('E', e.toPlainString()))
        if (rate != null) words.add(word('F', rate.toPlainString()))
        if (count != null) words.add(word('P', count))
        if (power != null) words.add(word('S', power.toPlainString()))
        return G(3, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<ArcOrCircleMoveG3> {

        override fun head(): GParameterWord<*> {
            return G(3).head
        }

        override fun decodeParams(tokens: List<GToken>): ArcOrCircleMoveG3 {
            return ArcOrCircleMoveG3(
                pos = tokens.decimalOf('X'),
                y = tokens.decimalOf('Y'),
                z = tokens.decimalOf('Z'),
                a = tokens.decimalOf('A'),
                b = tokens.decimalOf('B'),
                c = tokens.decimalOf('C'),
                u = tokens.decimalOf('U'),
                v = tokens.decimalOf('V'),
                w = tokens.decimalOf('W'),
                offset = tokens.decimalOf('I'),
                j = tokens.decimalOf('J'),
                radius = tokens.decimalOf('R'),
                e = tokens.decimalOf('E'),
                rate = tokens.decimalOf('F'),
                count = tokens.intOf('P'),
                power = tokens.decimalOf('S'),
            )
        }
    }
}
