package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.boolOf
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M290 [X<pos>] [Y<pos>] [Z<pos>] [S<pos>] [P<value>]
 *
 * Babystep (calibration).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(Babystep(pos = BigDecimal("1.5")).encode())   // M290 X1.5
 * Babystep.decode(GTokenizer.parse("M290 X1.5").toList())   // Babystep(M290 X1.5)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property pos `X` - pos
 * @property y `Y` - pos
 * @property z `Z` - pos
 * @property s `S` - pos
 * @property p `P`
 * @see <a href="https://marlinfw.org/docs/gcode/M290.html">MarlinFirmare M290 doc</a>
 */
data class Babystep(
    val pos: BigDecimal? = null,
    val y: BigDecimal? = null,
    val z: BigDecimal? = null,
    val s: BigDecimal? = null,
    val p: Boolean? = null,
) : GRq<Babystep> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(5)
        if (pos != null) words.add(word('X', pos.toPlainString()))
        if (y != null) words.add(word('Y', y.toPlainString()))
        if (z != null) words.add(word('Z', z.toPlainString()))
        if (s != null) words.add(word('S', s.toPlainString()))
        if (p != null) words.add(word('P', if (p) 1 else 0))
        return M(290, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<Babystep> {

        override fun head(): GParameterWord<*> {
            return M(290).head
        }

        override fun decodeParams(tokens: List<GToken>): Babystep {
            return Babystep(
                pos = tokens.decimalOf('X'),
                y = tokens.decimalOf('Y'),
                z = tokens.decimalOf('Z'),
                s = tokens.decimalOf('S'),
                p = tokens.boolOf('P'),
            )
        }
    }
}
