package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M425 [F<value>] [S<linear>] [X<linear>] [Y<linear>] [Z<linear>]
 *
 * Backlash compensation (calibration).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(BacklashCompensation(value = BigDecimal("1.5")).encode())   // M425 F1.5
 * BacklashCompensation.decode(GTokenizer.parse("M425 F1.5").toList())   // BacklashCompensation(M425 F1.5)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property value `F` - value
 * @property linear `S` - linear
 * @property x `X` - linear
 * @property y `Y` - linear
 * @property z `Z` - linear
 * @see <a href="https://marlinfw.org/docs/gcode/M425.html">MarlinFirmare M425 doc</a>
 */
data class BacklashCompensation(
    val value: BigDecimal? = null,
    val linear: BigDecimal? = null,
    val x: BigDecimal? = null,
    val y: BigDecimal? = null,
    val z: BigDecimal? = null,
) : GRq<BacklashCompensation> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(5)
        if (value != null) words.add(word('F', value.toPlainString()))
        if (linear != null) words.add(word('S', linear.toPlainString()))
        if (x != null) words.add(word('X', x.toPlainString()))
        if (y != null) words.add(word('Y', y.toPlainString()))
        if (z != null) words.add(word('Z', z.toPlainString()))
        return M(425, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<BacklashCompensation> {

        override fun head(): GParameterWord<*> {
            return M(425).head
        }

        override fun decodeParams(tokens: List<GToken>): BacklashCompensation {
            return BacklashCompensation(
                value = tokens.decimalOf('F'),
                linear = tokens.decimalOf('S'),
                x = tokens.decimalOf('X'),
                y = tokens.decimalOf('Y'),
                z = tokens.decimalOf('Z'),
            )
        }
    }
}
