package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M127
 *
 * Baricuda 1 Close (baricuda).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(Baricuda1Close().encode())   // M127
 * Baricuda1Close.decode(GTokenizer.parse("M127").toList())   // Baricuda1Close(M127)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @see <a href="https://marlinfw.org/docs/gcode/M127.html">MarlinFirmare M127 doc</a>
 */
class Baricuda1Close : GRq<Baricuda1Close> {

    override fun encode(): GCommand {
        return M(127)
    }

    override fun equals(other: Any?): Boolean {
        return other is Baricuda1Close
    }

    override fun hashCode(): Int {
        return 537594
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<Baricuda1Close> {

        override fun head(): GParameterWord<*> {
            return M(127).head
        }

        override fun decodeParams(tokens: List<GToken>): Baricuda1Close {
            return Baricuda1Close()
        }
    }
}
