package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M126 [S<pressure>]
 *
 * Baricuda 1 Open (baricuda).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(Baricuda1Open(pressure = 1).encode())   // M126 S1
 * Baricuda1Open.decode(GTokenizer.parse("M126 S1").toList())   // Baricuda1Open(M126 S1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property pressure `S` - pressure
 * @see <a href="https://marlinfw.org/docs/gcode/M126.html">MarlinFirmare M126 doc</a>
 */
data class Baricuda1Open(
    val pressure: Int? = null,
) : GRq<Baricuda1Open> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(1)
        if (pressure != null) words.add(word('S', pressure))
        return M(126, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<Baricuda1Open> {

        override fun head(): GParameterWord<*> {
            return M(126).head
        }

        override fun decodeParams(tokens: List<GToken>): Baricuda1Open {
            return Baricuda1Open(
                pressure = tokens.intOf('S'),
            )
        }
    }
}
