package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.G
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * G29 S<value> [I<index>] [J<index>] [X<count>] [Y<count>] [Z<linear>]
 *
 * Bed Leveling (Manual) (calibration).
 *
 * Marlin documents `S` as required; every property here still defaults to
 * absent, so that every command class is constructible bare.
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(BedLevelingManual(s = 1).encode())   // G29 S1
 * BedLevelingManual.decode(GTokenizer.parse("G29 S1").toList())   // BedLevelingManual(G29 S1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property s `S` (required)
 * @property index `I` - index
 * @property j `J` - index
 * @property count `X` - count
 * @property y `Y` - count
 * @property linear `Z` - linear
 * @see <a href="https://marlinfw.org/docs/gcode/G29.html">MarlinFirmare G29 doc</a>
 */
data class BedLevelingManual(
    val s: Int? = null,
    val index: Int? = null,
    val j: Int? = null,
    val count: Int? = null,
    val y: Int? = null,
    val linear: BigDecimal? = null,
) : GRq<BedLevelingManual> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(6)
        if (s != null) words.add(word('S', s))
        if (index != null) words.add(word('I', index))
        if (j != null) words.add(word('J', j))
        if (count != null) words.add(word('X', count))
        if (y != null) words.add(word('Y', y))
        if (linear != null) words.add(word('Z', linear.toPlainString()))
        return G(29, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<BedLevelingManual> {

        override fun head(): GParameterWord<*> {
            return G(29).head
        }

        override fun decodeParams(tokens: List<GToken>): BedLevelingManual {
            return BedLevelingManual(
                s = tokens.intOf('S'),
                index = tokens.intOf('I'),
                j = tokens.intOf('J'),
                count = tokens.intOf('X'),
                y = tokens.intOf('Y'),
                linear = tokens.decimalOf('Z'),
            )
        }
    }
}
