package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.G
import org.qw3rtrun.p3d.g.code.dsl.flag
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.boolOf
import org.qw3rtrun.p3d.g.marlin.hasWord
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * G29 [A<value>] [C<value>] [O] [Q<value>] [E<value>] [D<value>] [J<value>] [V<value>]
 *
 * Bed Leveling (3-Point) (calibration).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(BedLeveling3Point(a = true).encode())   // G29 A1
 * BedLeveling3Point.decode(GTokenizer.parse("G29 A1").toList())   // BedLeveling3Point(G29 A1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property a `A`
 * @property c `C`
 * @property o `O`
 * @property q `Q`
 * @property e `E`
 * @property d `D`
 * @property j `J`
 * @property v `V`
 * @see <a href="https://marlinfw.org/docs/gcode/G29.html">MarlinFirmare G29 doc</a>
 */
data class BedLeveling3Point(
    val a: Boolean? = null,
    val c: Boolean? = null,
    val o: Boolean = false,
    val q: Boolean? = null,
    val e: Boolean? = null,
    val d: Boolean? = null,
    val j: Boolean? = null,
    val v: Int? = null,
) : GRq<BedLeveling3Point> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(8)
        if (a != null) words.add(word('A', if (a) 1 else 0))
        if (c != null) words.add(word('C', if (c) 1 else 0))
        if (o) words.add(flag('O'))
        if (q != null) words.add(word('Q', if (q) 1 else 0))
        if (e != null) words.add(word('E', if (e) 1 else 0))
        if (d != null) words.add(word('D', if (d) 1 else 0))
        if (j != null) words.add(word('J', if (j) 1 else 0))
        if (v != null) words.add(word('V', v))
        return G(29, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<BedLeveling3Point> {

        override fun head(): GParameterWord<*> {
            return G(29).head
        }

        override fun decodeParams(tokens: List<GToken>): BedLeveling3Point {
            return BedLeveling3Point(
                a = tokens.boolOf('A'),
                c = tokens.boolOf('C'),
                o = tokens.hasWord('O'),
                q = tokens.boolOf('Q'),
                e = tokens.boolOf('E'),
                d = tokens.boolOf('D'),
                j = tokens.boolOf('J'),
                v = tokens.intOf('V'),
            )
        }
    }
}
