package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.G
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * G5 X<pos> Y<pos> [E<pos>] [F<rate>] I<pos> J<pos> P<pos> Q<pos> [S<power>]
 *
 * Bézier Cubic Spline Move (motion).
 *
 * Marlin documents `X`, `Y`, `I`, `J`, `P`, `Q` as required; every property here still defaults to
 * absent, so that every command class is constructible bare.
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(BezierCubicSplineMove(pos = BigDecimal("1.5")).encode())   // G5 X1.5
 * BezierCubicSplineMove.decode(GTokenizer.parse("G5 X1.5").toList())   // BezierCubicSplineMove(G5 X1.5)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property pos `X` - pos (required)
 * @property y `Y` - pos (required)
 * @property e `E` - pos
 * @property rate `F` - rate
 * @property i `I` - pos (required)
 * @property j `J` - pos (required)
 * @property p `P` - pos (required)
 * @property q `Q` - pos (required)
 * @property power `S` - power
 * @see <a href="https://marlinfw.org/docs/gcode/G5.html">MarlinFirmare G5 doc</a>
 */
data class BezierCubicSplineMove(
    val pos: BigDecimal? = null,
    val y: BigDecimal? = null,
    val e: BigDecimal? = null,
    val rate: BigDecimal? = null,
    val i: BigDecimal? = null,
    val j: BigDecimal? = null,
    val p: BigDecimal? = null,
    val q: BigDecimal? = null,
    val power: BigDecimal? = null,
) : GRq<BezierCubicSplineMove> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(9)
        if (pos != null) words.add(word('X', pos.toPlainString()))
        if (y != null) words.add(word('Y', y.toPlainString()))
        if (e != null) words.add(word('E', e.toPlainString()))
        if (rate != null) words.add(word('F', rate.toPlainString()))
        if (i != null) words.add(word('I', i.toPlainString()))
        if (j != null) words.add(word('J', j.toPlainString()))
        if (p != null) words.add(word('P', p.toPlainString()))
        if (q != null) words.add(word('Q', q.toPlainString()))
        if (power != null) words.add(word('S', power.toPlainString()))
        return G(5, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<BezierCubicSplineMove> {

        override fun head(): GParameterWord<*> {
            return G(5).head
        }

        override fun decodeParams(tokens: List<GToken>): BezierCubicSplineMove {
            return BezierCubicSplineMove(
                pos = tokens.decimalOf('X'),
                y = tokens.decimalOf('Y'),
                e = tokens.decimalOf('E'),
                rate = tokens.decimalOf('F'),
                i = tokens.decimalOf('I'),
                j = tokens.decimalOf('J'),
                p = tokens.decimalOf('P'),
                q = tokens.decimalOf('Q'),
                power = tokens.decimalOf('S'),
            )
        }
    }
}
