package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.flag
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.hasWord
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M486 [C] [P<index>] [S<index>] [T<count>] [U<index>]
 *
 * Cancel Objects (sdcard).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(CancelObjects(c = true).encode())   // M486 C
 * CancelObjects.decode(GTokenizer.parse("M486 C").toList())   // CancelObjects(M486 C)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property c `C`
 * @property index `P` - index
 * @property s `S` - index
 * @property count `T` - count
 * @property u `U` - index
 * @see <a href="https://marlinfw.org/docs/gcode/M486.html">MarlinFirmare M486 doc</a>
 */
data class CancelObjects(
    val c: Boolean = false,
    val index: Int? = null,
    val s: Int? = null,
    val count: Int? = null,
    val u: Int? = null,
) : GRq<CancelObjects> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(5)
        if (c) words.add(flag('C'))
        if (index != null) words.add(word('P', index))
        if (s != null) words.add(word('S', s))
        if (count != null) words.add(word('T', count))
        if (u != null) words.add(word('U', u))
        return M(486, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<CancelObjects> {

        override fun head(): GParameterWord<*> {
            return M(486).head
        }

        override fun decodeParams(tokens: List<GToken>): CancelObjects {
            return CancelObjects(
                c = tokens.hasWord('C'),
                index = tokens.intOf('P'),
                s = tokens.intOf('S'),
                count = tokens.intOf('T'),
                u = tokens.intOf('U'),
            )
        }
    }
}
