package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.boolOf
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M355 [P<value>] [S<value>]
 *
 * Case Light Control (control).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(CaseLightControl(p = 1).encode())   // M355 P1
 * CaseLightControl.decode(GTokenizer.parse("M355 P1").toList())   // CaseLightControl(M355 P1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property p `P`
 * @property s `S`
 * @see <a href="https://marlinfw.org/docs/gcode/M355.html">MarlinFirmare M355 doc</a>
 */
data class CaseLightControl(
    val p: Int? = null,
    val s: Boolean? = null,
) : GRq<CaseLightControl> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(2)
        if (p != null) words.add(word('P', p))
        if (s != null) words.add(word('S', if (s) 1 else 0))
        return M(355, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<CaseLightControl> {

        override fun head(): GParameterWord<*> {
            return M(355).head
        }

        override fun decodeParams(tokens: List<GToken>): CaseLightControl {
            return CaseLightControl(
                p = tokens.intOf('P'),
                s = tokens.boolOf('S'),
            )
        }
    }
}
