package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.G
import org.qw3rtrun.p3d.g.code.dsl.flag
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.hasWord
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * G12 [P<value>] [R<radius>] [S<count>] [T<count>] [X] [Y] [Z]
 *
 * Clean the Nozzle (nozzle).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(CleanTheNozzle(p = 1).encode())   // G12 P1
 * CleanTheNozzle.decode(GTokenizer.parse("G12 P1").toList())   // CleanTheNozzle(G12 P1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property p `P`
 * @property radius `R` - radius
 * @property count `S` - count
 * @property t `T` - count
 * @property x `X`
 * @property y `Y`
 * @property z `Z`
 * @see <a href="https://marlinfw.org/docs/gcode/G12.html">MarlinFirmare G12 doc</a>
 */
data class CleanTheNozzle(
    val p: Int? = null,
    val radius: BigDecimal? = null,
    val count: Int? = null,
    val t: Int? = null,
    val x: Boolean = false,
    val y: Boolean = false,
    val z: Boolean = false,
) : GRq<CleanTheNozzle> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(7)
        if (p != null) words.add(word('P', p))
        if (radius != null) words.add(word('R', radius.toPlainString()))
        if (count != null) words.add(word('S', count))
        if (t != null) words.add(word('T', t))
        if (x) words.add(flag('X'))
        if (y) words.add(flag('Y'))
        if (z) words.add(flag('Z'))
        return G(12, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<CleanTheNozzle> {

        override fun head(): GParameterWord<*> {
            return G(12).head
        }

        override fun decodeParams(tokens: List<GToken>): CleanTheNozzle {
            return CleanTheNozzle(
                p = tokens.intOf('P'),
                radius = tokens.decimalOf('R'),
                count = tokens.intOf('S'),
                t = tokens.intOf('T'),
                x = tokens.hasWord('X'),
                y = tokens.hasWord('Y'),
                z = tokens.hasWord('Z'),
            )
        }
    }
}
