package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.flag
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.hasWord
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M912 [I<value>] [X] [Y] [Z] [E<value>]
 *
 * Clear TMC OT Pre-Warn (control).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(ClearTMCOTPreWarn(i = 1).encode())   // M912 I1
 * ClearTMCOTPreWarn.decode(GTokenizer.parse("M912 I1").toList())   // ClearTMCOTPreWarn(M912 I1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property i `I`
 * @property x `X`
 * @property y `Y`
 * @property z `Z`
 * @property e `E`
 * @see <a href="https://marlinfw.org/docs/gcode/M912.html">MarlinFirmare M912 doc</a>
 */
data class ClearTMCOTPreWarn(
    val i: Int? = null,
    val x: Boolean = false,
    val y: Boolean = false,
    val z: Boolean = false,
    val e: BigDecimal? = null,
) : GRq<ClearTMCOTPreWarn> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(5)
        if (i != null) words.add(word('I', i))
        if (x) words.add(flag('X'))
        if (y) words.add(flag('Y'))
        if (z) words.add(flag('Z'))
        if (e != null) words.add(word('E', e.toPlainString()))
        return M(912, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<ClearTMCOTPreWarn> {

        override fun head(): GParameterWord<*> {
            return M(912).head
        }

        override fun decodeParams(tokens: List<GToken>): ClearTMCOTPreWarn {
            return ClearTMCOTPreWarn(
                i = tokens.intOf('I'),
                x = tokens.hasWord('X'),
                y = tokens.hasWord('Y'),
                z = tokens.hasWord('Z'),
                e = tokens.decimalOf('E'),
            )
        }
    }
}
