package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.dsl.G
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * G19
 *
 * CNC Workspace Planes (geometry).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(CNCWorkspacePlanesG19().encode())   // G19
 * CNCWorkspacePlanesG19.decode(GTokenizer.parse("G19").toList())   // CNCWorkspacePlanesG19(G19)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @see <a href="https://marlinfw.org/docs/gcode/G19.html">MarlinFirmare G19 doc</a>
 */
class CNCWorkspacePlanesG19 : GRq<CNCWorkspacePlanesG19> {

    override fun encode(): GCommand {
        return G(19)
    }

    override fun equals(other: Any?): Boolean {
        return other is CNCWorkspacePlanesG19
    }

    override fun hashCode(): Int {
        return 254704
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<CNCWorkspacePlanesG19> {

        override fun head(): GParameterWord<*> {
            return G(19).head
        }

        override fun decodeParams(tokens: List<GToken>): CNCWorkspacePlanesG19 {
            return CNCWorkspacePlanesG19()
        }
    }
}
