package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M381 [S<index>]
 *
 * Deactivate Solenoids.
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(DeactivateSolenoids(index = 1).encode())   // M381 S1
 * DeactivateSolenoids.decode(GTokenizer.parse("M381 S1").toList())   // DeactivateSolenoids(M381 S1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property index `S` - index
 * @see <a href="https://marlinfw.org/docs/gcode/M381.html">MarlinFirmare M381 doc</a>
 */
data class DeactivateSolenoids(
    val index: Int? = null,
) : GRq<DeactivateSolenoids> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(1)
        if (index != null) words.add(word('S', index))
        return M(381, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<DeactivateSolenoids> {

        override fun head(): GParameterWord<*> {
            return M(381).head
        }

        override fun decodeParams(tokens: List<GToken>): DeactivateSolenoids {
            return DeactivateSolenoids(
                index = tokens.intOf('S'),
            )
        }
    }
}
