package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M111 [S<flags>]
 *
 * Debug Level (hosts).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(DebugLevel(flags = 1).encode())   // M111 S1
 * DebugLevel.decode(GTokenizer.parse("M111 S1").toList())   // DebugLevel(M111 S1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property flags `S` - flags
 * @see <a href="https://marlinfw.org/docs/gcode/M111.html">MarlinFirmare M111 doc</a>
 */
data class DebugLevel(
    val flags: Int? = null,
) : GRq<DebugLevel> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(1)
        if (flags != null) words.add(word('S', flags))
        return M(111, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<DebugLevel> {

        override fun head(): GParameterWord<*> {
            return M(111).head
        }

        override fun decodeParams(tokens: List<GToken>): DebugLevel {
            return DebugLevel(
                flags = tokens.intOf('S'),
            )
        }
    }
}
