package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.G
import org.qw3rtrun.p3d.g.code.dsl.flag
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.boolOf
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.hasWord
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * G33 [C<value>] [E<value>] [F<value>] [P<value>] [T<value>] [V<value>] [O<value>] [R<value>] [S] [X] [Y] [Z]
 *
 * Delta Auto Calibration ([ calibration, delta ]).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(DeltaAutoCalibration(c = BigDecimal("1.5")).encode())   // G33 C1.5
 * DeltaAutoCalibration.decode(GTokenizer.parse("G33 C1.5").toList())   // DeltaAutoCalibration(G33 C1.5)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property c `C`
 * @property e `E`
 * @property f `F`
 * @property p `P`
 * @property t `T`
 * @property v `V`
 * @property o `O`
 * @property r `R`
 * @property s `S`
 * @property x `X`
 * @property y `Y`
 * @property z `Z`
 * @see <a href="https://marlinfw.org/docs/gcode/G33.html">MarlinFirmare G33 doc</a>
 */
data class DeltaAutoCalibration(
    val c: BigDecimal? = null,
    val e: Boolean? = null,
    val f: Int? = null,
    val p: Int? = null,
    val t: Boolean? = null,
    val v: Int? = null,
    val o: Boolean? = null,
    val r: BigDecimal? = null,
    val s: Boolean = false,
    val x: Boolean = false,
    val y: Boolean = false,
    val z: Boolean = false,
) : GRq<DeltaAutoCalibration> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(12)
        if (c != null) words.add(word('C', c.toPlainString()))
        if (e != null) words.add(word('E', if (e) 1 else 0))
        if (f != null) words.add(word('F', f))
        if (p != null) words.add(word('P', p))
        if (t != null) words.add(word('T', if (t) 1 else 0))
        if (v != null) words.add(word('V', v))
        if (o != null) words.add(word('O', if (o) 1 else 0))
        if (r != null) words.add(word('R', r.toPlainString()))
        if (s) words.add(flag('S'))
        if (x) words.add(flag('X'))
        if (y) words.add(flag('Y'))
        if (z) words.add(flag('Z'))
        return G(33, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<DeltaAutoCalibration> {

        override fun head(): GParameterWord<*> {
            return G(33).head
        }

        override fun decodeParams(tokens: List<GToken>): DeltaAutoCalibration {
            return DeltaAutoCalibration(
                c = tokens.decimalOf('C'),
                e = tokens.boolOf('E'),
                f = tokens.intOf('F'),
                p = tokens.intOf('P'),
                t = tokens.boolOf('T'),
                v = tokens.intOf('V'),
                o = tokens.boolOf('O'),
                r = tokens.decimalOf('R'),
                s = tokens.hasWord('S'),
                x = tokens.hasWord('X'),
                y = tokens.hasWord('Y'),
                z = tokens.hasWord('Z'),
            )
        }
    }
}
