package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.flag
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.boolOf
import org.qw3rtrun.p3d.g.marlin.hasWord
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M401 [H] [S<value>] [R<value>]
 *
 * Deploy Probe (calibration).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(DeployProbe(h = true).encode())   // M401 H
 * DeployProbe.decode(GTokenizer.parse("M401 H").toList())   // DeployProbe(M401 H)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property h `H`
 * @property s `S`
 * @property r `R`
 * @see <a href="https://marlinfw.org/docs/gcode/M401.html">MarlinFirmare M401 doc</a>
 */
data class DeployProbe(
    val h: Boolean = false,
    val s: Boolean? = null,
    val r: Boolean? = null,
) : GRq<DeployProbe> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(3)
        if (h) words.add(flag('H'))
        if (s != null) words.add(word('S', if (s) 1 else 0))
        if (r != null) words.add(word('R', if (r) 1 else 0))
        return M(401, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<DeployProbe> {

        override fun head(): GParameterWord<*> {
            return M(401).head
        }

        override fun decodeParams(tokens: List<GToken>): DeployProbe {
            return DeployProbe(
                h = tokens.hasWord('H'),
                s = tokens.boolOf('S'),
                r = tokens.boolOf('R'),
            )
        }
    }
}
