package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.G
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * G6 [I<index>] [R<rate>] [S<rate>] [X<direction>] [Y<direction>] [Z<direction>] [E<direction>]
 *
 * Direct Stepper Move (motion).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(DirectStepperMove(index = 1).encode())   // G6 I1
 * DirectStepperMove.decode(GTokenizer.parse("G6 I1").toList())   // DirectStepperMove(G6 I1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property index `I` - index
 * @property rate `R` - rate
 * @property s `S` - rate
 * @property direction `X` - direction
 * @property y `Y` - direction
 * @property z `Z` - direction
 * @property e `E` - direction
 * @see <a href="https://marlinfw.org/docs/gcode/G6.html">MarlinFirmare G6 doc</a>
 */
data class DirectStepperMove(
    val index: Int? = null,
    val rate: BigDecimal? = null,
    val s: BigDecimal? = null,
    val direction: Int? = null,
    val y: Int? = null,
    val z: Int? = null,
    val e: Int? = null,
) : GRq<DirectStepperMove> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(7)
        if (index != null) words.add(word('I', index))
        if (rate != null) words.add(word('R', rate.toPlainString()))
        if (s != null) words.add(word('S', s.toPlainString()))
        if (direction != null) words.add(word('X', direction))
        if (y != null) words.add(word('Y', y))
        if (z != null) words.add(word('Z', z))
        if (e != null) words.add(word('E', e))
        return G(6, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<DirectStepperMove> {

        override fun head(): GParameterWord<*> {
            return G(6).head
        }

        override fun decodeParams(tokens: List<GToken>): DirectStepperMove {
            return DirectStepperMove(
                index = tokens.intOf('I'),
                rate = tokens.decimalOf('R'),
                s = tokens.decimalOf('S'),
                direction = tokens.intOf('X'),
                y = tokens.intOf('Y'),
                z = tokens.intOf('Z'),
                e = tokens.intOf('E'),
            )
        }
    }
}
