package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.dsl.G
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * G31
 *
 * Dock Sled (calibration).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(DockSled().encode())   // G31
 * DockSled.decode(GTokenizer.parse("G31").toList())   // DockSled(G31)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @see <a href="https://marlinfw.org/docs/gcode/G31.html">MarlinFirmare G31 doc</a>
 */
class DockSled : GRq<DockSled> {

    override fun encode(): GCommand {
        return G(31)
    }

    override fun equals(other: Any?): Boolean {
        return other is DockSled
    }

    override fun hashCode(): Int {
        return 217521
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<DockSled> {

        override fun head(): GParameterWord<*> {
            return G(31).head
        }

        override fun decodeParams(tokens: List<GToken>): DockSled {
            return DockSled()
        }
    }
}
