package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M666 [X<adj>] [Y<adj>] [Z<adj>]
 *
 * Dual endstop offsets (calibration).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(DualEndstopOffsets(adj = BigDecimal("1.5")).encode())   // M666 X1.5
 * DualEndstopOffsets.decode(GTokenizer.parse("M666 X1.5").toList())   // DualEndstopOffsets(M666 X1.5)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property adj `X` - adj
 * @property y `Y` - adj
 * @property z `Z` - adj
 * @see <a href="https://marlinfw.org/docs/gcode/M666.html">MarlinFirmare M666 doc</a>
 */
data class DualEndstopOffsets(
    val adj: BigDecimal? = null,
    val y: BigDecimal? = null,
    val z: BigDecimal? = null,
) : GRq<DualEndstopOffsets> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(3)
        if (adj != null) words.add(word('X', adj.toPlainString()))
        if (y != null) words.add(word('Y', y.toPlainString()))
        if (z != null) words.add(word('Z', z.toPlainString()))
        return M(666, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<DualEndstopOffsets> {

        override fun head(): GParameterWord<*> {
            return M(666).head
        }

        override fun decodeParams(tokens: List<GToken>): DualEndstopOffsets {
            return DualEndstopOffsets(
                adj = tokens.decimalOf('X'),
                y = tokens.decimalOf('Y'),
                z = tokens.decimalOf('Z'),
            )
        }
    }
}
