package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M281 P<index> [L<degrees>] [U<degrees>]
 *
 * Edit Servo Angles (servos).
 *
 * Marlin documents `P` as required; every property here still defaults to
 * absent, so that every command class is constructible bare.
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(EditServoAngles(index = 1).encode())   // M281 P1
 * EditServoAngles.decode(GTokenizer.parse("M281 P1").toList())   // EditServoAngles(M281 P1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property index `P` - index (required)
 * @property degrees `L` - degrees
 * @property u `U` - degrees
 * @see <a href="https://marlinfw.org/docs/gcode/M281.html">MarlinFirmare M281 doc</a>
 */
data class EditServoAngles(
    val index: Int? = null,
    val degrees: Int? = null,
    val u: Int? = null,
) : GRq<EditServoAngles> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(3)
        if (index != null) words.add(word('P', index))
        if (degrees != null) words.add(word('L', degrees))
        if (u != null) words.add(word('U', u))
        return M(281, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<EditServoAngles> {

        override fun head(): GParameterWord<*> {
            return M(281).head
        }

        override fun decodeParams(tokens: List<GToken>): EditServoAngles {
            return EditServoAngles(
                index = tokens.intOf('P'),
                degrees = tokens.intOf('L'),
                u = tokens.intOf('U'),
            )
        }
    }
}
