package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.flag
import org.qw3rtrun.p3d.g.marlin.hasWord
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M17 [X] [Y] [Z] [E] [A] [B] [C] [U] [V] [W]
 *
 * Enable Steppers (control).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(EnableSteppers(x = true).encode())   // M17 X
 * EnableSteppers.decode(GTokenizer.parse("M17 X").toList())   // EnableSteppers(M17 X)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property x `X`
 * @property y `Y`
 * @property z `Z`
 * @property e `E`
 * @property a `A`
 * @property b `B`
 * @property c `C`
 * @property u `U`
 * @property v `V`
 * @property w `W`
 * @see <a href="https://marlinfw.org/docs/gcode/M17.html">MarlinFirmare M17 doc</a>
 */
data class EnableSteppers(
    val x: Boolean = false,
    val y: Boolean = false,
    val z: Boolean = false,
    val e: Boolean = false,
    val a: Boolean = false,
    val b: Boolean = false,
    val c: Boolean = false,
    val u: Boolean = false,
    val v: Boolean = false,
    val w: Boolean = false,
) : GRq<EnableSteppers> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(10)
        if (x) words.add(flag('X'))
        if (y) words.add(flag('Y'))
        if (z) words.add(flag('Z'))
        if (e) words.add(flag('E'))
        if (a) words.add(flag('A'))
        if (b) words.add(flag('B'))
        if (c) words.add(flag('C'))
        if (u) words.add(flag('U'))
        if (v) words.add(flag('V'))
        if (w) words.add(flag('W'))
        return M(17, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<EnableSteppers> {

        override fun head(): GParameterWord<*> {
            return M(17).head
        }

        override fun decodeParams(tokens: List<GToken>): EnableSteppers {
            return EnableSteppers(
                x = tokens.hasWord('X'),
                y = tokens.hasWord('Y'),
                z = tokens.hasWord('Z'),
                e = tokens.hasWord('E'),
                a = tokens.hasWord('A'),
                b = tokens.hasWord('B'),
                c = tokens.hasWord('C'),
                u = tokens.hasWord('U'),
                v = tokens.hasWord('V'),
                w = tokens.hasWord('W'),
            )
        }
    }
}
