package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.boolOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M540 S<flag>
 *
 * Endstops Abort SD (sdcard).
 *
 * Marlin documents `S` as required; every property here still defaults to
 * absent, so that every command class is constructible bare.
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(EndstopsAbortSD(flag = true).encode())   // M540 S1
 * EndstopsAbortSD.decode(GTokenizer.parse("M540 S1").toList())   // EndstopsAbortSD(M540 S1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property flag `S` - flag (required)
 * @see <a href="https://marlinfw.org/docs/gcode/M540.html">MarlinFirmare M540 doc</a>
 */
data class EndstopsAbortSD(
    val flag: Boolean? = null,
) : GRq<EndstopsAbortSD> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(1)
        if (flag != null) words.add(word('S', if (flag) 1 else 0))
        return M(540, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<EndstopsAbortSD> {

        override fun head(): GParameterWord<*> {
            return M(540).head
        }

        override fun decodeParams(tokens: List<GToken>): EndstopsAbortSD {
            return EndstopsAbortSD(
                flag = tokens.boolOf('S'),
            )
        }
    }
}
