package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.text
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.stringOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M554 [P<gateway>]
 *
 * Ethernet Gateway IP Address (ethernet).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(EthernetGatewayIPAddress(gateway = "x").encode())   // M554 P"x"
 * EthernetGatewayIPAddress.decode(GTokenizer.parse("M554 P\"x\"").toList())   // EthernetGatewayIPAddress(M554 P"x")
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property gateway `P` - gateway
 * @see <a href="https://marlinfw.org/docs/gcode/M554.html">MarlinFirmare M554 doc</a>
 */
data class EthernetGatewayIPAddress(
    val gateway: String? = null,
) : GRq<EthernetGatewayIPAddress> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(1)
        if (gateway != null) words.add(word('P', text(gateway)))
        return M(554, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<EthernetGatewayIPAddress> {

        override fun head(): GParameterWord<*> {
            return M(554).head
        }

        override fun decodeParams(tokens: List<GToken>): EthernetGatewayIPAddress {
            return EthernetGatewayIPAddress(
                gateway = tokens.stringOf('P'),
            )
        }
    }
}
