package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.text
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.stringOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M553 [P<subnet-mask>]
 *
 * Ethernet Subnet Mask (ethernet).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(EthernetSubnetMask(subnetMask = "x").encode())   // M553 P"x"
 * EthernetSubnetMask.decode(GTokenizer.parse("M553 P\"x\"").toList())   // EthernetSubnetMask(M553 P"x")
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property subnetMask `P` - subnet-mask
 * @see <a href="https://marlinfw.org/docs/gcode/M553.html">MarlinFirmare M553 doc</a>
 */
data class EthernetSubnetMask(
    val subnetMask: String? = null,
) : GRq<EthernetSubnetMask> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(1)
        if (subnetMask != null) words.add(word('P', text(subnetMask)))
        return M(553, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<EthernetSubnetMask> {

        override fun head(): GParameterWord<*> {
            return M(553).head
        }

        override fun decodeParams(tokens: List<GToken>): EthernetSubnetMask {
            return EthernetSubnetMask(
                subnetMask = tokens.stringOf('P'),
            )
        }
    }
}
