package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.bareString
import org.qw3rtrun.p3d.g.marlin.stringArg
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M16 [<message>]
 *
 * Expected Printer Check (safety).
 *
 * **`message` is a bare rest-of-line string** (spec 3.4a).
 * It carries no letter, it is written last because everything to the end of the
 * line belongs to it, and it cannot contain `;` - every parser reads that as the
 * start of a comment.
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(ExpectedPrinterCheck(message = "a tail").encode())   // M16 a tail
 * ExpectedPrinterCheck.decode(GTokenizer.parse("M16 a tail").toList())   // ExpectedPrinterCheck(M16 a tail)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property message the rest of the line
 * @see <a href="https://marlinfw.org/docs/gcode/M16.html">MarlinFirmare M16 doc</a>
 */
data class ExpectedPrinterCheck(
    val message: String? = null,
) : GRq<ExpectedPrinterCheck> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(1)
        if (message != null) words.add(bareString(message))
        return M(16, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<ExpectedPrinterCheck> {

        override fun head(): GParameterWord<*> {
            return M(16).head
        }

        override fun decodeParams(tokens: List<GToken>): ExpectedPrinterCheck {
            return ExpectedPrinterCheck(
                message = tokens.stringArg(),
            )
        }
    }
}
