package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.boolOf
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M412 [D<linear>] [H<value>] [L<linear>] [S<value>] [R<value>]
 *
 * Filament Runout (control).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(FilamentRunout(linear = BigDecimal("1.5")).encode())   // M412 D1.5
 * FilamentRunout.decode(GTokenizer.parse("M412 D1.5").toList())   // FilamentRunout(M412 D1.5)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property linear `D` - linear
 * @property h `H`
 * @property l `L` - linear
 * @property s `S`
 * @property r `R`
 * @see <a href="https://marlinfw.org/docs/gcode/M412.html">MarlinFirmare M412 doc</a>
 */
data class FilamentRunout(
    val linear: BigDecimal? = null,
    val h: Boolean? = null,
    val l: BigDecimal? = null,
    val s: Boolean? = null,
    val r: Boolean? = null,
) : GRq<FilamentRunout> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(5)
        if (linear != null) words.add(word('D', linear.toPlainString()))
        if (h != null) words.add(word('H', if (h) 1 else 0))
        if (l != null) words.add(word('L', l.toPlainString()))
        if (s != null) words.add(word('S', if (s) 1 else 0))
        if (r != null) words.add(word('R', if (r) 1 else 0))
        return M(412, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<FilamentRunout> {

        override fun head(): GParameterWord<*> {
            return M(412).head
        }

        override fun decodeParams(tokens: List<GToken>): FilamentRunout {
            return FilamentRunout(
                linear = tokens.decimalOf('D'),
                h = tokens.boolOf('H'),
                l = tokens.decimalOf('L'),
                s = tokens.boolOf('S'),
                r = tokens.boolOf('R'),
            )
        }
    }
}
