package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M406
 *
 * Filament Width Sensor Off (control).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(FilamentWidthSensorOff().encode())   // M406
 * FilamentWidthSensorOff.decode(GTokenizer.parse("M406").toList())   // FilamentWidthSensorOff(M406)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @see <a href="https://marlinfw.org/docs/gcode/M406.html">MarlinFirmare M406 doc</a>
 */
class FilamentWidthSensorOff : GRq<FilamentWidthSensorOff> {

    override fun encode(): GCommand {
        return M(406)
    }

    override fun equals(other: Any?): Boolean {
        return other is FilamentWidthSensorOff
    }

    override fun hashCode(): Int {
        return 574854
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<FilamentWidthSensorOff> {

        override fun head(): GParameterWord<*> {
            return M(406).head
        }

        override fun decodeParams(tokens: List<GToken>): FilamentWidthSensorOff {
            return FilamentWidthSensorOff()
        }
    }
}
