package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M600 [T<index>] [E<pos>] [U<pos>] [L<pos>] [X<pos>] [Y<pos>] [Z<pos>] [B<beeps>] [R<temp>]
 *
 * Filament Change (filament).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(FilamentChange(index = 1).encode())   // M600 T1
 * FilamentChange.decode(GTokenizer.parse("M600 T1").toList())   // FilamentChange(M600 T1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property index `T` - index
 * @property pos `E` - pos
 * @property u `U` - pos
 * @property l `L` - pos
 * @property x `X` - pos
 * @property y `Y` - pos
 * @property z `Z` - pos
 * @property beeps `B` - beeps
 * @property temp `R` - temp
 * @see <a href="https://marlinfw.org/docs/gcode/M600.html">MarlinFirmare M600 doc</a>
 */
data class FilamentChange(
    val index: Int? = null,
    val pos: BigDecimal? = null,
    val u: BigDecimal? = null,
    val l: BigDecimal? = null,
    val x: BigDecimal? = null,
    val y: BigDecimal? = null,
    val z: BigDecimal? = null,
    val beeps: Int? = null,
    val temp: Int? = null,
) : GRq<FilamentChange> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(9)
        if (index != null) words.add(word('T', index))
        if (pos != null) words.add(word('E', pos.toPlainString()))
        if (u != null) words.add(word('U', u.toPlainString()))
        if (l != null) words.add(word('L', l.toPlainString()))
        if (x != null) words.add(word('X', x.toPlainString()))
        if (y != null) words.add(word('Y', y.toPlainString()))
        if (z != null) words.add(word('Z', z.toPlainString()))
        if (beeps != null) words.add(word('B', beeps))
        if (temp != null) words.add(word('R', temp))
        return M(600, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<FilamentChange> {

        override fun head(): GParameterWord<*> {
            return M(600).head
        }

        override fun decodeParams(tokens: List<GToken>): FilamentChange {
            return FilamentChange(
                index = tokens.intOf('T'),
                pos = tokens.decimalOf('E'),
                u = tokens.decimalOf('U'),
                l = tokens.decimalOf('L'),
                x = tokens.decimalOf('X'),
                y = tokens.decimalOf('Y'),
                z = tokens.decimalOf('Z'),
                beeps = tokens.intOf('B'),
                temp = tokens.intOf('R'),
            )
        }
    }
}
