package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.flag
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.hasWord
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M217 [Q] [S<linear>] [B<linear>] [E<linear>] [P<feedrate>] [R<feedrate>] [U<linear>] [F<linear>] [G<linear>] [A<linear>] [L<linear>] [W<linear>] [X<linear>] [Y<linear>] [V<linear>] [Z<feedrate>] [I<linear>] [J<linear>] [K<linear>] [C<linear>] [H<linear>] [O<linear>]
 *
 * Filament swap parameters (calibration).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(FilamentSwapParameters(q = true).encode())   // M217 Q
 * FilamentSwapParameters.decode(GTokenizer.parse("M217 Q").toList())   // FilamentSwapParameters(M217 Q)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property q `Q`
 * @property linear `S` - linear
 * @property b `B` - linear
 * @property e `E` - linear
 * @property feedrate `P` - feedrate
 * @property r `R` - feedrate
 * @property u `U` - linear
 * @property f `F` - linear
 * @property g `G` - linear
 * @property a `A` - linear
 * @property l `L` - linear
 * @property w `W` - linear
 * @property x `X` - linear
 * @property y `Y` - linear
 * @property v `V` - linear
 * @property z `Z` - feedrate
 * @property i `I` - linear
 * @property j `J` - linear
 * @property k `K` - linear
 * @property c `C` - linear
 * @property h `H` - linear
 * @property o `O` - linear
 * @see <a href="https://marlinfw.org/docs/gcode/M217.html">MarlinFirmare M217 doc</a>
 */
data class FilamentSwapParameters(
    val q: Boolean = false,
    val linear: BigDecimal? = null,
    val b: BigDecimal? = null,
    val e: BigDecimal? = null,
    val feedrate: Int? = null,
    val r: Int? = null,
    val u: Int? = null,
    val f: Int? = null,
    val g: Int? = null,
    val a: Int? = null,
    val l: Int? = null,
    val w: Int? = null,
    val x: BigDecimal? = null,
    val y: BigDecimal? = null,
    val v: Int? = null,
    val z: Int? = null,
    val i: BigDecimal? = null,
    val j: BigDecimal? = null,
    val k: BigDecimal? = null,
    val c: BigDecimal? = null,
    val h: BigDecimal? = null,
    val o: BigDecimal? = null,
) : GRq<FilamentSwapParameters> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(22)
        if (q) words.add(flag('Q'))
        if (linear != null) words.add(word('S', linear.toPlainString()))
        if (b != null) words.add(word('B', b.toPlainString()))
        if (e != null) words.add(word('E', e.toPlainString()))
        if (feedrate != null) words.add(word('P', feedrate))
        if (r != null) words.add(word('R', r))
        if (u != null) words.add(word('U', u))
        if (f != null) words.add(word('F', f))
        if (g != null) words.add(word('G', g))
        if (a != null) words.add(word('A', a))
        if (l != null) words.add(word('L', l))
        if (w != null) words.add(word('W', w))
        if (x != null) words.add(word('X', x.toPlainString()))
        if (y != null) words.add(word('Y', y.toPlainString()))
        if (v != null) words.add(word('V', v))
        if (z != null) words.add(word('Z', z))
        if (i != null) words.add(word('I', i.toPlainString()))
        if (j != null) words.add(word('J', j.toPlainString()))
        if (k != null) words.add(word('K', k.toPlainString()))
        if (c != null) words.add(word('C', c.toPlainString()))
        if (h != null) words.add(word('H', h.toPlainString()))
        if (o != null) words.add(word('O', o.toPlainString()))
        return M(217, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<FilamentSwapParameters> {

        override fun head(): GParameterWord<*> {
            return M(217).head
        }

        override fun decodeParams(tokens: List<GToken>): FilamentSwapParameters {
            return FilamentSwapParameters(
                q = tokens.hasWord('Q'),
                linear = tokens.decimalOf('S'),
                b = tokens.decimalOf('B'),
                e = tokens.decimalOf('E'),
                feedrate = tokens.intOf('P'),
                r = tokens.intOf('R'),
                u = tokens.intOf('U'),
                f = tokens.intOf('F'),
                g = tokens.intOf('G'),
                a = tokens.intOf('A'),
                l = tokens.intOf('L'),
                w = tokens.intOf('W'),
                x = tokens.decimalOf('X'),
                y = tokens.decimalOf('Y'),
                v = tokens.intOf('V'),
                z = tokens.intOf('Z'),
                i = tokens.decimalOf('I'),
                j = tokens.decimalOf('J'),
                k = tokens.decimalOf('K'),
                c = tokens.decimalOf('C'),
                h = tokens.decimalOf('H'),
                o = tokens.decimalOf('O'),
            )
        }
    }
}
