package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M207 [S<length>] [W<length>] [F<feedrate>] [Z<length>]
 *
 * Firmware Retraction Settings (motion).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(FirmwareRetractionSettings(length = BigDecimal("1.5")).encode())   // M207 S1.5
 * FirmwareRetractionSettings.decode(GTokenizer.parse("M207 S1.5").toList())   // FirmwareRetractionSettings(M207 S1.5)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property length `S` - length
 * @property w `W` - length
 * @property feedrate `F` - feedrate
 * @property z `Z` - length
 * @see <a href="https://marlinfw.org/docs/gcode/M207.html">MarlinFirmare M207 doc</a>
 */
data class FirmwareRetractionSettings(
    val length: BigDecimal? = null,
    val w: BigDecimal? = null,
    val feedrate: BigDecimal? = null,
    val z: BigDecimal? = null,
) : GRq<FirmwareRetractionSettings> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(4)
        if (length != null) words.add(word('S', length.toPlainString()))
        if (w != null) words.add(word('W', w.toPlainString()))
        if (feedrate != null) words.add(word('F', feedrate.toPlainString()))
        if (z != null) words.add(word('Z', z.toPlainString()))
        return M(207, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<FirmwareRetractionSettings> {

        override fun head(): GParameterWord<*> {
            return M(207).head
        }

        override fun decodeParams(tokens: List<GToken>): FirmwareRetractionSettings {
            return FirmwareRetractionSettings(
                length = tokens.decimalOf('S'),
                w = tokens.decimalOf('W'),
                feedrate = tokens.decimalOf('F'),
                z = tokens.decimalOf('Z'),
            )
        }
    }
}
