package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.flag
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.hasWord
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M493 [S<value>] [H<value>] [C<value>] [D<value>] [A<value>] [F<scale>] [I<zeta>] [Q<vtol>] [X] [Y] [Z] [E]
 *
 * Fixed-Time Motion (motion).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(FixedTimeMotion(s = 1).encode())   // M493 S1
 * FixedTimeMotion.decode(GTokenizer.parse("M493 S1").toList())   // FixedTimeMotion(M493 S1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property s `S`
 * @property h `H`
 * @property c `C`
 * @property d `D`
 * @property a `A`
 * @property scale `F` - scale
 * @property zeta `I` - zeta
 * @property vtol `Q` - vtol
 * @property x `X`
 * @property y `Y`
 * @property z `Z`
 * @property e `E`
 * @see <a href="https://marlinfw.org/docs/gcode/M493.html">MarlinFirmare M493 doc</a>
 */
data class FixedTimeMotion(
    val s: Int? = null,
    val h: Int? = null,
    val c: Int? = null,
    val d: Int? = null,
    val a: BigDecimal? = null,
    val scale: BigDecimal? = null,
    val zeta: BigDecimal? = null,
    val vtol: BigDecimal? = null,
    val x: Boolean = false,
    val y: Boolean = false,
    val z: Boolean = false,
    val e: Boolean = false,
) : GRq<FixedTimeMotion> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(12)
        if (s != null) words.add(word('S', s))
        if (h != null) words.add(word('H', h))
        if (c != null) words.add(word('C', c))
        if (d != null) words.add(word('D', d))
        if (a != null) words.add(word('A', a.toPlainString()))
        if (scale != null) words.add(word('F', scale.toPlainString()))
        if (zeta != null) words.add(word('I', zeta.toPlainString()))
        if (vtol != null) words.add(word('Q', vtol.toPlainString()))
        if (x) words.add(flag('X'))
        if (y) words.add(flag('Y'))
        if (z) words.add(flag('Z'))
        if (e) words.add(flag('E'))
        return M(493, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<FixedTimeMotion> {

        override fun head(): GParameterWord<*> {
            return M(493).head
        }

        override fun decodeParams(tokens: List<GToken>): FixedTimeMotion {
            return FixedTimeMotion(
                s = tokens.intOf('S'),
                h = tokens.intOf('H'),
                c = tokens.intOf('C'),
                d = tokens.intOf('D'),
                a = tokens.decimalOf('A'),
                scale = tokens.decimalOf('F'),
                zeta = tokens.decimalOf('I'),
                vtol = tokens.decimalOf('Q'),
                x = tokens.hasWord('X'),
                y = tokens.hasWord('Y'),
                z = tokens.hasWord('Z'),
                e = tokens.hasWord('E'),
            )
        }
    }
}
