package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.flag
import org.qw3rtrun.p3d.g.marlin.hasWord
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M494 [T] [O] [X] [Y] [Z] [E]
 *
 * FT Motion Trajectory Smoothing (motion).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(FTMotionTrajectorySmoothing(t = true).encode())   // M494 T
 * FTMotionTrajectorySmoothing.decode(GTokenizer.parse("M494 T").toList())   // FTMotionTrajectorySmoothing(M494 T)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property t `T`
 * @property o `O`
 * @property x `X`
 * @property y `Y`
 * @property z `Z`
 * @property e `E`
 * @see <a href="https://marlinfw.org/docs/gcode/M494.html">MarlinFirmare M494 doc</a>
 */
data class FTMotionTrajectorySmoothing(
    val t: Boolean = false,
    val o: Boolean = false,
    val x: Boolean = false,
    val y: Boolean = false,
    val z: Boolean = false,
    val e: Boolean = false,
) : GRq<FTMotionTrajectorySmoothing> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(6)
        if (t) words.add(flag('T'))
        if (o) words.add(flag('O'))
        if (x) words.add(flag('X'))
        if (y) words.add(flag('Y'))
        if (z) words.add(flag('Z'))
        if (e) words.add(flag('E'))
        return M(494, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<FTMotionTrajectorySmoothing> {

        override fun head(): GParameterWord<*> {
            return M(494).head
        }

        override fun decodeParams(tokens: List<GToken>): FTMotionTrajectorySmoothing {
            return FTMotionTrajectorySmoothing(
                t = tokens.hasWord('T'),
                o = tokens.hasWord('O'),
                x = tokens.hasWord('X'),
                y = tokens.hasWord('Y'),
                z = tokens.hasWord('Z'),
                e = tokens.hasWord('E'),
            )
        }
    }
}
