package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.bareString
import org.qw3rtrun.p3d.g.marlin.stringArg
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M819 [<gcode>]
 *
 * G-code macros.
 *
 * **`gcode` is a bare rest-of-line string** (spec 3.4a).
 * It carries no letter, it is written last because everything to the end of the
 * line belongs to it, and it cannot contain `;` - every parser reads that as the
 * start of a comment.
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(GCodeMacrosM819(gcode = "a tail").encode())   // M819 a tail
 * GCodeMacrosM819.decode(GTokenizer.parse("M819 a tail").toList())   // GCodeMacrosM819(M819 a tail)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property gcode the rest of the line
 * @see <a href="https://marlinfw.org/docs/gcode/M819.html">MarlinFirmare M819 doc</a>
 */
data class GCodeMacrosM819(
    val gcode: String? = null,
) : GRq<GCodeMacrosM819> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(1)
        if (gcode != null) words.add(bareString(gcode))
        return M(819, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<GCodeMacrosM819> {

        override fun head(): GParameterWord<*> {
            return M(819).head
        }

        override fun decodeParams(tokens: List<GToken>): GCodeMacrosM819 {
            return GCodeMacrosM819(
                gcode = tokens.stringArg(),
            )
        }
    }
}
