package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.flag
import org.qw3rtrun.p3d.g.marlin.hasWord
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M114 [D] [E] [R]
 *
 * Get Current Position (hosts).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(GetCurrentPosition(d = true).encode())   // M114 D
 * GetCurrentPosition.decode(GTokenizer.parse("M114 D").toList())   // GetCurrentPosition(M114 D)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property d `D`
 * @property e `E`
 * @property r `R`
 * @see <a href="https://marlinfw.org/docs/gcode/M114.html">MarlinFirmare M114 doc</a>
 */
data class GetCurrentPosition(
    val d: Boolean = false,
    val e: Boolean = false,
    val r: Boolean = false,
) : GRq<GetCurrentPosition> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(3)
        if (d) words.add(flag('D'))
        if (e) words.add(flag('E'))
        if (r) words.add(flag('R'))
        return M(114, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<GetCurrentPosition> {

        override fun head(): GParameterWord<*> {
            return M(114).head
        }

        override fun decodeParams(tokens: List<GToken>): GetCurrentPosition {
            return GetCurrentPosition(
                d = tokens.hasWord('D'),
                e = tokens.hasWord('E'),
                r = tokens.hasWord('R'),
            )
        }
    }
}
