package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.boolOf
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M166 A<linear> Z<linear> I<index> J<index> [S<enable>] [T<index>]
 *
 * Gradient Mix (mixing).
 *
 * Marlin documents `A`, `Z`, `I`, `J` as required; every property here still defaults to
 * absent, so that every command class is constructible bare.
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(GradientMix(linear = BigDecimal("1.5")).encode())   // M166 A1.5
 * GradientMix.decode(GTokenizer.parse("M166 A1.5").toList())   // GradientMix(M166 A1.5)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property linear `A` - linear (required)
 * @property z `Z` - linear (required)
 * @property index `I` - index (required)
 * @property j `J` - index (required)
 * @property enable `S` - enable
 * @property t `T` - index
 * @see <a href="https://marlinfw.org/docs/gcode/M166.html">MarlinFirmare M166 doc</a>
 */
data class GradientMix(
    val linear: BigDecimal? = null,
    val z: BigDecimal? = null,
    val index: Int? = null,
    val j: Int? = null,
    val enable: Boolean? = null,
    val t: Int? = null,
) : GRq<GradientMix> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(6)
        if (linear != null) words.add(word('A', linear.toPlainString()))
        if (z != null) words.add(word('Z', z.toPlainString()))
        if (index != null) words.add(word('I', index))
        if (j != null) words.add(word('J', j))
        if (enable != null) words.add(word('S', if (enable) 1 else 0))
        if (t != null) words.add(word('T', t))
        return M(166, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<GradientMix> {

        override fun head(): GParameterWord<*> {
            return M(166).head
        }

        override fun decodeParams(tokens: List<GToken>): GradientMix {
            return GradientMix(
                linear = tokens.decimalOf('A'),
                z = tokens.decimalOf('Z'),
                index = tokens.intOf('I'),
                j = tokens.intOf('J'),
                enable = tokens.boolOf('S'),
                t = tokens.intOf('T'),
            )
        }
    }
}
