package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M210 [X<feedrate>] [Y<feedrate>] [Z<feedrate>] [A<feedrate>] [B<feedrate>] [C<feedrate>] [U<feedrate>] [V<feedrate>] [W<feedrate>]
 *
 * Homing Feedrate (calibration).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(HomingFeedrate(feedrate = BigDecimal("1.5")).encode())   // M210 X1.5
 * HomingFeedrate.decode(GTokenizer.parse("M210 X1.5").toList())   // HomingFeedrate(M210 X1.5)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property feedrate `X` - feedrate
 * @property y `Y` - feedrate
 * @property z `Z` - feedrate
 * @property a `A` - feedrate
 * @property b `B` - feedrate
 * @property c `C` - feedrate
 * @property u `U` - feedrate
 * @property v `V` - feedrate
 * @property w `W` - feedrate
 * @see <a href="https://marlinfw.org/docs/gcode/M210.html">MarlinFirmare M210 doc</a>
 */
data class HomingFeedrate(
    val feedrate: BigDecimal? = null,
    val y: BigDecimal? = null,
    val z: BigDecimal? = null,
    val a: BigDecimal? = null,
    val b: BigDecimal? = null,
    val c: BigDecimal? = null,
    val u: BigDecimal? = null,
    val v: BigDecimal? = null,
    val w: BigDecimal? = null,
) : GRq<HomingFeedrate> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(9)
        if (feedrate != null) words.add(word('X', feedrate.toPlainString()))
        if (y != null) words.add(word('Y', y.toPlainString()))
        if (z != null) words.add(word('Z', z.toPlainString()))
        if (a != null) words.add(word('A', a.toPlainString()))
        if (b != null) words.add(word('B', b.toPlainString()))
        if (c != null) words.add(word('C', c.toPlainString()))
        if (u != null) words.add(word('U', u.toPlainString()))
        if (v != null) words.add(word('V', v.toPlainString()))
        if (w != null) words.add(word('W', w.toPlainString()))
        return M(210, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<HomingFeedrate> {

        override fun head(): GParameterWord<*> {
            return M(210).head
        }

        override fun decodeParams(tokens: List<GToken>): HomingFeedrate {
            return HomingFeedrate(
                feedrate = tokens.decimalOf('X'),
                y = tokens.decimalOf('Y'),
                z = tokens.decimalOf('Z'),
                a = tokens.decimalOf('A'),
                b = tokens.decimalOf('B'),
                c = tokens.decimalOf('C'),
                u = tokens.decimalOf('U'),
                v = tokens.decimalOf('V'),
                w = tokens.decimalOf('W'),
            )
        }
    }
}
