package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M113 [S<seconds>]
 *
 * Host Keepalive (hosts).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(HostKeepalive(seconds = 1).encode())   // M113 S1
 * HostKeepalive.decode(GTokenizer.parse("M113 S1").toList())   // HostKeepalive(M113 S1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property seconds `S` - seconds
 * @see <a href="https://marlinfw.org/docs/gcode/M113.html">MarlinFirmare M113 doc</a>
 */
data class HostKeepalive(
    val seconds: Int? = null,
) : GRq<HostKeepalive> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(1)
        if (seconds != null) words.add(word('S', seconds))
        return M(113, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<HostKeepalive> {

        override fun head(): GParameterWord<*> {
            return M(113).head
        }

        override fun decodeParams(tokens: List<GToken>): HostKeepalive {
            return HostKeepalive(
                seconds = tokens.intOf('S'),
            )
        }
    }
}
