package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.flag
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.boolOf
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.hasWord
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M862 [I<index>] [O<value>] [X] [Y] [Z] [E] [U<value>] [P<value>] [S<addr>] [R<value>] [T<value>]
 *
 * I2C Position Encoders (encoder).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(I2CPositionEncodersM862(index = 1).encode())   // M862 I1
 * I2CPositionEncodersM862.decode(GTokenizer.parse("M862 I1").toList())   // I2CPositionEncodersM862(M862 I1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property index `I` - index
 * @property o `O`
 * @property axis `X` - axis
 * @property y `Y` - axis
 * @property z `Z` - axis
 * @property e `E` - axis
 * @property u `U`
 * @property p `P`
 * @property addr `S` - addr
 * @property r `R`
 * @property t `T`
 * @see <a href="https://marlinfw.org/docs/gcode/M862.html">MarlinFirmare M862 doc</a>
 */
data class I2CPositionEncodersM862(
    val index: Int? = null,
    val o: Boolean? = null,
    val axis: Boolean = false,
    val y: Boolean = false,
    val z: Boolean = false,
    val e: Boolean = false,
    val u: Boolean? = null,
    val p: Int? = null,
    val addr: Int? = null,
    val r: Boolean? = null,
    val t: BigDecimal? = null,
) : GRq<I2CPositionEncodersM862> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(11)
        if (index != null) words.add(word('I', index))
        if (o != null) words.add(word('O', if (o) 1 else 0))
        if (axis) words.add(flag('X'))
        if (y) words.add(flag('Y'))
        if (z) words.add(flag('Z'))
        if (e) words.add(flag('E'))
        if (u != null) words.add(word('U', if (u) 1 else 0))
        if (p != null) words.add(word('P', p))
        if (addr != null) words.add(word('S', addr))
        if (r != null) words.add(word('R', if (r) 1 else 0))
        if (t != null) words.add(word('T', t.toPlainString()))
        return M(862, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<I2CPositionEncodersM862> {

        override fun head(): GParameterWord<*> {
            return M(862).head
        }

        override fun decodeParams(tokens: List<GToken>): I2CPositionEncodersM862 {
            return I2CPositionEncodersM862(
                index = tokens.intOf('I'),
                o = tokens.boolOf('O'),
                axis = tokens.hasWord('X'),
                y = tokens.hasWord('Y'),
                z = tokens.hasWord('Z'),
                e = tokens.hasWord('E'),
                u = tokens.boolOf('U'),
                p = tokens.intOf('P'),
                addr = tokens.intOf('S'),
                r = tokens.boolOf('R'),
                t = tokens.decimalOf('T'),
            )
        }
    }
}
