package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M261 A<addr> B<count> [S<value>]
 *
 * I2C Request (i2c).
 *
 * Marlin documents `A`, `B` as required; every property here still defaults to
 * absent, so that every command class is constructible bare.
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(I2CRequest(addr = 1).encode())   // M261 A1
 * I2CRequest.decode(GTokenizer.parse("M261 A1").toList())   // I2CRequest(M261 A1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property addr `A` - addr (required)
 * @property count `B` - count (required)
 * @property s `S`
 * @see <a href="https://marlinfw.org/docs/gcode/M261.html">MarlinFirmare M261 doc</a>
 */
data class I2CRequest(
    val addr: Int? = null,
    val count: Int? = null,
    val s: Int? = null,
) : GRq<I2CRequest> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(3)
        if (addr != null) words.add(word('A', addr))
        if (count != null) words.add(word('B', count))
        if (s != null) words.add(word('S', s))
        return M(261, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<I2CRequest> {

        override fun head(): GParameterWord<*> {
            return M(261).head
        }

        override fun decodeParams(tokens: List<GToken>): I2CRequest {
            return I2CRequest(
                addr = tokens.intOf('A'),
                count = tokens.intOf('B'),
                s = tokens.intOf('S'),
            )
        }
    }
}
