package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M916 [J<value>] [X<value>] [Y<value>] [Z<value>] [E<value>] [F<feedrate>] [T<current>] [K<value>] [D<second>]
 *
 * L6474 Thermal Warning Test (L6474).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(L6474ThermalWarningTest(j = 1).encode())   // M916 J1
 * L6474ThermalWarningTest.decode(GTokenizer.parse("M916 J1").toList())   // L6474ThermalWarningTest(M916 J1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property j `J`
 * @property x `X`
 * @property y `Y`
 * @property z `Z`
 * @property e `E`
 * @property feedrate `F` - feedrate
 * @property current `T` - current
 * @property k `K`
 * @property second `D` - second
 * @see <a href="https://marlinfw.org/docs/gcode/M916.html">MarlinFirmare M916 doc</a>
 */
data class L6474ThermalWarningTest(
    val j: Int? = null,
    val x: BigDecimal? = null,
    val y: BigDecimal? = null,
    val z: BigDecimal? = null,
    val e: BigDecimal? = null,
    val feedrate: Int? = null,
    val current: Int? = null,
    val k: Int? = null,
    val second: Int? = null,
) : GRq<L6474ThermalWarningTest> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(9)
        if (j != null) words.add(word('J', j))
        if (x != null) words.add(word('X', x.toPlainString()))
        if (y != null) words.add(word('Y', y.toPlainString()))
        if (z != null) words.add(word('Z', z.toPlainString()))
        if (e != null) words.add(word('E', e.toPlainString()))
        if (feedrate != null) words.add(word('F', feedrate))
        if (current != null) words.add(word('T', current))
        if (k != null) words.add(word('K', k))
        if (second != null) words.add(word('D', second))
        return M(916, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<L6474ThermalWarningTest> {

        override fun head(): GParameterWord<*> {
            return M(916).head
        }

        override fun decodeParams(tokens: List<GToken>): L6474ThermalWarningTest {
            return L6474ThermalWarningTest(
                j = tokens.intOf('J'),
                x = tokens.decimalOf('X'),
                y = tokens.decimalOf('Y'),
                z = tokens.decimalOf('Z'),
                e = tokens.decimalOf('E'),
                feedrate = tokens.intOf('F'),
                current = tokens.intOf('T'),
                k = tokens.intOf('K'),
                second = tokens.intOf('D'),
            )
        }
    }
}
