package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M917 [J<value>] [X<value>] [Y<value>] [Z<value>] [A<value>] [B<value>] [C<value>] [U<value>] [V<value>] [W<value>] [E<value>] [F<feedrate>] [I<current>] [T<current>] [K<value>]
 *
 * L6474 Overcurrent Warning Test (L6474).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(L6474OvercurrentWarningTest(j = 1).encode())   // M917 J1
 * L6474OvercurrentWarningTest.decode(GTokenizer.parse("M917 J1").toList())   // L6474OvercurrentWarningTest(M917 J1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property j `J`
 * @property x `X`
 * @property y `Y`
 * @property z `Z`
 * @property a `A`
 * @property b `B`
 * @property c `C`
 * @property u `U`
 * @property v `V`
 * @property w `W`
 * @property e `E`
 * @property feedrate `F` - feedrate
 * @property current `I` - current
 * @property t `T` - current
 * @property k `K`
 * @see <a href="https://marlinfw.org/docs/gcode/M917.html">MarlinFirmare M917 doc</a>
 */
data class L6474OvercurrentWarningTest(
    val j: Int? = null,
    val x: BigDecimal? = null,
    val y: BigDecimal? = null,
    val z: BigDecimal? = null,
    val a: BigDecimal? = null,
    val b: BigDecimal? = null,
    val c: BigDecimal? = null,
    val u: BigDecimal? = null,
    val v: BigDecimal? = null,
    val w: BigDecimal? = null,
    val e: BigDecimal? = null,
    val feedrate: Int? = null,
    val current: Int? = null,
    val t: Int? = null,
    val k: Int? = null,
) : GRq<L6474OvercurrentWarningTest> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(15)
        if (j != null) words.add(word('J', j))
        if (x != null) words.add(word('X', x.toPlainString()))
        if (y != null) words.add(word('Y', y.toPlainString()))
        if (z != null) words.add(word('Z', z.toPlainString()))
        if (a != null) words.add(word('A', a.toPlainString()))
        if (b != null) words.add(word('B', b.toPlainString()))
        if (c != null) words.add(word('C', c.toPlainString()))
        if (u != null) words.add(word('U', u.toPlainString()))
        if (v != null) words.add(word('V', v.toPlainString()))
        if (w != null) words.add(word('W', w.toPlainString()))
        if (e != null) words.add(word('E', e.toPlainString()))
        if (feedrate != null) words.add(word('F', feedrate))
        if (current != null) words.add(word('I', current))
        if (t != null) words.add(word('T', t))
        if (k != null) words.add(word('K', k))
        return M(917, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<L6474OvercurrentWarningTest> {

        override fun head(): GParameterWord<*> {
            return M(917).head
        }

        override fun decodeParams(tokens: List<GToken>): L6474OvercurrentWarningTest {
            return L6474OvercurrentWarningTest(
                j = tokens.intOf('J'),
                x = tokens.decimalOf('X'),
                y = tokens.decimalOf('Y'),
                z = tokens.decimalOf('Z'),
                a = tokens.decimalOf('A'),
                b = tokens.decimalOf('B'),
                c = tokens.decimalOf('C'),
                u = tokens.decimalOf('U'),
                v = tokens.decimalOf('V'),
                w = tokens.decimalOf('W'),
                e = tokens.decimalOf('E'),
                feedrate = tokens.intOf('F'),
                current = tokens.intOf('I'),
                t = tokens.intOf('T'),
                k = tokens.intOf('K'),
            )
        }
    }
}
