package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M918 [J<value>] [X<value>] [Y<value>] [Z<value>] [E<value>] [I<current>] [T<current>] [K<value>] [M<microsteps>]
 *
 * L6474 Speed Warning Test (L6474).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(L6474SpeedWarningTest(j = 1).encode())   // M918 J1
 * L6474SpeedWarningTest.decode(GTokenizer.parse("M918 J1").toList())   // L6474SpeedWarningTest(M918 J1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property j `J`
 * @property x `X`
 * @property y `Y`
 * @property z `Z`
 * @property e `E`
 * @property current `I` - current
 * @property t `T` - current
 * @property k `K`
 * @property microsteps `M` - microsteps
 * @see <a href="https://marlinfw.org/docs/gcode/M918.html">MarlinFirmare M918 doc</a>
 */
data class L6474SpeedWarningTest(
    val j: Int? = null,
    val x: BigDecimal? = null,
    val y: BigDecimal? = null,
    val z: BigDecimal? = null,
    val e: BigDecimal? = null,
    val current: Int? = null,
    val t: Int? = null,
    val k: Int? = null,
    val microsteps: Int? = null,
) : GRq<L6474SpeedWarningTest> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(9)
        if (j != null) words.add(word('J', j))
        if (x != null) words.add(word('X', x.toPlainString()))
        if (y != null) words.add(word('Y', y.toPlainString()))
        if (z != null) words.add(word('Z', z.toPlainString()))
        if (e != null) words.add(word('E', e.toPlainString()))
        if (current != null) words.add(word('I', current))
        if (t != null) words.add(word('T', t))
        if (k != null) words.add(word('K', k))
        if (microsteps != null) words.add(word('M', microsteps))
        return M(918, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<L6474SpeedWarningTest> {

        override fun head(): GParameterWord<*> {
            return M(918).head
        }

        override fun decodeParams(tokens: List<GToken>): L6474SpeedWarningTest {
            return L6474SpeedWarningTest(
                j = tokens.intOf('J'),
                x = tokens.decimalOf('X'),
                y = tokens.decimalOf('Y'),
                z = tokens.decimalOf('Z'),
                e = tokens.decimalOf('E'),
                current = tokens.intOf('I'),
                t = tokens.intOf('T'),
                k = tokens.intOf('K'),
                microsteps = tokens.intOf('M'),
            )
        }
    }
}
