package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M256 [B<brightness>]
 *
 * LCD Brightness (lcd).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(LCDBrightness(brightness = 1).encode())   // M256 B1
 * LCDBrightness.decode(GTokenizer.parse("M256 B1").toList())   // LCDBrightness(M256 B1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property brightness `B` - brightness
 * @see <a href="https://marlinfw.org/docs/gcode/M256.html">MarlinFirmare M256 doc</a>
 */
data class LCDBrightness(
    val brightness: Int? = null,
) : GRq<LCDBrightness> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(1)
        if (brightness != null) words.add(word('B', brightness))
        return M(256, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<LCDBrightness> {

        override fun head(): GParameterWord<*> {
            return M(256).head
        }

        override fun decodeParams(tokens: List<GToken>): LCDBrightness {
            return LCDBrightness(
                brightness = tokens.intOf('B'),
            )
        }
    }
}
