package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M414 [S<language-index>]
 *
 * LCD language (lcd).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(LCDLanguage(languageIndex = 1).encode())   // M414 S1
 * LCDLanguage.decode(GTokenizer.parse("M414 S1").toList())   // LCDLanguage(M414 S1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property languageIndex `S` - language-index
 * @see <a href="https://marlinfw.org/docs/gcode/M414.html">MarlinFirmare M414 doc</a>
 */
data class LCDLanguage(
    val languageIndex: Int? = null,
) : GRq<LCDLanguage> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(1)
        if (languageIndex != null) words.add(word('S', languageIndex))
        return M(414, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<LCDLanguage> {

        override fun head(): GParameterWord<*> {
            return M(414).head
        }

        override fun decodeParams(tokens: List<GToken>): LCDLanguage {
            return LCDLanguage(
                languageIndex = tokens.intOf('S'),
            )
        }
    }
}
