package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M255 [S<minutes>]
 *
 * LCD Sleep/Backlight Timeout (lcd).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(LCDSleepBacklightTimeout(minutes = 1).encode())   // M255 S1
 * LCDSleepBacklightTimeout.decode(GTokenizer.parse("M255 S1").toList())   // LCDSleepBacklightTimeout(M255 S1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property minutes `S` - minutes
 * @see <a href="https://marlinfw.org/docs/gcode/M255.html">MarlinFirmare M255 doc</a>
 */
data class LCDSleepBacklightTimeout(
    val minutes: Int? = null,
) : GRq<LCDSleepBacklightTimeout> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(1)
        if (minutes != null) words.add(word('S', minutes))
        return M(255, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<LCDSleepBacklightTimeout> {

        override fun head(): GParameterWord<*> {
            return M(255).head
        }

        override fun decodeParams(tokens: List<GToken>): LCDSleepBacklightTimeout {
            return LCDSleepBacklightTimeout(
                minutes = tokens.intOf('S'),
            )
        }
    }
}
