package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.G
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * G0 [X<pos>] [Y<pos>] [Z<pos>] [A<pos>] [B<pos>] [C<pos>] [U<pos>] [V<pos>] [W<pos>] [E<pos>] [F<rate>] [S<power>]
 *
 * Linear Move (motion).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(LinearMoveG0(pos = BigDecimal("1.5")).encode())   // G0 X1.5
 * LinearMoveG0.decode(GTokenizer.parse("G0 X1.5").toList())   // LinearMoveG0(G0 X1.5)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property pos `X` - pos
 * @property y `Y` - pos
 * @property z `Z` - pos
 * @property a `A` - pos
 * @property b `B` - pos
 * @property c `C` - pos
 * @property u `U` - pos
 * @property v `V` - pos
 * @property w `W` - pos
 * @property e `E` - pos
 * @property rate `F` - rate
 * @property power `S` - power
 * @see <a href="https://marlinfw.org/docs/gcode/G0.html">MarlinFirmare G0 doc</a>
 */
data class LinearMoveG0(
    val pos: BigDecimal? = null,
    val y: BigDecimal? = null,
    val z: BigDecimal? = null,
    val a: BigDecimal? = null,
    val b: BigDecimal? = null,
    val c: BigDecimal? = null,
    val u: BigDecimal? = null,
    val v: BigDecimal? = null,
    val w: BigDecimal? = null,
    val e: BigDecimal? = null,
    val rate: BigDecimal? = null,
    val power: BigDecimal? = null,
) : GRq<LinearMoveG0> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(12)
        if (pos != null) words.add(word('X', pos.toPlainString()))
        if (y != null) words.add(word('Y', y.toPlainString()))
        if (z != null) words.add(word('Z', z.toPlainString()))
        if (a != null) words.add(word('A', a.toPlainString()))
        if (b != null) words.add(word('B', b.toPlainString()))
        if (c != null) words.add(word('C', c.toPlainString()))
        if (u != null) words.add(word('U', u.toPlainString()))
        if (v != null) words.add(word('V', v.toPlainString()))
        if (w != null) words.add(word('W', w.toPlainString()))
        if (e != null) words.add(word('E', e.toPlainString()))
        if (rate != null) words.add(word('F', rate.toPlainString()))
        if (power != null) words.add(word('S', power.toPlainString()))
        return G(0, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<LinearMoveG0> {

        override fun head(): GParameterWord<*> {
            return G(0).head
        }

        override fun decodeParams(tokens: List<GToken>): LinearMoveG0 {
            return LinearMoveG0(
                pos = tokens.decimalOf('X'),
                y = tokens.decimalOf('Y'),
                z = tokens.decimalOf('Z'),
                a = tokens.decimalOf('A'),
                b = tokens.decimalOf('B'),
                c = tokens.decimalOf('C'),
                u = tokens.decimalOf('U'),
                v = tokens.decimalOf('V'),
                w = tokens.decimalOf('W'),
                e = tokens.decimalOf('E'),
                rate = tokens.decimalOf('F'),
                power = tokens.decimalOf('S'),
            )
        }
    }
}
