package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M900 [K<kfactor>] [L<kfactor>] [S<slot>] [T<index>]
 *
 * Linear Advance Factor (control).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(LinearAdvanceFactor(kfactor = BigDecimal("1.5")).encode())   // M900 K1.5
 * LinearAdvanceFactor.decode(GTokenizer.parse("M900 K1.5").toList())   // LinearAdvanceFactor(M900 K1.5)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property kfactor `K` - kfactor
 * @property l `L` - kfactor
 * @property slot `S` - slot
 * @property index `T` - index
 * @see <a href="https://marlinfw.org/docs/gcode/M900.html">MarlinFirmare M900 doc</a>
 */
data class LinearAdvanceFactor(
    val kfactor: BigDecimal? = null,
    val l: BigDecimal? = null,
    val slot: Int? = null,
    val index: Int? = null,
) : GRq<LinearAdvanceFactor> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(4)
        if (kfactor != null) words.add(word('K', kfactor.toPlainString()))
        if (l != null) words.add(word('L', l.toPlainString()))
        if (slot != null) words.add(word('S', slot))
        if (index != null) words.add(word('T', index))
        return M(900, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<LinearAdvanceFactor> {

        override fun head(): GParameterWord<*> {
            return M(900).head
        }

        override fun decodeParams(tokens: List<GToken>): LinearAdvanceFactor {
            return LinearAdvanceFactor(
                kfactor = tokens.decimalOf('K'),
                l = tokens.decimalOf('L'),
                slot = tokens.intOf('S'),
                index = tokens.intOf('T'),
            )
        }
    }
}
