package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.flag
import org.qw3rtrun.p3d.g.marlin.hasWord
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M20 [F] [L] [T]
 *
 * List SD Card (sdcard).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(ListSDCard(f = true).encode())   // M20 F
 * ListSDCard.decode(GTokenizer.parse("M20 F").toList())   // ListSDCard(M20 F)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property f `F`
 * @property l `L`
 * @property t `T`
 * @see <a href="https://marlinfw.org/docs/gcode/M20.html">MarlinFirmare M20 doc</a>
 */
data class ListSDCard(
    val f: Boolean = false,
    val l: Boolean = false,
    val t: Boolean = false,
) : GRq<ListSDCard> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(3)
        if (f) words.add(flag('F'))
        if (l) words.add(flag('L'))
        if (t) words.add(flag('T'))
        return M(20, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<ListSDCard> {

        override fun head(): GParameterWord<*> {
            return M(20).head
        }

        override fun decodeParams(tokens: List<GToken>): ListSDCard {
            return ListSDCard(
                f = tokens.hasWord('F'),
                l = tokens.hasWord('L'),
                t = tokens.hasWord('T'),
            )
        }
    }
}
