package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M951 [L<value>] [R<value>] [I<value>] [J<value>] [H<value>] [D<value>] [C<value>]
 *
 * Magnetic Parking Extruder (calibration).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(MagneticParkingExtruder(l = BigDecimal("1.5")).encode())   // M951 L1.5
 * MagneticParkingExtruder.decode(GTokenizer.parse("M951 L1.5").toList())   // MagneticParkingExtruder(M951 L1.5)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property l `L`
 * @property r `R`
 * @property i `I`
 * @property j `J`
 * @property h `H`
 * @property d `D`
 * @property c `C`
 * @see <a href="https://marlinfw.org/docs/gcode/M951.html">MarlinFirmare M951 doc</a>
 */
data class MagneticParkingExtruder(
    val l: BigDecimal? = null,
    val r: BigDecimal? = null,
    val i: BigDecimal? = null,
    val j: BigDecimal? = null,
    val h: BigDecimal? = null,
    val d: BigDecimal? = null,
    val c: BigDecimal? = null,
) : GRq<MagneticParkingExtruder> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(7)
        if (l != null) words.add(word('L', l.toPlainString()))
        if (r != null) words.add(word('R', r.toPlainString()))
        if (i != null) words.add(word('I', i.toPlainString()))
        if (j != null) words.add(word('J', j.toPlainString()))
        if (h != null) words.add(word('H', h.toPlainString()))
        if (d != null) words.add(word('D', d.toPlainString()))
        if (c != null) words.add(word('C', c.toPlainString()))
        return M(951, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<MagneticParkingExtruder> {

        override fun head(): GParameterWord<*> {
            return M(951).head
        }

        override fun decodeParams(tokens: List<GToken>): MagneticParkingExtruder {
            return MagneticParkingExtruder(
                l = tokens.decimalOf('L'),
                r = tokens.decimalOf('R'),
                i = tokens.decimalOf('I'),
                j = tokens.decimalOf('J'),
                h = tokens.decimalOf('H'),
                d = tokens.decimalOf('D'),
                c = tokens.decimalOf('C'),
            )
        }
    }
}
