package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.flag
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.hasWord
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.marlin.longOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M7219 [C<column>] [D<row>] [R<row>] [I] [F] [P] [U<index>] [V<bits>] [X<index>] [Y<index>]
 *
 * MAX7219 Control (debug).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(MAX7219Control(column = 1).encode())   // M7219 C1
 * MAX7219Control.decode(GTokenizer.parse("M7219 C1").toList())   // MAX7219Control(M7219 C1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property column `C` - column
 * @property row `D` - row
 * @property r `R` - row
 * @property i `I`
 * @property f `F`
 * @property p `P`
 * @property index `U` - index
 * @property bits `V` - bits
 * @property x `X` - index
 * @property y `Y` - index
 * @see <a href="https://marlinfw.org/docs/gcode/M7219.html">MarlinFirmare M7219 doc</a>
 */
data class MAX7219Control(
    val column: Int? = null,
    val row: Int? = null,
    val r: Int? = null,
    val i: Boolean = false,
    val f: Boolean = false,
    val p: Boolean = false,
    val index: Int? = null,
    val bits: Long? = null,
    val x: Int? = null,
    val y: Int? = null,
) : GRq<MAX7219Control> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(10)
        if (column != null) words.add(word('C', column))
        if (row != null) words.add(word('D', row))
        if (r != null) words.add(word('R', r))
        if (i) words.add(flag('I'))
        if (f) words.add(flag('F'))
        if (p) words.add(flag('P'))
        if (index != null) words.add(word('U', index))
        if (bits != null) words.add(word('V', BigDecimal.valueOf(bits)))
        if (x != null) words.add(word('X', x))
        if (y != null) words.add(word('Y', y))
        return M(7219, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<MAX7219Control> {

        override fun head(): GParameterWord<*> {
            return M(7219).head
        }

        override fun decodeParams(tokens: List<GToken>): MAX7219Control {
            return MAX7219Control(
                column = tokens.intOf('C'),
                row = tokens.intOf('D'),
                r = tokens.intOf('R'),
                i = tokens.hasWord('I'),
                f = tokens.hasWord('F'),
                p = tokens.hasWord('P'),
                index = tokens.intOf('U'),
                bits = tokens.longOf('V'),
                x = tokens.intOf('X'),
                y = tokens.intOf('Y'),
            )
        }
    }
}
