package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.G
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * G34 [S<value>] [Z<value>]
 *
 * Mechanical Gantry Calibration (calibration).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(MechanicalGantryCalibration(s = 1).encode())   // G34 S1
 * MechanicalGantryCalibration.decode(GTokenizer.parse("G34 S1").toList())   // MechanicalGantryCalibration(G34 S1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property s `S`
 * @property z `Z`
 * @see <a href="https://marlinfw.org/docs/gcode/G34.html">MarlinFirmare G34 doc</a>
 */
data class MechanicalGantryCalibration(
    val s: Int? = null,
    val z: BigDecimal? = null,
) : GRq<MechanicalGantryCalibration> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(2)
        if (s != null) words.add(word('S', s))
        if (z != null) words.add(word('Z', z.toPlainString()))
        return G(34, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<MechanicalGantryCalibration> {

        override fun head(): GParameterWord<*> {
            return G(34).head
        }

        override fun decodeParams(tokens: List<GToken>): MechanicalGantryCalibration {
            return MechanicalGantryCalibration(
                s = tokens.intOf('S'),
                z = tokens.decimalOf('Z'),
            )
        }
    }
}
