package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.G
import org.qw3rtrun.p3d.g.code.dsl.flag
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.boolOf
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.hasWord
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * G26 [B<temp>] [C<value>] [D] [F<linear>] [H<linear>] [I<index>] [K<value>] [L<linear>] [O<linear>] [P<linear>] [Q<value>] [R<value>] [S<value>] [U<linear>] [X<linear>] [Y<linear>]
 *
 * Mesh Validation Pattern (calibration).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(MeshValidationPattern(temp = 1).encode())   // G26 B1
 * MeshValidationPattern.decode(GTokenizer.parse("G26 B1").toList())   // MeshValidationPattern(G26 B1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property temp `B` - temp
 * @property c `C`
 * @property d `D`
 * @property linear `F` - linear
 * @property h `H` - linear
 * @property index `I` - index
 * @property k `K`
 * @property l `L` - linear
 * @property o `O` - linear
 * @property p `P` - linear
 * @property q `Q`
 * @property r `R`
 * @property s `S`
 * @property u `U` - linear
 * @property x `X` - linear
 * @property y `Y` - linear
 * @see <a href="https://marlinfw.org/docs/gcode/G26.html">MarlinFirmare G26 doc</a>
 */
data class MeshValidationPattern(
    val temp: Int? = null,
    val c: Boolean? = null,
    val d: Boolean = false,
    val linear: BigDecimal? = null,
    val h: BigDecimal? = null,
    val index: Int? = null,
    val k: Boolean? = null,
    val l: BigDecimal? = null,
    val o: BigDecimal? = null,
    val p: BigDecimal? = null,
    val q: BigDecimal? = null,
    val r: Int? = null,
    val s: BigDecimal? = null,
    val u: BigDecimal? = null,
    val x: BigDecimal? = null,
    val y: BigDecimal? = null,
) : GRq<MeshValidationPattern> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(16)
        if (temp != null) words.add(word('B', temp))
        if (c != null) words.add(word('C', if (c) 1 else 0))
        if (d) words.add(flag('D'))
        if (linear != null) words.add(word('F', linear.toPlainString()))
        if (h != null) words.add(word('H', h.toPlainString()))
        if (index != null) words.add(word('I', index))
        if (k != null) words.add(word('K', if (k) 1 else 0))
        if (l != null) words.add(word('L', l.toPlainString()))
        if (o != null) words.add(word('O', o.toPlainString()))
        if (p != null) words.add(word('P', p.toPlainString()))
        if (q != null) words.add(word('Q', q.toPlainString()))
        if (r != null) words.add(word('R', r))
        if (s != null) words.add(word('S', s.toPlainString()))
        if (u != null) words.add(word('U', u.toPlainString()))
        if (x != null) words.add(word('X', x.toPlainString()))
        if (y != null) words.add(word('Y', y.toPlainString()))
        return G(26, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<MeshValidationPattern> {

        override fun head(): GParameterWord<*> {
            return G(26).head
        }

        override fun decodeParams(tokens: List<GToken>): MeshValidationPattern {
            return MeshValidationPattern(
                temp = tokens.intOf('B'),
                c = tokens.boolOf('C'),
                d = tokens.hasWord('D'),
                linear = tokens.decimalOf('F'),
                h = tokens.decimalOf('H'),
                index = tokens.intOf('I'),
                k = tokens.boolOf('K'),
                l = tokens.decimalOf('L'),
                o = tokens.decimalOf('O'),
                p = tokens.decimalOf('P'),
                q = tokens.decimalOf('Q'),
                r = tokens.intOf('R'),
                s = tokens.decimalOf('S'),
                u = tokens.decimalOf('U'),
                x = tokens.decimalOf('X'),
                y = tokens.decimalOf('Y'),
            )
        }
    }
}
