package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M403 E<index> F<value>
 *
 * MMU2 Filament Type (control).
 *
 * Marlin documents `E`, `F` as required; every property here still defaults to
 * absent, so that every command class is constructible bare.
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(MMU2FilamentType(index = 1).encode())   // M403 E1
 * MMU2FilamentType.decode(GTokenizer.parse("M403 E1").toList())   // MMU2FilamentType(M403 E1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property index `E` - index (required)
 * @property f `F` (required)
 * @see <a href="https://marlinfw.org/docs/gcode/M403.html">MarlinFirmare M403 doc</a>
 */
data class MMU2FilamentType(
    val index: Int? = null,
    val f: Int? = null,
) : GRq<MMU2FilamentType> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(2)
        if (index != null) words.add(word('E', index))
        if (f != null) words.add(word('F', f))
        return M(403, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<MMU2FilamentType> {

        override fun head(): GParameterWord<*> {
            return M(403).head
        }

        override fun decodeParams(tokens: List<GToken>): MMU2FilamentType {
            return MMU2FilamentType(
                index = tokens.intOf('E'),
                f = tokens.intOf('F'),
            )
        }
    }
}
