package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.G
import org.qw3rtrun.p3d.g.code.dsl.flag
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.hasWord
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * G42 [I<pos>] [J<pos>] [F<rate>] [P]
 *
 * Move to mesh coordinate (calibration).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(MoveToMeshCoordinate(pos = BigDecimal("1.5")).encode())   // G42 I1.5
 * MoveToMeshCoordinate.decode(GTokenizer.parse("G42 I1.5").toList())   // MoveToMeshCoordinate(G42 I1.5)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property pos `I` - pos
 * @property j `J` - pos
 * @property rate `F` - rate
 * @property p `P`
 * @see <a href="https://marlinfw.org/docs/gcode/G42.html">MarlinFirmare G42 doc</a>
 */
data class MoveToMeshCoordinate(
    val pos: BigDecimal? = null,
    val j: BigDecimal? = null,
    val rate: BigDecimal? = null,
    val p: Boolean = false,
) : GRq<MoveToMeshCoordinate> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(4)
        if (pos != null) words.add(word('I', pos.toPlainString()))
        if (j != null) words.add(word('J', j.toPlainString()))
        if (rate != null) words.add(word('F', rate.toPlainString()))
        if (p) words.add(flag('P'))
        return G(42, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<MoveToMeshCoordinate> {

        override fun head(): GParameterWord<*> {
            return G(42).head
        }

        override fun decodeParams(tokens: List<GToken>): MoveToMeshCoordinate {
            return MoveToMeshCoordinate(
                pos = tokens.decimalOf('I'),
                j = tokens.decimalOf('J'),
                rate = tokens.decimalOf('F'),
                p = tokens.hasWord('P'),
            )
        }
    }
}
