package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M605 S<value> [X<value>] [R<value>] [P<value>] [E<value>]
 *
 * Multi Nozzle Mode (control).
 *
 * Marlin documents `S` as required; every property here still defaults to
 * absent, so that every command class is constructible bare.
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(MultiNozzleMode(s = 1).encode())   // M605 S1
 * MultiNozzleMode.decode(GTokenizer.parse("M605 S1").toList())   // MultiNozzleMode(M605 S1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property s `S` (required)
 * @property x `X`
 * @property r `R`
 * @property p `P`
 * @property e `E`
 * @see <a href="https://marlinfw.org/docs/gcode/M605.html">MarlinFirmare M605 doc</a>
 */
data class MultiNozzleMode(
    val s: Int? = null,
    val x: BigDecimal? = null,
    val r: Int? = null,
    val p: Int? = null,
    val e: Int? = null,
) : GRq<MultiNozzleMode> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(5)
        if (s != null) words.add(word('S', s))
        if (x != null) words.add(word('X', x.toPlainString()))
        if (r != null) words.add(word('R', r))
        if (p != null) words.add(word('P', p))
        if (e != null) words.add(word('E', e))
        return M(605, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<MultiNozzleMode> {

        override fun head(): GParameterWord<*> {
            return M(605).head
        }

        override fun decodeParams(tokens: List<GToken>): MultiNozzleMode {
            return MultiNozzleMode(
                s = tokens.intOf('S'),
                x = tokens.decimalOf('X'),
                r = tokens.intOf('R'),
                p = tokens.intOf('P'),
                e = tokens.intOf('E'),
            )
        }
    }
}
