package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.flag
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.hasWord
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M592 [A<coeff>] [B<coeff>] [C<coeff>] [S]
 *
 * Nonlinear Extrusion Control (motion).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(NonlinearExtrusionControl(coeff = BigDecimal("1.5")).encode())   // M592 A1.5
 * NonlinearExtrusionControl.decode(GTokenizer.parse("M592 A1.5").toList())   // NonlinearExtrusionControl(M592 A1.5)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property coeff `A` - coeff
 * @property b `B` - coeff
 * @property c `C` - coeff
 * @property s `S`
 * @see <a href="https://marlinfw.org/docs/gcode/M592.html">MarlinFirmare M592 doc</a>
 */
data class NonlinearExtrusionControl(
    val coeff: BigDecimal? = null,
    val b: BigDecimal? = null,
    val c: BigDecimal? = null,
    val s: Boolean = false,
) : GRq<NonlinearExtrusionControl> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(4)
        if (coeff != null) words.add(word('A', coeff.toPlainString()))
        if (b != null) words.add(word('B', b.toPlainString()))
        if (c != null) words.add(word('C', c.toPlainString()))
        if (s) words.add(flag('S'))
        return M(592, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<NonlinearExtrusionControl> {

        override fun head(): GParameterWord<*> {
            return M(592).head
        }

        override fun decodeParams(tokens: List<GToken>): NonlinearExtrusionControl {
            return NonlinearExtrusionControl(
                coeff = tokens.decimalOf('A'),
                b = tokens.decimalOf('B'),
                c = tokens.decimalOf('C'),
                s = tokens.hasWord('S'),
            )
        }
    }
}
