package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.G
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * G27 [P<value>]
 *
 * Park toolhead (nozzle).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(ParkToolhead(p = 1).encode())   // G27 P1
 * ParkToolhead.decode(GTokenizer.parse("G27 P1").toList())   // ParkToolhead(G27 P1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property p `P`
 * @see <a href="https://marlinfw.org/docs/gcode/G27.html">MarlinFirmare G27 doc</a>
 */
data class ParkToolhead(
    val p: Int? = null,
) : GRq<ParkToolhead> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(1)
        if (p != null) words.add(word('P', p))
        return G(27, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<ParkToolhead> {

        override fun head(): GParameterWord<*> {
            return G(27).head
        }

        override fun decodeParams(tokens: List<GToken>): ParkToolhead {
            return ParkToolhead(
                p = tokens.intOf('P'),
            )
        }
    }
}
