package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.boolOf
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M125 [L<linear>] [X<linear>] [Y<linear>] [Z<linear>] [P<value>]
 *
 * Park Head (nozzle).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(ParkHead(linear = BigDecimal("1.5")).encode())   // M125 L1.5
 * ParkHead.decode(GTokenizer.parse("M125 L1.5").toList())   // ParkHead(M125 L1.5)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property linear `L` - linear
 * @property x `X` - linear
 * @property y `Y` - linear
 * @property z `Z` - linear
 * @property p `P`
 * @see <a href="https://marlinfw.org/docs/gcode/M125.html">MarlinFirmare M125 doc</a>
 */
data class ParkHead(
    val linear: BigDecimal? = null,
    val x: BigDecimal? = null,
    val y: BigDecimal? = null,
    val z: BigDecimal? = null,
    val p: Boolean? = null,
) : GRq<ParkHead> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(5)
        if (linear != null) words.add(word('L', linear.toPlainString()))
        if (x != null) words.add(word('X', x.toPlainString()))
        if (y != null) words.add(word('Y', y.toPlainString()))
        if (z != null) words.add(word('Z', z.toPlainString()))
        if (p != null) words.add(word('P', if (p) 1 else 0))
        return M(125, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<ParkHead> {

        override fun head(): GParameterWord<*> {
            return M(125).head
        }

        override fun decodeParams(tokens: List<GToken>): ParkHead {
            return ParkHead(
                linear = tokens.decimalOf('L'),
                x = tokens.decimalOf('X'),
                y = tokens.decimalOf('Y'),
                z = tokens.decimalOf('Z'),
                p = tokens.boolOf('P'),
            )
        }
    }
}
