package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M25
 *
 * Pause SD print (sdcard).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(PauseSDPrint().encode())   // M25
 * PauseSDPrint.decode(GTokenizer.parse("M25").toList())   // PauseSDPrint(M25)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @see <a href="https://marlinfw.org/docs/gcode/M25.html">MarlinFirmare M25 doc</a>
 */
class PauseSDPrint : GRq<PauseSDPrint> {

    override fun encode(): GCommand {
        return M(25)
    }

    override fun equals(other: Any?): Boolean {
        return other is PauseSDPrint
    }

    override fun hashCode(): Int {
        return 726375
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<PauseSDPrint> {

        override fun head(): GParameterWord<*> {
            return M(25).head
        }

        override fun decodeParams(tokens: List<GToken>): PauseSDPrint {
            return PauseSDPrint()
        }
    }
}
