package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.flag
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.boolOf
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.hasWord
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M303 [E<index>] [C<count>] [S<temp>] [U<value>] [D]
 *
 * PID autotune (thermal).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(PIDAutotune(index = 1).encode())   // M303 E1
 * PIDAutotune.decode(GTokenizer.parse("M303 E1").toList())   // PIDAutotune(M303 E1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property index `E` - index
 * @property count `C` - count
 * @property temp `S` - temp
 * @property u `U`
 * @property d `D`
 * @see <a href="https://marlinfw.org/docs/gcode/M303.html">MarlinFirmare M303 doc</a>
 */
data class PIDAutotune(
    val index: Int? = null,
    val count: Int? = null,
    val temp: BigDecimal? = null,
    val u: Boolean? = null,
    val d: Boolean = false,
) : GRq<PIDAutotune> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(5)
        if (index != null) words.add(word('E', index))
        if (count != null) words.add(word('C', count))
        if (temp != null) words.add(word('S', temp.toPlainString()))
        if (u != null) words.add(word('U', if (u) 1 else 0))
        if (d) words.add(flag('D'))
        return M(303, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<PIDAutotune> {

        override fun head(): GParameterWord<*> {
            return M(303).head
        }

        override fun decodeParams(tokens: List<GToken>): PIDAutotune {
            return PIDAutotune(
                index = tokens.intOf('E'),
                count = tokens.intOf('C'),
                temp = tokens.decimalOf('S'),
                u = tokens.boolOf('U'),
                d = tokens.hasWord('D'),
            )
        }
    }
}
