package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.flag
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.boolOf
import org.qw3rtrun.p3d.g.marlin.hasWord
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M43 [P<pin>] [W] [E<value>] [T] [S] [I]
 *
 * Pins Debugging (debug).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(PinsDebugging(pin = 1).encode())   // M43 P1
 * PinsDebugging.decode(GTokenizer.parse("M43 P1").toList())   // PinsDebugging(M43 P1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property pin `P` - pin
 * @property w `W`
 * @property e `E`
 * @property t `T`
 * @property s `S`
 * @property i `I`
 * @see <a href="https://marlinfw.org/docs/gcode/M43.html">MarlinFirmare M43 doc</a>
 */
data class PinsDebugging(
    val pin: Int? = null,
    val w: Boolean = false,
    val e: Boolean? = null,
    val t: Boolean = false,
    val s: Boolean = false,
    val i: Boolean = false,
) : GRq<PinsDebugging> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(6)
        if (pin != null) words.add(word('P', pin))
        if (w) words.add(flag('W'))
        if (e != null) words.add(word('E', if (e) 1 else 0))
        if (t) words.add(flag('T'))
        if (s) words.add(flag('S'))
        if (i) words.add(flag('I'))
        return M(43, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<PinsDebugging> {

        override fun head(): GParameterWord<*> {
            return M(43).head
        }

        override fun decodeParams(tokens: List<GToken>): PinsDebugging {
            return PinsDebugging(
                pin = tokens.intOf('P'),
                w = tokens.hasWord('W'),
                e = tokens.boolOf('E'),
                t = tokens.hasWord('T'),
                s = tokens.hasWord('S'),
                i = tokens.hasWord('I'),
            )
        }
    }
}
