package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.boolOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M430 [I<value>] [V<value>] [W<value>]
 *
 * Power Monitor (thermal).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(PowerMonitor(i = true).encode())   // M430 I1
 * PowerMonitor.decode(GTokenizer.parse("M430 I1").toList())   // PowerMonitor(M430 I1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property i `I`
 * @property v `V`
 * @property w `W`
 * @see <a href="https://marlinfw.org/docs/gcode/M430.html">MarlinFirmare M430 doc</a>
 */
data class PowerMonitor(
    val i: Boolean? = null,
    val v: Boolean? = null,
    val w: Boolean? = null,
) : GRq<PowerMonitor> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(3)
        if (i != null) words.add(word('I', if (i) 1 else 0))
        if (v != null) words.add(word('V', if (v) 1 else 0))
        if (w != null) words.add(word('W', if (w) 1 else 0))
        return M(430, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<PowerMonitor> {

        override fun head(): GParameterWord<*> {
            return M(430).head
        }

        override fun decodeParams(tokens: List<GToken>): PowerMonitor {
            return PowerMonitor(
                i = tokens.boolOf('I'),
                v = tokens.boolOf('V'),
                w = tokens.boolOf('W'),
            )
        }
    }
}
