package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.flag
import org.qw3rtrun.p3d.g.marlin.hasWord
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M80 [S]
 *
 * Power On (control).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(PowerOn(s = true).encode())   // M80 S
 * PowerOn.decode(GTokenizer.parse("M80 S").toList())   // PowerOn(M80 S)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property s `S`
 * @see <a href="https://marlinfw.org/docs/gcode/M80.html">MarlinFirmare M80 doc</a>
 */
data class PowerOn(
    val s: Boolean = false,
) : GRq<PowerOn> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(1)
        if (s) words.add(flag('S'))
        return M(80, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<PowerOn> {

        override fun head(): GParameterWord<*> {
            return M(80).head
        }

        override fun decodeParams(tokens: List<GToken>): PowerOn {
            return PowerOn(
                s = tokens.hasWord('S'),
            )
        }
    }
}
