package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M201 [X<accel>] [Y<accel>] [Z<accel>] [E<accel>] [T<index>] [F<value>] [S<percent>]
 *
 * Print / Travel Move Limits (motion).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(PrintTravelMoveLimits(accel = BigDecimal("1.5")).encode())   // M201 X1.5
 * PrintTravelMoveLimits.decode(GTokenizer.parse("M201 X1.5").toList())   // PrintTravelMoveLimits(M201 X1.5)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property accel `X` - accel
 * @property y `Y` - accel
 * @property z `Z` - accel
 * @property e `E` - accel
 * @property index `T` - index
 * @property f `F`
 * @property percent `S` - percent
 * @see <a href="https://marlinfw.org/docs/gcode/M201.html">MarlinFirmare M201 doc</a>
 */
data class PrintTravelMoveLimits(
    val accel: BigDecimal? = null,
    val y: BigDecimal? = null,
    val z: BigDecimal? = null,
    val e: BigDecimal? = null,
    val index: Int? = null,
    val f: Int? = null,
    val percent: BigDecimal? = null,
) : GRq<PrintTravelMoveLimits> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(7)
        if (accel != null) words.add(word('X', accel.toPlainString()))
        if (y != null) words.add(word('Y', y.toPlainString()))
        if (z != null) words.add(word('Z', z.toPlainString()))
        if (e != null) words.add(word('E', e.toPlainString()))
        if (index != null) words.add(word('T', index))
        if (f != null) words.add(word('F', f))
        if (percent != null) words.add(word('S', percent.toPlainString()))
        return M(201, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<PrintTravelMoveLimits> {

        override fun head(): GParameterWord<*> {
            return M(201).head
        }

        override fun decodeParams(tokens: List<GToken>): PrintTravelMoveLimits {
            return PrintTravelMoveLimits(
                accel = tokens.decimalOf('X'),
                y = tokens.decimalOf('Y'),
                z = tokens.decimalOf('Z'),
                e = tokens.decimalOf('E'),
                index = tokens.intOf('T'),
                f = tokens.intOf('F'),
                percent = tokens.decimalOf('S'),
            )
        }
    }
}
