package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.boolOf
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M48 [C<value>] [E<engage>] [L<legs>] [P<count>] [S<value>] [V<level>] [X<pos>] [Y<pos>]
 *
 * Probe Repeatability Test (calibration).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(ProbeRepeatabilityTest(c = true).encode())   // M48 C1
 * ProbeRepeatabilityTest.decode(GTokenizer.parse("M48 C1").toList())   // ProbeRepeatabilityTest(M48 C1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property c `C`
 * @property engage `E` - engage
 * @property legs `L` - legs
 * @property count `P` - count
 * @property s `S`
 * @property level `V` - level
 * @property pos `X` - pos
 * @property y `Y` - pos
 * @see <a href="https://marlinfw.org/docs/gcode/M48.html">MarlinFirmare M48 doc</a>
 */
data class ProbeRepeatabilityTest(
    val c: Boolean? = null,
    val engage: Boolean? = null,
    val legs: Int? = null,
    val count: Int? = null,
    val s: Int? = null,
    val level: Int? = null,
    val pos: BigDecimal? = null,
    val y: BigDecimal? = null,
) : GRq<ProbeRepeatabilityTest> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(8)
        if (c != null) words.add(word('C', if (c) 1 else 0))
        if (engage != null) words.add(word('E', if (engage) 1 else 0))
        if (legs != null) words.add(word('L', legs))
        if (count != null) words.add(word('P', count))
        if (s != null) words.add(word('S', s))
        if (level != null) words.add(word('V', level))
        if (pos != null) words.add(word('X', pos.toPlainString()))
        if (y != null) words.add(word('Y', y.toPlainString()))
        return M(48, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<ProbeRepeatabilityTest> {

        override fun head(): GParameterWord<*> {
            return M(48).head
        }

        override fun decodeParams(tokens: List<GToken>): ProbeRepeatabilityTest {
            return ProbeRepeatabilityTest(
                c = tokens.boolOf('C'),
                engage = tokens.boolOf('E'),
                legs = tokens.intOf('L'),
                count = tokens.intOf('P'),
                s = tokens.intOf('S'),
                level = tokens.intOf('V'),
                pos = tokens.decimalOf('X'),
                y = tokens.decimalOf('Y'),
            )
        }
    }
}
