package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.G
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * G38.2 [X<pos>] [Y<pos>] [Z<pos>] [F<rate>]
 *
 * Probe target (calibration).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(ProbeTargetG38_2(pos = BigDecimal("1.5")).encode())   // G38.2 X1.5
 * ProbeTargetG38_2.decode(GTokenizer.parse("G38.2 X1.5").toList())   // ProbeTargetG38_2(G38.2 X1.5)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property pos `X` - pos
 * @property y `Y` - pos
 * @property z `Z` - pos
 * @property rate `F` - rate
 * @see <a href="https://marlinfw.org/docs/gcode/G38-2.html">MarlinFirmare G38.2 doc</a>
 */
data class ProbeTargetG38_2(
    val pos: BigDecimal? = null,
    val y: BigDecimal? = null,
    val z: BigDecimal? = null,
    val rate: BigDecimal? = null,
) : GRq<ProbeTargetG38_2> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(4)
        if (pos != null) words.add(word('X', pos.toPlainString()))
        if (y != null) words.add(word('Y', y.toPlainString()))
        if (z != null) words.add(word('Z', z.toPlainString()))
        if (rate != null) words.add(word('F', rate.toPlainString()))
        return G("38.2", *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<ProbeTargetG38_2> {

        override fun head(): GParameterWord<*> {
            return G("38.2").head
        }

        override fun decodeParams(tokens: List<GToken>): ProbeTargetG38_2 {
            return ProbeTargetG38_2(
                pos = tokens.decimalOf('X'),
                y = tokens.decimalOf('Y'),
                z = tokens.decimalOf('Z'),
                rate = tokens.decimalOf('F'),
            )
        }
    }
}
