package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.flag
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.hasWord
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M871 [V<value>] [I<index>] [B] [P] [E] [R]
 *
 * Probe temperature config (calibration).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(ProbeTemperatureConfig(value = 1).encode())   // M871 V1
 * ProbeTemperatureConfig.decode(GTokenizer.parse("M871 V1").toList())   // ProbeTemperatureConfig(M871 V1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property value `V` - value
 * @property index `I` - index
 * @property b `B`
 * @property p `P`
 * @property e `E`
 * @property r `R`
 * @see <a href="https://marlinfw.org/docs/gcode/M871.html">MarlinFirmare M871 doc</a>
 */
data class ProbeTemperatureConfig(
    val value: Int? = null,
    val index: Int? = null,
    val b: Boolean = false,
    val p: Boolean = false,
    val e: Boolean = false,
    val r: Boolean = false,
) : GRq<ProbeTemperatureConfig> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(6)
        if (value != null) words.add(word('V', value))
        if (index != null) words.add(word('I', index))
        if (b) words.add(flag('B'))
        if (p) words.add(flag('P'))
        if (e) words.add(flag('E'))
        if (r) words.add(flag('R'))
        return M(871, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<ProbeTemperatureConfig> {

        override fun head(): GParameterWord<*> {
            return M(871).head
        }

        override fun decodeParams(tokens: List<GToken>): ProbeTemperatureConfig {
            return ProbeTemperatureConfig(
                value = tokens.intOf('V'),
                index = tokens.intOf('I'),
                b = tokens.hasWord('B'),
                p = tokens.hasWord('P'),
                e = tokens.hasWord('E'),
                r = tokens.hasWord('R'),
            )
        }
    }
}
