package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.dsl.G
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * G91
 *
 * Relative Positioning (units).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(RelativePositioning().encode())   // G91
 * RelativePositioning.decode(GTokenizer.parse("G91").toList())   // RelativePositioning(G91)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @see <a href="https://marlinfw.org/docs/gcode/G91.html">MarlinFirmare G91 doc</a>
 */
class RelativePositioning : GRq<RelativePositioning> {

    override fun encode(): GCommand {
        return G(91)
    }

    override fun equals(other: Any?): Boolean {
        return other is RelativePositioning
    }

    override fun hashCode(): Int {
        return 667015
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<RelativePositioning> {

        override fun head(): GParameterWord<*> {
            return G(91).head
        }

        override fun decodeParams(tokens: List<GToken>): RelativePositioning {
            return RelativePositioning()
        }
    }
}
