package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.flag
import org.qw3rtrun.p3d.g.marlin.hasWord
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M503 [S] [C]
 *
 * Report Settings (eeprom).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(ReportSettings(s = true).encode())   // M503 S
 * ReportSettings.decode(GTokenizer.parse("M503 S").toList())   // ReportSettings(M503 S)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property s `S`
 * @property c `C`
 * @see <a href="https://marlinfw.org/docs/gcode/M503.html">MarlinFirmare M503 doc</a>
 */
data class ReportSettings(
    val s: Boolean = false,
    val c: Boolean = false,
) : GRq<ReportSettings> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(2)
        if (s) words.add(flag('S'))
        if (c) words.add(flag('C'))
        return M(503, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<ReportSettings> {

        override fun head(): GParameterWord<*> {
            return M(503).head
        }

        override fun decodeParams(tokens: List<GToken>): ReportSettings {
            return ReportSettings(
                s = tokens.hasWord('S'),
                c = tokens.hasWord('C'),
            )
        }
    }
}
