package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.flag
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.hasWord
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M105 [R] [T<index>]
 *
 * Report Temperatures (thermal).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(ReportHotendTemperature(r = true).encode())   // M105 R
 * ReportHotendTemperature.decode(GTokenizer.parse("M105 R").toList())   // ReportHotendTemperature(M105 R)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property r `R`
 * @property index `T` - index
 * @see <a href="https://marlinfw.org/docs/gcode/M105.html">MarlinFirmare M105 doc</a>
 */
data class ReportHotendTemperature(
    val r: Boolean = false,
    val index: Int? = null,
) : GRq<ReportHotendTemperature> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(2)
        if (r) words.add(flag('R'))
        if (index != null) words.add(word('T', index))
        return M(105, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<ReportHotendTemperature> {

        override fun head(): GParameterWord<*> {
            return M(105).head
        }

        override fun decodeParams(tokens: List<GToken>): ReportHotendTemperature {
            return ReportHotendTemperature(
                r = tokens.hasWord('R'),
                index = tokens.intOf('T'),
            )
        }
    }
}
