package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.flag
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.hasWord
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M27 [S<seconds>] [C]
 *
 * Report SD print status (sdcard).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(ReportSDPrintStatus(seconds = 1).encode())   // M27 S1
 * ReportSDPrintStatus.decode(GTokenizer.parse("M27 S1").toList())   // ReportSDPrintStatus(M27 S1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property seconds `S` - seconds
 * @property c `C`
 * @see <a href="https://marlinfw.org/docs/gcode/M27.html">MarlinFirmare M27 doc</a>
 */
data class ReportSDPrintStatus(
    val seconds: Int? = null,
    val c: Boolean = false,
) : GRq<ReportSDPrintStatus> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(2)
        if (seconds != null) words.add(word('S', seconds))
        if (c) words.add(flag('C'))
        return M(27, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<ReportSDPrintStatus> {

        override fun head(): GParameterWord<*> {
            return M(27).head
        }

        override fun decodeParams(tokens: List<GToken>): ReportSDPrintStatus {
            return ReportSDPrintStatus(
                seconds = tokens.intOf('S'),
                c = tokens.hasWord('C'),
            )
        }
    }
}
