package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M31
 *
 * Report Print Time (printjob).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(ReportPrintTime().encode())   // M31
 * ReportPrintTime.decode(GTokenizer.parse("M31").toList())   // ReportPrintTime(M31)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @see <a href="https://marlinfw.org/docs/gcode/M31.html">MarlinFirmare M31 doc</a>
 */
class ReportPrintTime : GRq<ReportPrintTime> {

    override fun encode(): GCommand {
        return M(31)
    }

    override fun equals(other: Any?): Boolean {
        return other is ReportPrintTime
    }

    override fun hashCode(): Int {
        return 867522
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<ReportPrintTime> {

        override fun head(): GParameterWord<*> {
            return M(31).head
        }

        override fun decodeParams(tokens: List<GToken>): ReportPrintTime {
            return ReportPrintTime()
        }
    }
}
