package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M501
 *
 * Restore Settings (eeprom).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(RestoreSettings().encode())   // M501
 * RestoreSettings.decode(GTokenizer.parse("M501").toList())   // RestoreSettings(M501)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @see <a href="https://marlinfw.org/docs/gcode/M501.html">MarlinFirmare M501 doc</a>
 */
class RestoreSettings : GRq<RestoreSettings> {

    override fun encode(): GCommand {
        return M(501)
    }

    override fun equals(other: Any?): Boolean {
        return other is RestoreSettings
    }

    override fun hashCode(): Int {
        return 848523
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<RestoreSettings> {

        override fun head(): GParameterWord<*> {
            return M(501).head
        }

        override fun decodeParams(tokens: List<GToken>): RestoreSettings {
            return RestoreSettings()
        }
    }
}
