package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M500
 *
 * Save Settings (eeprom).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(SaveSettings().encode())   // M500
 * SaveSettings.decode(GTokenizer.parse("M500").toList())   // SaveSettings(M500)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @see <a href="https://marlinfw.org/docs/gcode/M500.html">MarlinFirmare M500 doc</a>
 */
class SaveSettings : GRq<SaveSettings> {

    override fun encode(): GCommand {
        return M(500)
    }

    override fun equals(other: Any?): Boolean {
        return other is SaveSettings
    }

    override fun hashCode(): Int {
        return 359397
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<SaveSettings> {

        override fun head(): GParameterWord<*> {
            return M(500).head
        }

        override fun decodeParams(tokens: List<GToken>): SaveSettings {
            return SaveSettings()
        }
    }
}
