package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M360
 *
 * SCARA Theta A (control).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(SCARAThetaA().encode())   // M360
 * SCARAThetaA.decode(GTokenizer.parse("M360").toList())   // SCARAThetaA(M360)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @see <a href="https://marlinfw.org/docs/gcode/M360.html">MarlinFirmare M360 doc</a>
 */
class SCARAThetaA : GRq<SCARAThetaA> {

    override fun encode(): GCommand {
        return M(360)
    }

    override fun equals(other: Any?): Boolean {
        return other is SCARAThetaA
    }

    override fun hashCode(): Int {
        return 850344
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<SCARAThetaA> {

        override fun head(): GParameterWord<*> {
            return M(360).head
        }

        override fun decodeParams(tokens: List<GToken>): SCARAThetaA {
            return SCARAThetaA()
        }
    }
}
