package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M34 [S<value>] [F<value>]
 *
 * SDCard Sorting (sdcard).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(SDCardSorting(s = BigDecimal("1.5")).encode())   // M34 S1.5
 * SDCardSorting.decode(GTokenizer.parse("M34 S1.5").toList())   // SDCardSorting(M34 S1.5)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property s `S`
 * @property f `F`
 * @see <a href="https://marlinfw.org/docs/gcode/M34.html">MarlinFirmare M34 doc</a>
 */
data class SDCardSorting(
    val s: BigDecimal? = null,
    val f: Int? = null,
) : GRq<SDCardSorting> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(2)
        if (s != null) words.add(word('S', s.toPlainString()))
        if (f != null) words.add(word('F', f))
        return M(34, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<SDCardSorting> {

        override fun head(): GParameterWord<*> {
            return M(34).head
        }

        override fun decodeParams(tokens: List<GToken>): SDCardSorting {
            return SDCardSorting(
                s = tokens.decimalOf('S'),
                f = tokens.intOf('F'),
            )
        }
    }
}
