package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.dsl.G
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * G56
 *
 * Select Workspace (geometry).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(SelectWorkspaceG56().encode())   // G56
 * SelectWorkspaceG56.decode(GTokenizer.parse("G56").toList())   // SelectWorkspaceG56(G56)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @see <a href="https://marlinfw.org/docs/gcode/G56.html">MarlinFirmare G56 doc</a>
 */
class SelectWorkspaceG56 : GRq<SelectWorkspaceG56> {

    override fun encode(): GCommand {
        return G(56)
    }

    override fun equals(other: Any?): Boolean {
        return other is SelectWorkspaceG56
    }

    override fun hashCode(): Int {
        return 878290
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<SelectWorkspaceG56> {

        override fun head(): GParameterWord<*> {
            return G(56).head
        }

        override fun decodeParams(tokens: List<GToken>): SelectWorkspaceG56 {
            return SelectWorkspaceG56()
        }
    }
}
