package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.dsl.G
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * G59.3
 *
 * Select Workspace (geometry).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(SelectWorkspaceG59_3().encode())   // G59.3
 * SelectWorkspaceG59_3.decode(GTokenizer.parse("G59.3").toList())   // SelectWorkspaceG59_3(G59.3)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @see <a href="https://marlinfw.org/docs/gcode/G59-3.html">MarlinFirmare G59.3 doc</a>
 */
class SelectWorkspaceG59_3 : GRq<SelectWorkspaceG59_3> {

    override fun encode(): GCommand {
        return G("59.3")
    }

    override fun equals(other: Any?): Boolean {
        return other is SelectWorkspaceG59_3
    }

    override fun hashCode(): Int {
        return 622035
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<SelectWorkspaceG59_3> {

        override fun head(): GParameterWord<*> {
            return G("59.3").head
        }

        override fun decodeParams(tokens: List<GToken>): SelectWorkspaceG59_3 {
            return SelectWorkspaceG59_3()
        }
    }
}
