package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.T
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.boolOf
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * T5 [F<feedrate>] [S<value>]
 *
 * Select or Report Tool (control).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(SelectOrReportToolT5(feedrate = BigDecimal("1.5")).encode())   // T5 F1.5
 * SelectOrReportToolT5.decode(GTokenizer.parse("T5 F1.5").toList())   // SelectOrReportToolT5(T5 F1.5)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property feedrate `F` - feedrate
 * @property s `S`
 * @see <a href="https://marlinfw.org/docs/gcode/T5.html">MarlinFirmare T5 doc</a>
 */
data class SelectOrReportToolT5(
    val feedrate: BigDecimal? = null,
    val s: Boolean? = null,
) : GRq<SelectOrReportToolT5> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(2)
        if (feedrate != null) words.add(word('F', feedrate.toPlainString()))
        if (s != null) words.add(word('S', if (s) 1 else 0))
        return T(5, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<SelectOrReportToolT5> {

        override fun head(): GParameterWord<*> {
            return T(5).head
        }

        override fun decodeParams(tokens: List<GToken>): SelectOrReportToolT5 {
            return SelectOrReportToolT5(
                feedrate = tokens.decimalOf('F'),
                s = tokens.boolOf('S'),
            )
        }
    }
}
