package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M92 [X<steps>] [Y<steps>] [Z<steps>] [A<steps>] [B<steps>] [C<steps>] [U<steps>] [V<steps>] [W<steps>] [E<steps>] [T<index>]
 *
 * Set Axis Steps-per-unit (motion).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(SetAxisStepsPerUnit(steps = BigDecimal("1.5")).encode())   // M92 X1.5
 * SetAxisStepsPerUnit.decode(GTokenizer.parse("M92 X1.5").toList())   // SetAxisStepsPerUnit(M92 X1.5)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property steps `X` - steps
 * @property y `Y` - steps
 * @property z `Z` - steps
 * @property a `A` - steps
 * @property b `B` - steps
 * @property c `C` - steps
 * @property u `U` - steps
 * @property v `V` - steps
 * @property w `W` - steps
 * @property e `E` - steps
 * @property index `T` - index
 * @see <a href="https://marlinfw.org/docs/gcode/M92.html">MarlinFirmare M92 doc</a>
 */
data class SetAxisStepsPerUnit(
    val steps: BigDecimal? = null,
    val y: BigDecimal? = null,
    val z: BigDecimal? = null,
    val a: BigDecimal? = null,
    val b: BigDecimal? = null,
    val c: BigDecimal? = null,
    val u: BigDecimal? = null,
    val v: BigDecimal? = null,
    val w: BigDecimal? = null,
    val e: BigDecimal? = null,
    val index: Int? = null,
) : GRq<SetAxisStepsPerUnit> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(11)
        if (steps != null) words.add(word('X', steps.toPlainString()))
        if (y != null) words.add(word('Y', y.toPlainString()))
        if (z != null) words.add(word('Z', z.toPlainString()))
        if (a != null) words.add(word('A', a.toPlainString()))
        if (b != null) words.add(word('B', b.toPlainString()))
        if (c != null) words.add(word('C', c.toPlainString()))
        if (u != null) words.add(word('U', u.toPlainString()))
        if (v != null) words.add(word('V', v.toPlainString()))
        if (w != null) words.add(word('W', w.toPlainString()))
        if (e != null) words.add(word('E', e.toPlainString()))
        if (index != null) words.add(word('T', index))
        return M(92, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<SetAxisStepsPerUnit> {

        override fun head(): GParameterWord<*> {
            return M(92).head
        }

        override fun decodeParams(tokens: List<GToken>): SetAxisStepsPerUnit {
            return SetAxisStepsPerUnit(
                steps = tokens.decimalOf('X'),
                y = tokens.decimalOf('Y'),
                z = tokens.decimalOf('Z'),
                a = tokens.decimalOf('A'),
                b = tokens.decimalOf('B'),
                c = tokens.decimalOf('C'),
                u = tokens.decimalOf('U'),
                v = tokens.decimalOf('V'),
                w = tokens.decimalOf('W'),
                e = tokens.decimalOf('E'),
                index = tokens.intOf('T'),
            )
        }
    }
}
