package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M205 [X<jerk>] [Y<jerk>] [Z<jerk>] [E<jerk>] [B<value>] [S<value>] [T<value>] [J<deviation>]
 *
 * Set Advanced Settings (motion).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(SetAdvancedSettings(jerk = BigDecimal("1.5")).encode())   // M205 X1.5
 * SetAdvancedSettings.decode(GTokenizer.parse("M205 X1.5").toList())   // SetAdvancedSettings(M205 X1.5)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property jerk `X` - jerk
 * @property y `Y` - jerk
 * @property z `Z` - jerk
 * @property e `E` - jerk
 * @property b `B`
 * @property s `S`
 * @property t `T`
 * @property deviation `J` - deviation
 * @see <a href="https://marlinfw.org/docs/gcode/M205.html">MarlinFirmare M205 doc</a>
 */
data class SetAdvancedSettings(
    val jerk: BigDecimal? = null,
    val y: BigDecimal? = null,
    val z: BigDecimal? = null,
    val e: BigDecimal? = null,
    val b: Int? = null,
    val s: BigDecimal? = null,
    val t: BigDecimal? = null,
    val deviation: BigDecimal? = null,
) : GRq<SetAdvancedSettings> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(8)
        if (jerk != null) words.add(word('X', jerk.toPlainString()))
        if (y != null) words.add(word('Y', y.toPlainString()))
        if (z != null) words.add(word('Z', z.toPlainString()))
        if (e != null) words.add(word('E', e.toPlainString()))
        if (b != null) words.add(word('B', b))
        if (s != null) words.add(word('S', s.toPlainString()))
        if (t != null) words.add(word('T', t.toPlainString()))
        if (deviation != null) words.add(word('J', deviation.toPlainString()))
        return M(205, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<SetAdvancedSettings> {

        override fun head(): GParameterWord<*> {
            return M(205).head
        }

        override fun decodeParams(tokens: List<GToken>): SetAdvancedSettings {
            return SetAdvancedSettings(
                jerk = tokens.decimalOf('X'),
                y = tokens.decimalOf('Y'),
                z = tokens.decimalOf('Z'),
                e = tokens.decimalOf('E'),
                b = tokens.intOf('B'),
                s = tokens.decimalOf('S'),
                t = tokens.decimalOf('T'),
                deviation = tokens.decimalOf('J'),
            )
        }
    }
}
