package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M304 [P<value>] [I<value>] [D<value>]
 *
 * Set Bed PID (thermal).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(SetBedPID(value = BigDecimal("1.5")).encode())   // M304 P1.5
 * SetBedPID.decode(GTokenizer.parse("M304 P1.5").toList())   // SetBedPID(M304 P1.5)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property value `P` - value
 * @property i `I` - value
 * @property d `D` - value
 * @see <a href="https://marlinfw.org/docs/gcode/M304.html">MarlinFirmare M304 doc</a>
 */
data class SetBedPID(
    val value: BigDecimal? = null,
    val i: BigDecimal? = null,
    val d: BigDecimal? = null,
) : GRq<SetBedPID> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(3)
        if (value != null) words.add(word('P', value.toPlainString()))
        if (i != null) words.add(word('I', i.toPlainString()))
        if (d != null) words.add(word('D', d.toPlainString()))
        return M(304, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<SetBedPID> {

        override fun head(): GParameterWord<*> {
            return M(304).head
        }

        override fun decodeParams(tokens: List<GToken>): SetBedPID {
            return SetBedPID(
                value = tokens.decimalOf('P'),
                i = tokens.decimalOf('I'),
                d = tokens.decimalOf('D'),
            )
        }
    }
}
