package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M221 S<percent> [T<index>]
 *
 * Set Flow Percentage (motion).
 *
 * Marlin documents `S` as required; every property here still defaults to
 * absent, so that every command class is constructible bare.
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(SetFlowPercentage(percent = 1).encode())   // M221 S1
 * SetFlowPercentage.decode(GTokenizer.parse("M221 S1").toList())   // SetFlowPercentage(M221 S1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property percent `S` - percent (required)
 * @property index `T` - index
 * @see <a href="https://marlinfw.org/docs/gcode/M221.html">MarlinFirmare M221 doc</a>
 */
data class SetFlowPercentage(
    val percent: Int? = null,
    val index: Int? = null,
) : GRq<SetFlowPercentage> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(2)
        if (percent != null) words.add(word('S', percent))
        if (index != null) words.add(word('T', index))
        return M(221, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<SetFlowPercentage> {

        override fun head(): GParameterWord<*> {
            return M(221).head
        }

        override fun decodeParams(tokens: List<GToken>): SetFlowPercentage {
            return SetFlowPercentage(
                percent = tokens.intOf('S'),
                index = tokens.intOf('T'),
            )
        }
    }
}
