package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M106 [I<index>] [S<speed>] [P<index>] [T<value>]
 *
 * Set Fan Speed (thermal).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(SetFanSpeed(index = 1).encode())   // M106 I1
 * SetFanSpeed.decode(GTokenizer.parse("M106 I1").toList())   // SetFanSpeed(M106 I1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property index `I` - index
 * @property speed `S` - speed
 * @property p `P` - index
 * @property t `T`
 * @see <a href="https://marlinfw.org/docs/gcode/M106.html">MarlinFirmare M106 doc</a>
 */
data class SetFanSpeed(
    val index: Int? = null,
    val speed: Int? = null,
    val p: Int? = null,
    val t: BigDecimal? = null,
) : GRq<SetFanSpeed> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(4)
        if (index != null) words.add(word('I', index))
        if (speed != null) words.add(word('S', speed))
        if (p != null) words.add(word('P', p))
        if (t != null) words.add(word('T', t.toPlainString()))
        return M(106, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<SetFanSpeed> {

        override fun head(): GParameterWord<*> {
            return M(106).head
        }

        override fun decodeParams(tokens: List<GToken>): SetFanSpeed {
            return SetFanSpeed(
                index = tokens.intOf('I'),
                speed = tokens.intOf('S'),
                p = tokens.intOf('P'),
                t = tokens.decimalOf('T'),
            )
        }
    }
}
