package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M104 [I<index>] [S<temp>] [F<factor>] [B<temp>] [T<index>]
 *
 * Set Hotend Temperature (thermal).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(SetHotendTemperature(index = 1).encode())   // M104 I1
 * SetHotendTemperature.decode(GTokenizer.parse("M104 I1").toList())   // SetHotendTemperature(M104 I1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property index `I` - index
 * @property temp `S` - temp
 * @property factor `F` - factor
 * @property b `B` - temp
 * @property t `T` - index
 * @see <a href="https://marlinfw.org/docs/gcode/M104.html">MarlinFirmare M104 doc</a>
 */
data class SetHotendTemperature(
    val index: Int? = null,
    val temp: BigDecimal? = null,
    val factor: BigDecimal? = null,
    val b: BigDecimal? = null,
    val t: Int? = null,
) : GRq<SetHotendTemperature> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(5)
        if (index != null) words.add(word('I', index))
        if (temp != null) words.add(word('S', temp.toPlainString()))
        if (factor != null) words.add(word('F', factor.toPlainString()))
        if (b != null) words.add(word('B', b.toPlainString()))
        if (t != null) words.add(word('T', t))
        return M(104, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<SetHotendTemperature> {

        override fun head(): GParameterWord<*> {
            return M(104).head
        }

        override fun decodeParams(tokens: List<GToken>): SetHotendTemperature {
            return SetHotendTemperature(
                index = tokens.intOf('I'),
                temp = tokens.decimalOf('S'),
                factor = tokens.decimalOf('F'),
                b = tokens.decimalOf('B'),
                t = tokens.intOf('T'),
            )
        }
    }
}
