package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M206 [P<offset>] [T<offset>] [X<offset>] [Y<offset>] [Z<offset>] [A<offset>] [B<offset>] [C<offset>] [U<offset>] [V<offset>] [W<offset>]
 *
 * Set Home Offsets (motion).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(SetHomeOffsets(offset = BigDecimal("1.5")).encode())   // M206 P1.5
 * SetHomeOffsets.decode(GTokenizer.parse("M206 P1.5").toList())   // SetHomeOffsets(M206 P1.5)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property offset `P` - offset
 * @property t `T` - offset
 * @property x `X` - offset
 * @property y `Y` - offset
 * @property z `Z` - offset
 * @property a `A` - offset
 * @property b `B` - offset
 * @property c `C` - offset
 * @property u `U` - offset
 * @property v `V` - offset
 * @property w `W` - offset
 * @see <a href="https://marlinfw.org/docs/gcode/M206.html">MarlinFirmare M206 doc</a>
 */
data class SetHomeOffsets(
    val offset: BigDecimal? = null,
    val t: BigDecimal? = null,
    val x: BigDecimal? = null,
    val y: BigDecimal? = null,
    val z: BigDecimal? = null,
    val a: BigDecimal? = null,
    val b: BigDecimal? = null,
    val c: BigDecimal? = null,
    val u: BigDecimal? = null,
    val v: BigDecimal? = null,
    val w: BigDecimal? = null,
) : GRq<SetHomeOffsets> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(11)
        if (offset != null) words.add(word('P', offset.toPlainString()))
        if (t != null) words.add(word('T', t.toPlainString()))
        if (x != null) words.add(word('X', x.toPlainString()))
        if (y != null) words.add(word('Y', y.toPlainString()))
        if (z != null) words.add(word('Z', z.toPlainString()))
        if (a != null) words.add(word('A', a.toPlainString()))
        if (b != null) words.add(word('B', b.toPlainString()))
        if (c != null) words.add(word('C', c.toPlainString()))
        if (u != null) words.add(word('U', u.toPlainString()))
        if (v != null) words.add(word('V', v.toPlainString()))
        if (w != null) words.add(word('W', w.toPlainString()))
        return M(206, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<SetHomeOffsets> {

        override fun head(): GParameterWord<*> {
            return M(206).head
        }

        override fun decodeParams(tokens: List<GToken>): SetHomeOffsets {
            return SetHomeOffsets(
                offset = tokens.decimalOf('P'),
                t = tokens.decimalOf('T'),
                x = tokens.decimalOf('X'),
                y = tokens.decimalOf('Y'),
                z = tokens.decimalOf('Z'),
                a = tokens.decimalOf('A'),
                b = tokens.decimalOf('B'),
                c = tokens.decimalOf('C'),
                u = tokens.decimalOf('U'),
                v = tokens.decimalOf('V'),
                w = tokens.decimalOf('W'),
            )
        }
    }
}
