package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M301 [E<index>] [P<value>] [I<value>] [D<value>] [C<value>] [L<value>] [F<value>]
 *
 * Set Hotend PID (thermal).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(SetHotendPID(index = 1).encode())   // M301 E1
 * SetHotendPID.decode(GTokenizer.parse("M301 E1").toList())   // SetHotendPID(M301 E1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property index `E` - index
 * @property value `P` - value
 * @property i `I` - value
 * @property d `D` - value
 * @property c `C` - value
 * @property l `L` - value
 * @property f `F` - value
 * @see <a href="https://marlinfw.org/docs/gcode/M301.html">MarlinFirmare M301 doc</a>
 */
data class SetHotendPID(
    val index: Int? = null,
    val value: BigDecimal? = null,
    val i: BigDecimal? = null,
    val d: BigDecimal? = null,
    val c: BigDecimal? = null,
    val l: BigDecimal? = null,
    val f: BigDecimal? = null,
) : GRq<SetHotendPID> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(7)
        if (index != null) words.add(word('E', index))
        if (value != null) words.add(word('P', value.toPlainString()))
        if (i != null) words.add(word('I', i.toPlainString()))
        if (d != null) words.add(word('D', d.toPlainString()))
        if (c != null) words.add(word('C', c.toPlainString()))
        if (l != null) words.add(word('L', l.toPlainString()))
        if (f != null) words.add(word('F', f.toPlainString()))
        return M(301, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<SetHotendPID> {

        override fun head(): GParameterWord<*> {
            return M(301).head
        }

        override fun decodeParams(tokens: List<GToken>): SetHotendPID {
            return SetHotendPID(
                index = tokens.intOf('E'),
                value = tokens.decimalOf('P'),
                i = tokens.decimalOf('I'),
                d = tokens.decimalOf('D'),
                c = tokens.decimalOf('C'),
                l = tokens.decimalOf('L'),
                f = tokens.decimalOf('F'),
            )
        }
    }
}
