package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M143 [S<temp>]
 *
 * Set Laser Cooler Temperature (thermal).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(SetLaserCoolerTemperature(temp = BigDecimal("1.5")).encode())   // M143 S1.5
 * SetLaserCoolerTemperature.decode(GTokenizer.parse("M143 S1.5").toList())   // SetLaserCoolerTemperature(M143 S1.5)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property temp `S` - temp
 * @see <a href="https://marlinfw.org/docs/gcode/M143.html">MarlinFirmare M143 doc</a>
 */
data class SetLaserCoolerTemperature(
    val temp: BigDecimal? = null,
) : GRq<SetLaserCoolerTemperature> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(1)
        if (temp != null) words.add(word('S', temp.toPlainString()))
        return M(143, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<SetLaserCoolerTemperature> {

        override fun head(): GParameterWord<*> {
            return M(143).head
        }

        override fun decodeParams(tokens: List<GToken>): SetLaserCoolerTemperature {
            return SetLaserCoolerTemperature(
                temp = tokens.decimalOf('S'),
            )
        }
    }
}
