package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M351 S<value> [B<value>] [X<value>] [Y<value>] [Z<value>] [E<value>]
 *
 * Set Microstep Pins (control).
 *
 * Marlin documents `S` as required; every property here still defaults to
 * absent, so that every command class is constructible bare.
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(SetMicrostepPins(s = 1).encode())   // M351 S1
 * SetMicrostepPins.decode(GTokenizer.parse("M351 S1").toList())   // SetMicrostepPins(M351 S1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property s `S` (required)
 * @property b `B`
 * @property x `X`
 * @property y `Y`
 * @property z `Z`
 * @property e `E`
 * @see <a href="https://marlinfw.org/docs/gcode/M351.html">MarlinFirmare M351 doc</a>
 */
data class SetMicrostepPins(
    val s: Int? = null,
    val b: Int? = null,
    val x: Int? = null,
    val y: Int? = null,
    val z: Int? = null,
    val e: Int? = null,
) : GRq<SetMicrostepPins> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(6)
        if (s != null) words.add(word('S', s))
        if (b != null) words.add(word('B', b))
        if (x != null) words.add(word('X', x))
        if (y != null) words.add(word('Y', y))
        if (z != null) words.add(word('Z', z))
        if (e != null) words.add(word('E', e))
        return M(351, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<SetMicrostepPins> {

        override fun head(): GParameterWord<*> {
            return M(351).head
        }

        override fun decodeParams(tokens: List<GToken>): SetMicrostepPins {
            return SetMicrostepPins(
                s = tokens.intOf('S'),
                b = tokens.intOf('B'),
                x = tokens.intOf('X'),
                y = tokens.intOf('Y'),
                z = tokens.intOf('Z'),
                e = tokens.intOf('E'),
            )
        }
    }
}
