package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M145 [S<index>] [H<temp>] [B<temp>] [F<speed>]
 *
 * Set Material Preset (lcd).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(SetMaterialPreset(index = 1).encode())   // M145 S1
 * SetMaterialPreset.decode(GTokenizer.parse("M145 S1").toList())   // SetMaterialPreset(M145 S1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property index `S` - index
 * @property temp `H` - temp
 * @property b `B` - temp
 * @property speed `F` - speed
 * @see <a href="https://marlinfw.org/docs/gcode/M145.html">MarlinFirmare M145 doc</a>
 */
data class SetMaterialPreset(
    val index: Int? = null,
    val temp: Int? = null,
    val b: Int? = null,
    val speed: Int? = null,
) : GRq<SetMaterialPreset> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(4)
        if (index != null) words.add(word('S', index))
        if (temp != null) words.add(word('H', temp))
        if (b != null) words.add(word('B', b))
        if (speed != null) words.add(word('F', speed))
        return M(145, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<SetMaterialPreset> {

        override fun head(): GParameterWord<*> {
            return M(145).head
        }

        override fun decodeParams(tokens: List<GToken>): SetMaterialPreset {
            return SetMaterialPreset(
                index = tokens.intOf('S'),
                temp = tokens.intOf('H'),
                b = tokens.intOf('B'),
                speed = tokens.intOf('F'),
            )
        }
    }
}
