package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.boolOf
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M421 [I<index>] [J<index>] [X<linear>] [Y<linear>] [Z<linear>] [Q<linear>] [C<value>] [N<value>]
 *
 * Set Mesh Value (motion).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(SetMeshValue(index = 1).encode())   // M421 I1
 * SetMeshValue.decode(GTokenizer.parse("M421 I1").toList())   // SetMeshValue(M421 I1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property index `I` - index
 * @property j `J` - index
 * @property linear `X` - linear
 * @property y `Y` - linear
 * @property z `Z` - linear
 * @property q `Q` - linear
 * @property c `C`
 * @property n `N`
 * @see <a href="https://marlinfw.org/docs/gcode/M421.html">MarlinFirmare M421 doc</a>
 */
data class SetMeshValue(
    val index: Int? = null,
    val j: Int? = null,
    val linear: BigDecimal? = null,
    val y: BigDecimal? = null,
    val z: BigDecimal? = null,
    val q: BigDecimal? = null,
    val c: Boolean? = null,
    val n: Boolean? = null,
) : GRq<SetMeshValue> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(8)
        if (index != null) words.add(word('I', index))
        if (j != null) words.add(word('J', j))
        if (linear != null) words.add(word('X', linear.toPlainString()))
        if (y != null) words.add(word('Y', y.toPlainString()))
        if (z != null) words.add(word('Z', z.toPlainString()))
        if (q != null) words.add(word('Q', q.toPlainString()))
        if (c != null) words.add(word('C', if (c) 1 else 0))
        if (n != null) words.add(word('N', if (n) 1 else 0))
        return M(421, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<SetMeshValue> {

        override fun head(): GParameterWord<*> {
            return M(421).head
        }

        override fun decodeParams(tokens: List<GToken>): SetMeshValue {
            return SetMeshValue(
                index = tokens.intOf('I'),
                j = tokens.intOf('J'),
                linear = tokens.decimalOf('X'),
                y = tokens.decimalOf('Y'),
                z = tokens.decimalOf('Z'),
                q = tokens.decimalOf('Q'),
                c = tokens.boolOf('C'),
                n = tokens.boolOf('N'),
            )
        }
    }
}
