package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M163 [S<index>] [P<factor>]
 *
 * Set Mix Factor (mixing).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(SetMixFactor(index = 1).encode())   // M163 S1
 * SetMixFactor.decode(GTokenizer.parse("M163 S1").toList())   // SetMixFactor(M163 S1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property index `S` - index
 * @property factor `P` - factor
 * @see <a href="https://marlinfw.org/docs/gcode/M163.html">MarlinFirmare M163 doc</a>
 */
data class SetMixFactor(
    val index: Int? = null,
    val factor: BigDecimal? = null,
) : GRq<SetMixFactor> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(2)
        if (index != null) words.add(word('S', index))
        if (factor != null) words.add(word('P', factor.toPlainString()))
        return M(163, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<SetMixFactor> {

        override fun head(): GParameterWord<*> {
            return M(163).head
        }

        override fun decodeParams(tokens: List<GToken>): SetMixFactor {
            return SetMixFactor(
                index = tokens.intOf('S'),
                factor = tokens.decimalOf('P'),
            )
        }
    }
}
