package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M204 [P<accel>] [R<accel>] [T<accel>] [S<accel>]
 *
 * Set Starting Acceleration (motion).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(SetStartingAcceleration(accel = BigDecimal("1.5")).encode())   // M204 P1.5
 * SetStartingAcceleration.decode(GTokenizer.parse("M204 P1.5").toList())   // SetStartingAcceleration(M204 P1.5)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property accel `P` - accel
 * @property r `R` - accel
 * @property t `T` - accel
 * @property s `S` - accel
 * @see <a href="https://marlinfw.org/docs/gcode/M204.html">MarlinFirmare M204 doc</a>
 */
data class SetStartingAcceleration(
    val accel: BigDecimal? = null,
    val r: BigDecimal? = null,
    val t: BigDecimal? = null,
    val s: BigDecimal? = null,
) : GRq<SetStartingAcceleration> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(4)
        if (accel != null) words.add(word('P', accel.toPlainString()))
        if (r != null) words.add(word('R', r.toPlainString()))
        if (t != null) words.add(word('T', t.toPlainString()))
        if (s != null) words.add(word('S', s.toPlainString()))
        return M(204, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<SetStartingAcceleration> {

        override fun head(): GParameterWord<*> {
            return M(204).head
        }

        override fun decodeParams(tokens: List<GToken>): SetStartingAcceleration {
            return SetStartingAcceleration(
                accel = tokens.decimalOf('P'),
                r = tokens.decimalOf('R'),
                t = tokens.decimalOf('T'),
                s = tokens.decimalOf('S'),
            )
        }
    }
}
