package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M908 P<address> S<current>
 *
 * Set Trimpot Pins (control).
 *
 * Marlin documents `P`, `S` as required; every property here still defaults to
 * absent, so that every command class is constructible bare.
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(SetTrimpotPins(address = 1).encode())   // M908 P1
 * SetTrimpotPins.decode(GTokenizer.parse("M908 P1").toList())   // SetTrimpotPins(M908 P1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property address `P` - address (required)
 * @property current `S` - current (required)
 * @see <a href="https://marlinfw.org/docs/gcode/M908.html">MarlinFirmare M908 doc</a>
 */
data class SetTrimpotPins(
    val address: Int? = null,
    val current: Int? = null,
) : GRq<SetTrimpotPins> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(2)
        if (address != null) words.add(word('P', address))
        if (current != null) words.add(word('S', current))
        return M(908, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<SetTrimpotPins> {

        override fun head(): GParameterWord<*> {
            return M(908).head
        }

        override fun decodeParams(tokens: List<GToken>): SetTrimpotPins {
            return SetTrimpotPins(
                address = tokens.intOf('P'),
                current = tokens.intOf('S'),
            )
        }
    }
}
