package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.flag
import org.qw3rtrun.p3d.g.marlin.hasWord
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M149 [C] [F] [K]
 *
 * Set Temperature Units (units).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(SetTemperatureUnits(c = true).encode())   // M149 C
 * SetTemperatureUnits.decode(GTokenizer.parse("M149 C").toList())   // SetTemperatureUnits(M149 C)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property c `C`
 * @property f `F`
 * @property k `K`
 * @see <a href="https://marlinfw.org/docs/gcode/M149.html">MarlinFirmare M149 doc</a>
 */
data class SetTemperatureUnits(
    val c: Boolean = false,
    val f: Boolean = false,
    val k: Boolean = false,
) : GRq<SetTemperatureUnits> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(3)
        if (c) words.add(flag('C'))
        if (f) words.add(flag('F'))
        if (k) words.add(flag('K'))
        return M(149, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<SetTemperatureUnits> {

        override fun head(): GParameterWord<*> {
            return M(149).head
        }

        override fun decodeParams(tokens: List<GToken>): SetTemperatureUnits {
            return SetTemperatureUnits(
                c = tokens.hasWord('C'),
                f = tokens.hasWord('F'),
                k = tokens.hasWord('K'),
            )
        }
    }
}
