package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.flag
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.hasWord
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M422 [R] [S<index>] [W<index>] [X<linear>] [Y<linear>]
 *
 * Set Z Motor XY (calibration).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(SetZMotorXY(r = true).encode())   // M422 R
 * SetZMotorXY.decode(GTokenizer.parse("M422 R").toList())   // SetZMotorXY(M422 R)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property r `R`
 * @property index `S` - index
 * @property w `W` - index
 * @property linear `X` - linear
 * @property y `Y` - linear
 * @see <a href="https://marlinfw.org/docs/gcode/M422.html">MarlinFirmare M422 doc</a>
 */
data class SetZMotorXY(
    val r: Boolean = false,
    val index: Int? = null,
    val w: Int? = null,
    val linear: BigDecimal? = null,
    val y: BigDecimal? = null,
) : GRq<SetZMotorXY> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(5)
        if (r) words.add(flag('R'))
        if (index != null) words.add(word('S', index))
        if (w != null) words.add(word('W', w))
        if (linear != null) words.add(word('X', linear.toPlainString()))
        if (y != null) words.add(word('Y', y.toPlainString()))
        return M(422, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<SetZMotorXY> {

        override fun head(): GParameterWord<*> {
            return M(422).head
        }

        override fun decodeParams(tokens: List<GToken>): SetZMotorXY {
            return SetZMotorXY(
                r = tokens.hasWord('R'),
                index = tokens.intOf('S'),
                w = tokens.intOf('W'),
                linear = tokens.decimalOf('X'),
                y = tokens.decimalOf('Y'),
            )
        }
    }
}
