package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.G
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.boolOf
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * G30 [C<value>] [X<pos>] [Y<pos>] [E<value>]
 *
 * Single Z-Probe (calibration).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(SingleZProbe(c = true).encode())   // G30 C1
 * SingleZProbe.decode(GTokenizer.parse("G30 C1").toList())   // SingleZProbe(G30 C1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property c `C`
 * @property pos `X` - pos
 * @property y `Y` - pos
 * @property e `E`
 * @see <a href="https://marlinfw.org/docs/gcode/G30.html">MarlinFirmare G30 doc</a>
 */
data class SingleZProbe(
    val c: Boolean? = null,
    val pos: BigDecimal? = null,
    val y: BigDecimal? = null,
    val e: Boolean? = null,
) : GRq<SingleZProbe> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(4)
        if (c != null) words.add(word('C', if (c) 1 else 0))
        if (pos != null) words.add(word('X', pos.toPlainString()))
        if (y != null) words.add(word('Y', y.toPlainString()))
        if (e != null) words.add(word('E', if (e) 1 else 0))
        return G(30, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<SingleZProbe> {

        override fun head(): GParameterWord<*> {
            return G(30).head
        }

        override fun decodeParams(tokens: List<GToken>): SingleZProbe {
            return SingleZProbe(
                c = tokens.boolOf('C'),
                pos = tokens.decimalOf('X'),
                y = tokens.decimalOf('Y'),
                e = tokens.boolOf('E'),
            )
        }
    }
}
