package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.boolOf
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M4 [S<power>] [O<power>] [I<mode>]
 *
 * Spindle CCW / Laser On (control).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(SpindleCCWLaserOn(power = 1).encode())   // M4 S1
 * SpindleCCWLaserOn.decode(GTokenizer.parse("M4 S1").toList())   // SpindleCCWLaserOn(M4 S1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property power `S` - power
 * @property o `O` - power
 * @property mode `I` - mode
 * @see <a href="https://marlinfw.org/docs/gcode/M4.html">MarlinFirmare M4 doc</a>
 */
data class SpindleCCWLaserOn(
    val power: Int? = null,
    val o: Int? = null,
    val mode: Boolean? = null,
) : GRq<SpindleCCWLaserOn> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(3)
        if (power != null) words.add(word('S', power))
        if (o != null) words.add(word('O', o))
        if (mode != null) words.add(word('I', if (mode) 1 else 0))
        return M(4, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<SpindleCCWLaserOn> {

        override fun head(): GParameterWord<*> {
            return M(4).head
        }

        override fun decodeParams(tokens: List<GToken>): SpindleCCWLaserOn {
            return SpindleCCWLaserOn(
                power = tokens.intOf('S'),
                o = tokens.intOf('O'),
                mode = tokens.boolOf('I'),
            )
        }
    }
}
