package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.longOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M24 [S<pos>] [T<time>]
 *
 * Start or Resume SD print (sdcard).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(StartOrResumeSDPrint(pos = 1L).encode())   // M24 S1
 * StartOrResumeSDPrint.decode(GTokenizer.parse("M24 S1").toList())   // StartOrResumeSDPrint(M24 S1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property pos `S` - pos
 * @property time `T` - time
 * @see <a href="https://marlinfw.org/docs/gcode/M24.html">MarlinFirmare M24 doc</a>
 */
data class StartOrResumeSDPrint(
    val pos: Long? = null,
    val time: Long? = null,
) : GRq<StartOrResumeSDPrint> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(2)
        if (pos != null) words.add(word('S', BigDecimal.valueOf(pos)))
        if (time != null) words.add(word('T', BigDecimal.valueOf(time)))
        return M(24, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<StartOrResumeSDPrint> {

        override fun head(): GParameterWord<*> {
            return M(24).head
        }

        override fun decodeParams(tokens: List<GToken>): StartOrResumeSDPrint {
            return StartOrResumeSDPrint(
                pos = tokens.longOf('S'),
                time = tokens.longOf('T'),
            )
        }
    }
}
