package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.bareString
import org.qw3rtrun.p3d.g.marlin.stringArg
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M28 [<filename>]
 *
 * Start SD write (sdcard).
 *
 * **`filename` is a bare rest-of-line string** (spec 3.4a).
 * It carries no letter, it is written last because everything to the end of the
 * line belongs to it, and it cannot contain `;` - every parser reads that as the
 * start of a comment.
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(StartSDWrite(filename = "a tail").encode())   // M28 a tail
 * StartSDWrite.decode(GTokenizer.parse("M28 a tail").toList())   // StartSDWrite(M28 a tail)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property filename the rest of the line
 * @see <a href="https://marlinfw.org/docs/gcode/M28.html">MarlinFirmare M28 doc</a>
 */
data class StartSDWrite(
    val filename: String? = null,
) : GRq<StartSDWrite> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(1)
        if (filename != null) words.add(bareString(filename))
        return M(28, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<StartSDWrite> {

        override fun head(): GParameterWord<*> {
            return M(28).head
        }

        override fun decodeParams(tokens: List<GToken>): StartSDWrite {
            return StartSDWrite(
                filename = tokens.stringArg(),
            )
        }
    }
}
