package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M906 [E<value>] I<value> [T<value>] [X<value>] [Y<value>] [Z<value>]
 *
 * Stepper Motor Current.
 *
 * Marlin documents `I` as required; every property here still defaults to
 * absent, so that every command class is constructible bare.
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(StepperMotorCurrent(e = 1).encode())   // M906 E1
 * StepperMotorCurrent.decode(GTokenizer.parse("M906 E1").toList())   // StepperMotorCurrent(M906 E1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property e `E`
 * @property i `I` (required)
 * @property t `T`
 * @property x `X`
 * @property y `Y`
 * @property z `Z`
 * @see <a href="https://marlinfw.org/docs/gcode/M906.html">MarlinFirmare M906 doc</a>
 */
data class StepperMotorCurrent(
    val e: Int? = null,
    val i: Int? = null,
    val t: Int? = null,
    val x: Int? = null,
    val y: Int? = null,
    val z: Int? = null,
) : GRq<StepperMotorCurrent> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(6)
        if (e != null) words.add(word('E', e))
        if (i != null) words.add(word('I', i))
        if (t != null) words.add(word('T', t))
        if (x != null) words.add(word('X', x))
        if (y != null) words.add(word('Y', y))
        if (z != null) words.add(word('Z', z))
        return M(906, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<StepperMotorCurrent> {

        override fun head(): GParameterWord<*> {
            return M(906).head
        }

        override fun decodeParams(tokens: List<GToken>): StepperMotorCurrent {
            return StepperMotorCurrent(
                e = tokens.intOf('E'),
                i = tokens.intOf('I'),
                t = tokens.intOf('T'),
                x = tokens.intOf('X'),
                y = tokens.intOf('Y'),
                z = tokens.intOf('Z'),
            )
        }
    }
}
