package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M77
 *
 * Stop Print Job Timer (printjob).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(StopPrintJobTimer().encode())   // M77
 * StopPrintJobTimer.decode(GTokenizer.parse("M77").toList())   // StopPrintJobTimer(M77)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @see <a href="https://marlinfw.org/docs/gcode/M77.html">MarlinFirmare M77 doc</a>
 */
class StopPrintJobTimer : GRq<StopPrintJobTimer> {

    override fun encode(): GCommand {
        return M(77)
    }

    override fun equals(other: Any?): Boolean {
        return other is StopPrintJobTimer
    }

    override fun hashCode(): Int {
        return 748819
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<StopPrintJobTimer> {

        override fun head(): GParameterWord<*> {
            return M(77).head
        }

        override fun decodeParams(tokens: List<GToken>): StopPrintJobTimer {
            return StopPrintJobTimer()
        }
    }
}
