package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.G
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * G60 [S<slot>] [D<slot>] [Q<slot>] [F<rate>] [X<value>] [Y<value>] [Z<value>] [E<value>]
 *
 * Stored Positions (motion).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(StoredPositions(slot = 1).encode())   // G60 S1
 * StoredPositions.decode(GTokenizer.parse("G60 S1").toList())   // StoredPositions(G60 S1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property slot `S` - slot
 * @property d `D` - slot
 * @property q `Q` - slot
 * @property rate `F` - rate
 * @property x `X`
 * @property y `Y`
 * @property z `Z`
 * @property e `E`
 * @see <a href="https://marlinfw.org/docs/gcode/G60.html">MarlinFirmare G60 doc</a>
 */
data class StoredPositions(
    val slot: Int? = null,
    val d: Int? = null,
    val q: Int? = null,
    val rate: BigDecimal? = null,
    val x: BigDecimal? = null,
    val y: BigDecimal? = null,
    val z: BigDecimal? = null,
    val e: BigDecimal? = null,
) : GRq<StoredPositions> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(8)
        if (slot != null) words.add(word('S', slot))
        if (d != null) words.add(word('D', d))
        if (q != null) words.add(word('Q', q))
        if (rate != null) words.add(word('F', rate.toPlainString()))
        if (x != null) words.add(word('X', x.toPlainString()))
        if (y != null) words.add(word('Y', y.toPlainString()))
        if (z != null) words.add(word('Z', z.toPlainString()))
        if (e != null) words.add(word('E', e.toPlainString()))
        return G(60, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<StoredPositions> {

        override fun head(): GParameterWord<*> {
            return G(60).head
        }

        override fun decodeParams(tokens: List<GToken>): StoredPositions {
            return StoredPositions(
                slot = tokens.intOf('S'),
                d = tokens.intOf('D'),
                q = tokens.intOf('Q'),
                rate = tokens.decimalOf('F'),
                x = tokens.decimalOf('X'),
                y = tokens.decimalOf('Y'),
                z = tokens.decimalOf('Z'),
                e = tokens.decimalOf('E'),
            )
        }
    }
}
