package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.boolOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M402 [R<value>]
 *
 * Stow Probe (calibration).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(StowProbe(r = true).encode())   // M402 R1
 * StowProbe.decode(GTokenizer.parse("M402 R1").toList())   // StowProbe(M402 R1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property r `R`
 * @see <a href="https://marlinfw.org/docs/gcode/M402.html">MarlinFirmare M402 doc</a>
 */
data class StowProbe(
    val r: Boolean? = null,
) : GRq<StowProbe> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(1)
        if (r != null) words.add(word('R', if (r) 1 else 0))
        return M(402, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<StowProbe> {

        override fun head(): GParameterWord<*> {
            return M(402).head
        }

        override fun decodeParams(tokens: List<GToken>): StowProbe {
            return StowProbe(
                r = tokens.boolOf('R'),
            )
        }
    }
}
