package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.flag
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.hasWord
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M919 [O<value>] [P<value>] [S<value>] [I<value>] [T<value>] [X] [Y] [Z] [A] [B] [C] [U] [V] [W]
 *
 * TMC Chopper Timing (trinamic).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(TMCChopperTiming(o = 1).encode())   // M919 O1
 * TMCChopperTiming.decode(GTokenizer.parse("M919 O1").toList())   // TMCChopperTiming(M919 O1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property o `O`
 * @property p `P`
 * @property s `S`
 * @property i `I`
 * @property t `T`
 * @property x `X`
 * @property y `Y`
 * @property z `Z`
 * @property a `A`
 * @property b `B`
 * @property c `C`
 * @property u `U`
 * @property v `V`
 * @property w `W`
 * @see <a href="https://marlinfw.org/docs/gcode/M919.html">MarlinFirmare M919 doc</a>
 */
data class TMCChopperTiming(
    val o: Int? = null,
    val p: Int? = null,
    val s: Int? = null,
    val i: Int? = null,
    val t: Int? = null,
    val x: Boolean = false,
    val y: Boolean = false,
    val z: Boolean = false,
    val a: Boolean = false,
    val b: Boolean = false,
    val c: Boolean = false,
    val u: Boolean = false,
    val v: Boolean = false,
    val w: Boolean = false,
) : GRq<TMCChopperTiming> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(14)
        if (o != null) words.add(word('O', o))
        if (p != null) words.add(word('P', p))
        if (s != null) words.add(word('S', s))
        if (i != null) words.add(word('I', i))
        if (t != null) words.add(word('T', t))
        if (x) words.add(flag('X'))
        if (y) words.add(flag('Y'))
        if (z) words.add(flag('Z'))
        if (a) words.add(flag('A'))
        if (b) words.add(flag('B'))
        if (c) words.add(flag('C'))
        if (u) words.add(flag('U'))
        if (v) words.add(flag('V'))
        if (w) words.add(flag('W'))
        return M(919, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<TMCChopperTiming> {

        override fun head(): GParameterWord<*> {
            return M(919).head
        }

        override fun decodeParams(tokens: List<GToken>): TMCChopperTiming {
            return TMCChopperTiming(
                o = tokens.intOf('O'),
                p = tokens.intOf('P'),
                s = tokens.intOf('S'),
                i = tokens.intOf('I'),
                t = tokens.intOf('T'),
                x = tokens.hasWord('X'),
                y = tokens.hasWord('Y'),
                z = tokens.hasWord('Z'),
                a = tokens.hasWord('A'),
                b = tokens.hasWord('B'),
                c = tokens.hasWord('C'),
                u = tokens.hasWord('U'),
                v = tokens.hasWord('V'),
                w = tokens.hasWord('W'),
            )
        }
    }
}
