package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.flag
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.boolOf
import org.qw3rtrun.p3d.g.marlin.hasWord
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M122 [I] [X] [Y] [Z] [E] [V] [S<value>] [P<ms>]
 *
 * TMC Debugging (debug).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(TMCDebugging(i = true).encode())   // M122 I
 * TMCDebugging.decode(GTokenizer.parse("M122 I").toList())   // TMCDebugging(M122 I)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property i `I`
 * @property x `X`
 * @property y `Y`
 * @property z `Z`
 * @property e `E`
 * @property v `V`
 * @property s `S`
 * @property ms `P` - ms
 * @see <a href="https://marlinfw.org/docs/gcode/M122.html">MarlinFirmare M122 doc</a>
 */
data class TMCDebugging(
    val i: Boolean = false,
    val x: Boolean = false,
    val y: Boolean = false,
    val z: Boolean = false,
    val e: Boolean = false,
    val v: Boolean = false,
    val s: Boolean? = null,
    val ms: Int? = null,
) : GRq<TMCDebugging> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(8)
        if (i) words.add(flag('I'))
        if (x) words.add(flag('X'))
        if (y) words.add(flag('Y'))
        if (z) words.add(flag('Z'))
        if (e) words.add(flag('E'))
        if (v) words.add(flag('V'))
        if (s != null) words.add(word('S', if (s) 1 else 0))
        if (ms != null) words.add(word('P', ms))
        return M(122, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<TMCDebugging> {

        override fun head(): GParameterWord<*> {
            return M(122).head
        }

        override fun decodeParams(tokens: List<GToken>): TMCDebugging {
            return TMCDebugging(
                i = tokens.hasWord('I'),
                x = tokens.hasWord('X'),
                y = tokens.hasWord('Y'),
                z = tokens.hasWord('Z'),
                e = tokens.hasWord('E'),
                v = tokens.hasWord('V'),
                s = tokens.boolOf('S'),
                ms = tokens.intOf('P'),
            )
        }
    }
}
