package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M920 [I<value>] [X<value>] [Y<value>] [Z<value>] [A<value>] [B<value>] [C<value>] [U<value>] [V<value>] [W<value>]
 *
 * TMC Homing Current (trinamic).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(TMCHomingCurrent(i = 1).encode())   // M920 I1
 * TMCHomingCurrent.decode(GTokenizer.parse("M920 I1").toList())   // TMCHomingCurrent(M920 I1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property i `I`
 * @property x `X`
 * @property y `Y`
 * @property z `Z`
 * @property a `A`
 * @property b `B`
 * @property c `C`
 * @property u `U`
 * @property v `V`
 * @property w `W`
 * @see <a href="https://marlinfw.org/docs/gcode/M920.html">MarlinFirmare M920 doc</a>
 */
data class TMCHomingCurrent(
    val i: Int? = null,
    val x: Int? = null,
    val y: Int? = null,
    val z: Int? = null,
    val a: Int? = null,
    val b: Int? = null,
    val c: Int? = null,
    val u: Int? = null,
    val v: Int? = null,
    val w: Int? = null,
) : GRq<TMCHomingCurrent> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(10)
        if (i != null) words.add(word('I', i))
        if (x != null) words.add(word('X', x))
        if (y != null) words.add(word('Y', y))
        if (z != null) words.add(word('Z', z))
        if (a != null) words.add(word('A', a))
        if (b != null) words.add(word('B', b))
        if (c != null) words.add(word('C', c))
        if (u != null) words.add(word('U', u))
        if (v != null) words.add(word('V', v))
        if (w != null) words.add(word('W', w))
        return M(920, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<TMCHomingCurrent> {

        override fun head(): GParameterWord<*> {
            return M(920).head
        }

        override fun decodeParams(tokens: List<GToken>): TMCHomingCurrent {
            return TMCHomingCurrent(
                i = tokens.intOf('I'),
                x = tokens.intOf('X'),
                y = tokens.intOf('Y'),
                z = tokens.intOf('Z'),
                a = tokens.intOf('A'),
                b = tokens.intOf('B'),
                c = tokens.intOf('C'),
                u = tokens.intOf('U'),
                v = tokens.intOf('V'),
                w = tokens.intOf('W'),
            )
        }
    }
}
