package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M240 [A<offset>] [B<offset>] [D<ms>] [F<feedrate>] [I<pos>] [J<pos>] [P<ms>] [R<length>] [S<feedrate>] [X<pos>] [Y<pos>] [Z<length>]
 *
 * Trigger Camera (extras).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(TriggerCamera(offset = BigDecimal("1.5")).encode())   // M240 A1.5
 * TriggerCamera.decode(GTokenizer.parse("M240 A1.5").toList())   // TriggerCamera(M240 A1.5)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property offset `A` - offset
 * @property b `B` - offset
 * @property ms `D` - ms
 * @property feedrate `F` - feedrate
 * @property pos `I` - pos
 * @property j `J` - pos
 * @property p `P` - ms
 * @property length `R` - length
 * @property s `S` - feedrate
 * @property x `X` - pos
 * @property y `Y` - pos
 * @property z `Z` - length
 * @see <a href="https://marlinfw.org/docs/gcode/M240.html">MarlinFirmare M240 doc</a>
 */
data class TriggerCamera(
    val offset: BigDecimal? = null,
    val b: BigDecimal? = null,
    val ms: Int? = null,
    val feedrate: BigDecimal? = null,
    val pos: BigDecimal? = null,
    val j: BigDecimal? = null,
    val p: Int? = null,
    val length: BigDecimal? = null,
    val s: BigDecimal? = null,
    val x: BigDecimal? = null,
    val y: BigDecimal? = null,
    val z: BigDecimal? = null,
) : GRq<TriggerCamera> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(12)
        if (offset != null) words.add(word('A', offset.toPlainString()))
        if (b != null) words.add(word('B', b.toPlainString()))
        if (ms != null) words.add(word('D', ms))
        if (feedrate != null) words.add(word('F', feedrate.toPlainString()))
        if (pos != null) words.add(word('I', pos.toPlainString()))
        if (j != null) words.add(word('J', j.toPlainString()))
        if (p != null) words.add(word('P', p))
        if (length != null) words.add(word('R', length.toPlainString()))
        if (s != null) words.add(word('S', s.toPlainString()))
        if (x != null) words.add(word('X', x.toPlainString()))
        if (y != null) words.add(word('Y', y.toPlainString()))
        if (z != null) words.add(word('Z', z.toPlainString()))
        return M(240, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<TriggerCamera> {

        override fun head(): GParameterWord<*> {
            return M(240).head
        }

        override fun decodeParams(tokens: List<GToken>): TriggerCamera {
            return TriggerCamera(
                offset = tokens.decimalOf('A'),
                b = tokens.decimalOf('B'),
                ms = tokens.intOf('D'),
                feedrate = tokens.decimalOf('F'),
                pos = tokens.decimalOf('I'),
                j = tokens.decimalOf('J'),
                p = tokens.intOf('P'),
                length = tokens.decimalOf('R'),
                s = tokens.decimalOf('S'),
                x = tokens.decimalOf('X'),
                y = tokens.decimalOf('Y'),
                z = tokens.decimalOf('Z'),
            )
        }
    }
}
