package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M907 [B<current>] [C<current>] [D<current>] [E<current>] [S<current>] [X<current>] [Y<current>] [Z<current>] [I<current>] [J<current>] [K<current>] [U<current>] [V<current>] [W<current>]
 *
 * Trimpot Stepper Motor Current (control).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(TrimpotStepperMotorCurrent(current = BigDecimal("1.5")).encode())   // M907 B1.5
 * TrimpotStepperMotorCurrent.decode(GTokenizer.parse("M907 B1.5").toList())   // TrimpotStepperMotorCurrent(M907 B1.5)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property current `B` - current
 * @property c `C` - current
 * @property d `D` - current
 * @property e `E` - current
 * @property s `S` - current
 * @property x `X` - current
 * @property y `Y` - current
 * @property z `Z` - current
 * @property i `I` - current
 * @property j `J` - current
 * @property k `K` - current
 * @property u `U` - current
 * @property v `V` - current
 * @property w `W` - current
 * @see <a href="https://marlinfw.org/docs/gcode/M907.html">MarlinFirmare M907 doc</a>
 */
data class TrimpotStepperMotorCurrent(
    val current: BigDecimal? = null,
    val c: BigDecimal? = null,
    val d: BigDecimal? = null,
    val e: BigDecimal? = null,
    val s: BigDecimal? = null,
    val x: BigDecimal? = null,
    val y: BigDecimal? = null,
    val z: BigDecimal? = null,
    val i: BigDecimal? = null,
    val j: BigDecimal? = null,
    val k: BigDecimal? = null,
    val u: BigDecimal? = null,
    val v: BigDecimal? = null,
    val w: BigDecimal? = null,
) : GRq<TrimpotStepperMotorCurrent> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(14)
        if (current != null) words.add(word('B', current.toPlainString()))
        if (c != null) words.add(word('C', c.toPlainString()))
        if (d != null) words.add(word('D', d.toPlainString()))
        if (e != null) words.add(word('E', e.toPlainString()))
        if (s != null) words.add(word('S', s.toPlainString()))
        if (x != null) words.add(word('X', x.toPlainString()))
        if (y != null) words.add(word('Y', y.toPlainString()))
        if (z != null) words.add(word('Z', z.toPlainString()))
        if (i != null) words.add(word('I', i.toPlainString()))
        if (j != null) words.add(word('J', j.toPlainString()))
        if (k != null) words.add(word('K', k.toPlainString()))
        if (u != null) words.add(word('U', u.toPlainString()))
        if (v != null) words.add(word('V', v.toPlainString()))
        if (w != null) words.add(word('W', w.toPlainString()))
        return M(907, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<TrimpotStepperMotorCurrent> {

        override fun head(): GParameterWord<*> {
            return M(907).head
        }

        override fun decodeParams(tokens: List<GToken>): TrimpotStepperMotorCurrent {
            return TrimpotStepperMotorCurrent(
                current = tokens.decimalOf('B'),
                c = tokens.decimalOf('C'),
                d = tokens.decimalOf('D'),
                e = tokens.decimalOf('E'),
                s = tokens.decimalOf('S'),
                x = tokens.decimalOf('X'),
                y = tokens.decimalOf('Y'),
                z = tokens.decimalOf('Z'),
                i = tokens.decimalOf('I'),
                j = tokens.decimalOf('J'),
                k = tokens.decimalOf('K'),
                u = tokens.decimalOf('U'),
                v = tokens.decimalOf('V'),
                w = tokens.decimalOf('W'),
            )
        }
    }
}
