package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.bareString
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.beforeStringArg
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.marlin.stringArg
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M0 [S<sec>] [P<ms>] [<message>]
 *
 * Unconditional stop (motion).
 *
 * **`message` is a bare rest-of-line string** (spec 3.4a).
 * It carries no letter, it is written last because everything to the end of the
 * line belongs to it, and it cannot contain `;` - every parser reads that as the
 * start of a comment.
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(UnconditionalStopM0(sec = 1).encode())   // M0 S1
 * UnconditionalStopM0.decode(GTokenizer.parse("M0 S1").toList())   // UnconditionalStopM0(M0 S1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property sec `S` - sec
 * @property ms `P` - ms
 * @property message the rest of the line
 * @see <a href="https://marlinfw.org/docs/gcode/M0.html">MarlinFirmare M0 doc</a>
 */
data class UnconditionalStopM0(
    val sec: Int? = null,
    val ms: Int? = null,
    val message: String? = null,
) : GRq<UnconditionalStopM0> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(3)
        if (sec != null) words.add(word('S', sec))
        if (ms != null) words.add(word('P', ms))
        if (message != null) words.add(bareString(message))
        return M(0, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<UnconditionalStopM0> {

        override fun head(): GParameterWord<*> {
            return M(0).head
        }

        override fun decodeParams(tokens: List<GToken>): UnconditionalStopM0 {
            val params = tokens.beforeStringArg('S', 'P')
            return UnconditionalStopM0(
                sec = params.intOf('S'),
                ms = params.intOf('P'),
                message = tokens.stringArg('S', 'P'),
            )
        }
    }
}
