package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.dsl.G
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * G32
 *
 * Undock Sled (calibration).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(UndockSled().encode())   // G32
 * UndockSled.decode(GTokenizer.parse("G32").toList())   // UndockSled(G32)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @see <a href="https://marlinfw.org/docs/gcode/G32.html">MarlinFirmare G32 doc</a>
 */
class UndockSled : GRq<UndockSled> {

    override fun encode(): GCommand {
        return G(32)
    }

    override fun equals(other: Any?): Boolean {
        return other is UndockSled
    }

    override fun hashCode(): Int {
        return 337154
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<UndockSled> {

        override fun head(): GParameterWord<*> {
            return G(32).head
        }

        override fun decodeParams(tokens: List<GToken>): UndockSled {
            return UndockSled()
        }
    }
}
