package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M702 [T<extruder>] [Z<distance>] U<distance>
 *
 * Unload filament (control).
 *
 * Marlin documents `U` as required; every property here still defaults to
 * absent, so that every command class is constructible bare.
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(UnloadFilament(extruder = 1).encode())   // M702 T1
 * UnloadFilament.decode(GTokenizer.parse("M702 T1").toList())   // UnloadFilament(M702 T1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property extruder `T` - extruder
 * @property distance `Z` - distance
 * @property u `U` - distance (required)
 * @see <a href="https://marlinfw.org/docs/gcode/M702.html">MarlinFirmare M702 doc</a>
 */
data class UnloadFilament(
    val extruder: Int? = null,
    val distance: BigDecimal? = null,
    val u: BigDecimal? = null,
) : GRq<UnloadFilament> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(3)
        if (extruder != null) words.add(word('T', extruder))
        if (distance != null) words.add(word('Z', distance.toPlainString()))
        if (u != null) words.add(word('U', u.toPlainString()))
        return M(702, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<UnloadFilament> {

        override fun head(): GParameterWord<*> {
            return M(702).head
        }

        override fun decodeParams(tokens: List<GToken>): UnloadFilament {
            return UnloadFilament(
                extruder = tokens.intOf('T'),
                distance = tokens.decimalOf('Z'),
                u = tokens.decimalOf('U'),
            )
        }
    }
}
