package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M305 [P<index>] [R<ohm>] [T<ohms>] [B<beta>] [C<coeff>]
 *
 * User Thermistor Parameters (thermal).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(UserThermistorParameters(index = 1).encode())   // M305 P1
 * UserThermistorParameters.decode(GTokenizer.parse("M305 P1").toList())   // UserThermistorParameters(M305 P1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property index `P` - index
 * @property ohm `R` - ohm
 * @property ohms `T` - ohms
 * @property beta `B` - beta
 * @property coeff `C` - coeff
 * @see <a href="https://marlinfw.org/docs/gcode/M305.html">MarlinFirmare M305 doc</a>
 */
data class UserThermistorParameters(
    val index: Int? = null,
    val ohm: Int? = null,
    val ohms: Int? = null,
    val beta: Int? = null,
    val coeff: BigDecimal? = null,
) : GRq<UserThermistorParameters> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(5)
        if (index != null) words.add(word('P', index))
        if (ohm != null) words.add(word('R', ohm))
        if (ohms != null) words.add(word('T', ohms))
        if (beta != null) words.add(word('B', beta))
        if (coeff != null) words.add(word('C', coeff.toPlainString()))
        return M(305, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<UserThermistorParameters> {

        override fun head(): GParameterWord<*> {
            return M(305).head
        }

        override fun decodeParams(tokens: List<GToken>): UserThermistorParameters {
            return UserThermistorParameters(
                index = tokens.intOf('P'),
                ohm = tokens.intOf('R'),
                ohms = tokens.intOf('T'),
                beta = tokens.intOf('B'),
                coeff = tokens.decimalOf('C'),
            )
        }
    }
}
