package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M200 [D<diameter>] [L<volume>] [S<value>] [T<index>]
 *
 * Volumetric Extrusion Diameter (motion).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(VolumetricExtrusionDiameter(diameter = BigDecimal("1.5")).encode())   // M200 D1.5
 * VolumetricExtrusionDiameter.decode(GTokenizer.parse("M200 D1.5").toList())   // VolumetricExtrusionDiameter(M200 D1.5)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property diameter `D` - diameter
 * @property volume `L` - volume
 * @property s `S`
 * @property index `T` - index
 * @see <a href="https://marlinfw.org/docs/gcode/M200.html">MarlinFirmare M200 doc</a>
 */
data class VolumetricExtrusionDiameter(
    val diameter: BigDecimal? = null,
    val volume: BigDecimal? = null,
    val s: Int? = null,
    val index: Int? = null,
) : GRq<VolumetricExtrusionDiameter> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(4)
        if (diameter != null) words.add(word('D', diameter.toPlainString()))
        if (volume != null) words.add(word('L', volume.toPlainString()))
        if (s != null) words.add(word('S', s))
        if (index != null) words.add(word('T', index))
        return M(200, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<VolumetricExtrusionDiameter> {

        override fun head(): GParameterWord<*> {
            return M(200).head
        }

        override fun decodeParams(tokens: List<GToken>): VolumetricExtrusionDiameter {
            return VolumetricExtrusionDiameter(
                diameter = tokens.decimalOf('D'),
                volume = tokens.decimalOf('L'),
                s = tokens.intOf('S'),
                index = tokens.intOf('T'),
            )
        }
    }
}
