package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M190 [I<index>] [S<temp>] [R<temp>] [T<seconds>]
 *
 * Wait for Bed Temperature (thermal).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(WaitForBedTemperature(index = 1).encode())   // M190 I1
 * WaitForBedTemperature.decode(GTokenizer.parse("M190 I1").toList())   // WaitForBedTemperature(M190 I1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property index `I` - index
 * @property temp `S` - temp
 * @property r `R` - temp
 * @property seconds `T` - seconds
 * @see <a href="https://marlinfw.org/docs/gcode/M190.html">MarlinFirmare M190 doc</a>
 */
data class WaitForBedTemperature(
    val index: Int? = null,
    val temp: BigDecimal? = null,
    val r: BigDecimal? = null,
    val seconds: Int? = null,
) : GRq<WaitForBedTemperature> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(4)
        if (index != null) words.add(word('I', index))
        if (temp != null) words.add(word('S', temp.toPlainString()))
        if (r != null) words.add(word('R', r.toPlainString()))
        if (seconds != null) words.add(word('T', seconds))
        return M(190, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<WaitForBedTemperature> {

        override fun head(): GParameterWord<*> {
            return M(190).head
        }

        override fun decodeParams(tokens: List<GToken>): WaitForBedTemperature {
            return WaitForBedTemperature(
                index = tokens.intOf('I'),
                temp = tokens.decimalOf('S'),
                r = tokens.decimalOf('R'),
                seconds = tokens.intOf('T'),
            )
        }
    }
}
