package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder

/**
 * M226 P<pin> [S<state>]
 *
 * Wait for Pin State (control).
 *
 * Marlin documents `P` as required; every property here still defaults to
 * absent, so that every command class is constructible bare.
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(WaitForPinState(pin = 1).encode())   // M226 P1
 * WaitForPinState.decode(GTokenizer.parse("M226 P1").toList())   // WaitForPinState(M226 P1)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property pin `P` - pin (required)
 * @property state `S` - state
 * @see <a href="https://marlinfw.org/docs/gcode/M226.html">MarlinFirmare M226 doc</a>
 */
data class WaitForPinState(
    val pin: Int? = null,
    val state: Int? = null,
) : GRq<WaitForPinState> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(2)
        if (pin != null) words.add(word('P', pin))
        if (state != null) words.add(word('S', state))
        return M(226, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<WaitForPinState> {

        override fun head(): GParameterWord<*> {
            return M(226).head
        }

        override fun decodeParams(tokens: List<GToken>): WaitForPinState {
            return WaitForPinState(
                pin = tokens.intOf('P'),
                state = tokens.intOf('S'),
            )
        }
    }
}
