package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.flag
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.hasWord
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M423 [R] [A<linear>] [E<linear>] [I<linear>] [X<index>] [Z<linear>]
 *
 * X Twist Compensation (calibration).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(XTwistCompensation(r = true).encode())   // M423 R
 * XTwistCompensation.decode(GTokenizer.parse("M423 R").toList())   // XTwistCompensation(M423 R)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property r `R`
 * @property linear `A` - linear
 * @property e `E` - linear
 * @property i `I` - linear
 * @property index `X` - index
 * @property z `Z` - linear
 * @see <a href="https://marlinfw.org/docs/gcode/M423.html">MarlinFirmare M423 doc</a>
 */
data class XTwistCompensation(
    val r: Boolean = false,
    val linear: BigDecimal? = null,
    val e: BigDecimal? = null,
    val i: BigDecimal? = null,
    val index: Int? = null,
    val z: BigDecimal? = null,
) : GRq<XTwistCompensation> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(6)
        if (r) words.add(flag('R'))
        if (linear != null) words.add(word('A', linear.toPlainString()))
        if (e != null) words.add(word('E', e.toPlainString()))
        if (i != null) words.add(word('I', i.toPlainString()))
        if (index != null) words.add(word('X', index))
        if (z != null) words.add(word('Z', z.toPlainString()))
        return M(423, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<XTwistCompensation> {

        override fun head(): GParameterWord<*> {
            return M(423).head
        }

        override fun decodeParams(tokens: List<GToken>): XTwistCompensation {
            return XTwistCompensation(
                r = tokens.hasWord('R'),
                linear = tokens.decimalOf('A'),
                e = tokens.decimalOf('E'),
                i = tokens.decimalOf('I'),
                index = tokens.intOf('X'),
                z = tokens.decimalOf('Z'),
            )
        }
    }
}
