package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M851 [X<value>] [Y<value>] [Z<value>]
 *
 * XYZ Probe Offset.
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(XYZProbeOffset(x = BigDecimal("1.5")).encode())   // M851 X1.5
 * XYZProbeOffset.decode(GTokenizer.parse("M851 X1.5").toList())   // XYZProbeOffset(M851 X1.5)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property x `X`
 * @property y `Y`
 * @property z `Z`
 * @see <a href="https://marlinfw.org/docs/gcode/M851.html">MarlinFirmare M851 doc</a>
 */
data class XYZProbeOffset(
    val x: BigDecimal? = null,
    val y: BigDecimal? = null,
    val z: BigDecimal? = null,
) : GRq<XYZProbeOffset> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(3)
        if (x != null) words.add(word('X', x.toPlainString()))
        if (y != null) words.add(word('Y', y.toPlainString()))
        if (z != null) words.add(word('Z', z.toPlainString()))
        return M(851, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<XYZProbeOffset> {

        override fun head(): GParameterWord<*> {
            return M(851).head
        }

        override fun decodeParams(tokens: List<GToken>): XYZProbeOffset {
            return XYZProbeOffset(
                x = tokens.decimalOf('X'),
                y = tokens.decimalOf('Y'),
                z = tokens.decimalOf('Z'),
            )
        }
    }
}
