package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.token.GCommand
import org.qw3rtrun.p3d.g.code.core.token.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.token.GWord
import org.qw3rtrun.p3d.g.code.dsl.G
import org.qw3rtrun.p3d.g.code.dsl.flag
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.boolOf
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.hasWord
import org.qw3rtrun.p3d.g.marlin.intOf
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * G34 [L] [Z<value>] [S<value>] [I<value>] [T<value>] [A<value>] [E<value>] [R]
 *
 * Z Steppers Auto-Alignment (calibration).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(ZSteppersAutoAlignment(l = true).encode())   // G34 L
 * ZSteppersAutoAlignment.decode(GTokenizer.parse("G34 L").toList())   // ZSteppersAutoAlignment(G34 L)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property l `L`
 * @property z `Z`
 * @property s `S`
 * @property i `I`
 * @property t `T`
 * @property a `A`
 * @property e `E`
 * @property r `R`
 * @see <a href="https://marlinfw.org/docs/gcode/G34.html">MarlinFirmare G34 doc</a>
 */
data class ZSteppersAutoAlignment(
    val l: Boolean = false,
    val z: Int? = null,
    val s: Boolean? = null,
    val i: Int? = null,
    val t: BigDecimal? = null,
    val a: BigDecimal? = null,
    val e: Boolean? = null,
    val r: Boolean = false,
) : GRq<ZSteppersAutoAlignment> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(8)
        if (l) words.add(flag('L'))
        if (z != null) words.add(word('Z', z))
        if (s != null) words.add(word('S', if (s) 1 else 0))
        if (i != null) words.add(word('I', i))
        if (t != null) words.add(word('T', t.toPlainString()))
        if (a != null) words.add(word('A', a.toPlainString()))
        if (e != null) words.add(word('E', if (e) 1 else 0))
        if (r) words.add(flag('R'))
        return G(34, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<ZSteppersAutoAlignment> {

        override fun head(): GParameterWord<*> {
            return G(34).head
        }

        override fun decodeParams(tokens: List<GToken>): ZSteppersAutoAlignment {
            return ZSteppersAutoAlignment(
                l = tokens.hasWord('L'),
                z = tokens.intOf('Z'),
                s = tokens.boolOf('S'),
                i = tokens.intOf('I'),
                t = tokens.decimalOf('T'),
                a = tokens.decimalOf('A'),
                e = tokens.boolOf('E'),
                r = tokens.hasWord('R'),
            )
        }
    }
}
