package org.qw3rtrun.p3d.g.marlin.command

import org.qw3rtrun.p3d.g.code.core.GEncoder
import org.qw3rtrun.p3d.g.code.core.block.GCommand
import org.qw3rtrun.p3d.g.code.core.block.GParameterWord
import org.qw3rtrun.p3d.g.code.core.token.GToken
import org.qw3rtrun.p3d.g.code.core.block.GWord
import org.qw3rtrun.p3d.g.code.dsl.M
import org.qw3rtrun.p3d.g.code.dsl.flag
import org.qw3rtrun.p3d.g.code.dsl.word
import org.qw3rtrun.p3d.g.marlin.decimalOf
import org.qw3rtrun.p3d.g.marlin.hasWord
import org.qw3rtrun.p3d.g.protocol.GRq
import org.qw3rtrun.p3d.g.protocol.GRqDecoder
import java.math.BigDecimal

/**
 * M593 [D<zeta>] [F<hertz>] [X] [Y] [Z]
 *
 * ZV Input Shaping (motion).
 *
 * Build one to send the command, and read one back with the companion's `decode`, which
 * is this command's [GRqDecoder]:
 *
 * ```
 * GEncoder.encode(ZVInputShaping(zeta = BigDecimal("1.5")).encode())   // M593 D1.5
 * ZVInputShaping.decode(GTokenizer.parse("M593 D1.5").toList())   // ZVInputShaping(M593 D1.5)
 * ```
 *
 * Generated by `tools/marlin/gen_mcommands.py` from `doc/marlin-gcode/commands.json`,
 * extracted from MarlinFirmware/MarlinDocumentation at commit
 * `0856d12b0253378bc8d17a246fb09fc8c5437997`. Do not edit; regenerate.
 * How and why: `tools/marlin/README.md`, github.com/qw3rtrun/p3d-web-ui/issues/13.
 *
 * @property zeta `D` - zeta
 * @property hertz `F` - hertz
 * @property x `X`
 * @property y `Y`
 * @property z `Z`
 * @see <a href="https://marlinfw.org/docs/gcode/M593.html">MarlinFirmare M593 doc</a>
 */
data class ZVInputShaping(
    val zeta: BigDecimal? = null,
    val hertz: BigDecimal? = null,
    val x: Boolean = false,
    val y: Boolean = false,
    val z: Boolean = false,
) : GRq<ZVInputShaping> {

    override fun encode(): GCommand {
        val words = ArrayList<GWord>(5)
        if (zeta != null) words.add(word('D', zeta.toPlainString()))
        if (hertz != null) words.add(word('F', hertz.toPlainString()))
        if (x) words.add(flag('X'))
        if (y) words.add(flag('Y'))
        if (z) words.add(flag('Z'))
        return M(593, *words.toTypedArray())
    }

    override fun toString(): String {
        return javaClass.simpleName + "(" + GEncoder.encode(encode()) + ')'
    }

    companion object : GRqDecoder<ZVInputShaping> {

        override fun head(): GParameterWord<*> {
            return M(593).head
        }

        override fun decodeParams(tokens: List<GToken>): ZVInputShaping {
            return ZVInputShaping(
                zeta = tokens.decimalOf('D'),
                hertz = tokens.decimalOf('F'),
                x = tokens.hasWord('X'),
                y = tokens.hasWord('Y'),
                z = tokens.hasWord('Z'),
            )
        }
    }
}
